CodeSystem: StrokeMedicationCS
Id: stroke-medication
Title: "腦中風－藥品與藥物類別代碼"
Description: "此 CodeSystem 定義本 IG 記錄腦中風用藥的本地代碼，涵蓋藥物類別（如抗凝血藥、抗血小板藥、降血脂藥）、個別藥品（如 aspirin、warfarin、各類 NOAC）與治療方式（如雙重抗血小板治療）。代碼僅代表藥名或藥物類別。"
* ^identifier[0].system = "urn:ietf:rfc:3986"
* ^identifier[0].value = "urn:oid:2.25.264839284167749472549460884988440265748"
* ^status = #draft
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #anticoagulant "抗凝血藥" "抗凝血藥物類別，未指明品項。"
* #vka "維生素 K 拮抗劑（VKA）" "維生素 K 拮抗劑類口服抗凝血藥，未指明品項。"
* #noac "非維生素 K 口服抗凝血藥（NOAC）" "非維生素 K 拮抗劑的口服抗凝血藥類別。品項不明時使用，已知品項時改用 dabigatran、rivaroxaban、apixaban 或 edoxaban。"
* #other-anticoagulant "其他抗凝血藥" "維生素 K 拮抗劑與 NOAC 以外的抗凝血藥，未指明品項。"
* #antiplatelet "抗血小板藥" "抗血小板藥物類別，未指明品項。"
* #antihypertensive "降血壓藥" "降血壓藥物類別，未指明品項。"
* #antiarrhythmic "抗心律不整藥" "抗心律不整藥物類別，未指明品項。"
* #diabetes-medication "糖尿病藥" "治療糖尿病的藥物類別，未區分口服降血糖藥或胰島素，未指明品項。"
* #lipid-lowering "降血脂藥" "降血脂藥物類別，未區分 statin 或非 statin 類，未指明品項。"
* #statin "statin 類降血脂藥" "statin 類降血脂藥，未指明品項。"
* #non-statin-lipid-lowering "非 statin 類降血脂藥" "statin 以外的降血脂藥，未指明品項。"
* #aggrenox "Aggrenox（aspirin／dipyridamole）" "含 aspirin 與 dipyridamole 的複方抗血小板藥，商品名 Aggrenox。"
* #aspirin "Aspirin" "Aspirin，抗血小板藥。"
* #ticlopidine "Ticlopidine" "Ticlopidine，抗血小板藥。"
* #warfarin "Warfarin" "Warfarin，維生素 K 拮抗劑類口服抗凝血藥。此代碼只代表 warfarin 單一藥品。"
* #clopidogrel "Clopidogrel" "Clopidogrel，抗血小板藥。"
* #cilostazol-brand "Pletaal（cilostazol）" "Cilostazol，抗血小板藥，商品名 Pletaal。"
* #lmw-heparin "低分子量肝素（LMWH）" "低分子量肝素類抗凝血藥，未指明品項。"
* #apixaban "Apixaban" "Apixaban，非維生素 K 口服抗凝血藥（NOAC）。"
* #dabigatran "Dabigatran" "Dabigatran，非維生素 K 口服抗凝血藥（NOAC）。"
* #edoxaban "Edoxaban" "Edoxaban，非維生素 K 口服抗凝血藥（NOAC）。"
* #rivaroxaban "Rivaroxaban" "Rivaroxaban，非維生素 K 口服抗凝血藥（NOAC）。"
* #ticagrelor "Ticagrelor" "Ticagrelor，抗血小板藥。"
* #inhibitor-unspecified "Inhibitor 使用註記（類別未明）" "只知道曾使用 inhibitor，未說明是哪一類抑制劑。"
* #dapt "雙重抗血小板治療（DAPT）" "同時使用兩種抗血小板藥的治療方式，未指明藥品組合。"
* #sapt "單一抗血小板治療（SAPT）" "只使用一種抗血小板藥的治療方式，未指明品項。"
* #oral-hypoglycemic "口服降血糖藥（OHA）" "口服降血糖藥物類別，未指明品項。"
* #insulin "胰島素" "胰島素類降血糖藥，未指明品項與劑型。"
* #iv-tpa-unspecified "靜脈血栓溶解劑 IV-tPA（品項未明）" "經靜脈給予的血栓溶解劑（tPA）。只知道是 IV-tPA、未指明為 alteplase 或 tenecteplase 時使用。"
* #heparin "Heparin（肝素）" "Heparin 抗凝血藥，未指明製劑。"
