CodeSystem: StrokeObservationCS
Id: stroke-observation
Title: "腦中風－觀察項目代碼"
Description: "此 CodeSystem 定義本 IG 的 Observation.code 本地觀察項目代碼，涵蓋就醫背景、發病時間、危險因子與病史、中風分類評估、照護流程、住院併發症與惡化、EVT 處置細節與術後結果、離院與追蹤結果、影像判讀、處置時點及檢驗結果。各代碼定義均載明應填的 value[x] 型別、可選值、單位與缺值處理。NIHSS、mRS 與 GCS 使用 LOINC，此處不收錄。"
* ^identifier[0].system = "urn:ietf:rfc:3986"
* ^identifier[0].value = "urn:oid:2.25.264350442306904858610685909312356390144"
* ^status = #draft
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete

// 就醫背景（StrokeAdmissionContext）
* #admission-source "就醫來源" "本次就醫或住院的來源類別。valueCodeableConcept：1＝急診，2＝直入病房，3＝院內中風，A＝住院，E＝急診，O＝門診。數字代碼與英文代碼屬於不同分類。"
* #arrival-mode "到院方式" "病人抵達醫院的方式。valueCodeableConcept：1＝緊急醫療救護（EMS），2＝自行到院，3＝轉院，NONE＝無。"
* #not-hospitalized "未住院" "本次就醫未住院。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #patient-age "病人年齡" "本次就醫時病人的年齡，填 valueQuantity，單位 a（年）。"
* #education-level "教育程度" "病人的最高教育程度。valueCodeableConcept：EDU00＝無，EDU01＝小學，EDU02＝國中，EDU03＝高中職，EDU04＝大專，EDU05＝研究所，EDU99＝不詳。"

// 發病時間（StrokeOnsetTime）
* #stroke-onset-time "中風發病時間" "本次中風症狀出現的日期與時間，填 valueDateTime。有日期與時間時，時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；時區確認後填完整日期時間與時區（例如 +08:00），來源只到分鐘時，秒填 00。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間沒有日期時，改以 StrokeEventTimeOnly 擴充保留時間。"
* #onset-time-uncertain "發病時間不確定" "發病時間是否無法確定。valueBoolean：true＝不確定，false＝確定。"
* #last-known-well "最後正常時間" "最後一次確認病人沒有中風症狀的日期與時間，填 valueDateTime。有日期與時間時，時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；時區確認後填完整日期時間與時區（例如 +08:00），來源只到分鐘時，秒填 00。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間沒有日期時，改以 StrokeEventTimeOnly 擴充保留時間。"
* #wake-up-stroke "醒後中風" "是否為睡醒後才發現症狀的中風。valueBoolean：true＝是，false＝否。"

// 危險因子與病史（StrokeRiskFactor）
* #hypertension-history "高血壓病史" "是否有高血壓病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #hypertension-newly-diagnosed "高血壓為本次新診斷" "高血壓是否在本次就醫時才診斷出來。valueBoolean：true＝是，false＝否。"
* #diabetes-history "糖尿病病史" "是否有糖尿病病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #diabetes-newly-diagnosed "糖尿病為本次新診斷" "糖尿病是否在本次就醫時才診斷出來。valueBoolean：true＝是，false＝否。"
* #prior-stroke-history "既往腦中風病史" "本次中風前是否曾發生腦中風。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #prior-cerebral-infarction-history "既往腦梗塞病史" "本次中風前是否曾發生腦梗塞。valueBoolean：true＝有，false＝沒有。"
* #prior-cerebral-hemorrhage-history "既往腦出血病史" "本次中風前是否曾發生腦出血。valueBoolean：true＝有，false＝沒有。"
* #prior-tia-history "既往短暫性腦缺血病史" "本次中風前是否曾發生短暫性腦缺血（TIA）。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #heart-disease-history "心臟病病史" "是否有心臟病病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #chronic-kidney-disease-history "慢性腎臟病病史" "是否有慢性腎臟病病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #dialysis-treatment "透析治療" "是否接受透析治療。valueBoolean：true＝有，false＝沒有。"
* #peripheral-artery-disease-history "周邊動脈疾病病史" "是否有周邊動脈疾病病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #dyslipidemia-history "血脂異常病史" "是否有血脂異常病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #hypertriglyceridemia-history "高三酸甘油脂血症病史" "是否有高三酸甘油脂血症病史。valueBoolean：true＝有，false＝沒有。"
* #hypercholesterolemia-history "高膽固醇血症病史" "是否有高膽固醇血症病史。valueBoolean：true＝有，false＝沒有。"
* #smoking-history "吸菸史" "是否有吸菸史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #cigarettes-per-day "每日吸菸量" "平均每天吸菸支數，填 valueQuantity，單位 {cigarette}/d（支／天）。"
* #smoking-duration "吸菸年數" "累計吸菸年數，填 valueQuantity，單位 a（年）。"
* #alcohol-use-history "飲酒史" "是否有飲酒史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #cancer-history "癌症病史" "是否有癌症病史。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #cancer-name "癌症名稱" "癌症病史的癌症名稱。valueString，原樣填入文字。"
* #other-risk-factor "其他危險因子" "是否有其他中風危險因子。valueBoolean：true＝有，false＝沒有。資料為「不確定」時不填值，改填 dataAbsentReason = unknown。"
* #other-risk-factor-name "其他危險因子名稱" "其他中風危險因子的名稱。valueString，原樣填入文字。"
* #polycythemia-history "紅血球增多症病史" "是否有紅血球增多症。valueBoolean：true＝有，false＝沒有。"
* #uremia-history "尿毒症病史" "是否有尿毒症。valueBoolean：true＝有，false＝沒有。"
* #family-history-hypertension "高血壓家族史" "家族中是否有人患高血壓。valueBoolean：true＝有，false＝沒有。資料為「不知道」時不填值，改填 dataAbsentReason = unknown。"
* #family-history-diabetes "糖尿病家族史" "家族中是否有人患糖尿病。valueBoolean：true＝有，false＝沒有。資料為「不知道」時不填值，改填 dataAbsentReason = unknown。"
* #family-history-ischemic-heart-disease "缺血性心臟病家族史" "家族中是否有人患缺血性心臟病。valueBoolean：true＝有，false＝沒有。資料為「不知道」時不填值，改填 dataAbsentReason = unknown。"
* #family-history-stroke-or-tia "中風或短暫性腦缺血家族史" "家族中是否有人發生腦中風或短暫性腦缺血。valueBoolean：true＝有，false＝沒有。資料為「不知道」時不填值，改填 dataAbsentReason = unknown。"
* #no-heart-disease "無心臟病" "病人無任何心臟病。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #atrial-fibrillation-history "心房顫動病史" "是否有心房顫動病史。valueBoolean：true＝有，false＝沒有。"
* #atrial-fibrillation-newly-diagnosed "心房顫動為本次新診斷" "心房顫動是否在本次就醫時才診斷出來。valueBoolean：true＝是，false＝否。"
* #ischemic-heart-disease-history "缺血性心臟病病史" "是否有缺血性心臟病病史。valueBoolean：true＝有，false＝沒有。"
* #acute-mi-within-4-weeks "4 週內急性心肌梗塞" "本次中風前 4 週內是否發生急性心肌梗塞。valueBoolean：true＝有，false＝沒有。與 acute-mi-history 的期間定義不同。"
* #acute-mi-history "急性心肌梗塞病史（期間未定）" "是否有急性心肌梗塞病史，不限發生期間。valueBoolean：true＝有，false＝沒有。與 acute-mi-within-4-weeks 的定義不同。"
* #valvular-heart-disease-history "心瓣膜疾病病史" "是否有心瓣膜疾病。valueBoolean：true＝有，false＝沒有。"
* #valvular-heart-disease-name "心瓣膜疾病名稱" "心瓣膜疾病的名稱。valueString，原樣填入文字。"
* #heart-failure-history "心衰竭病史" "是否有心衰竭病史。valueBoolean：true＝有，false＝沒有。"
* #valve-replacement-history "瓣膜置換病史" "是否曾接受心臟瓣膜置換。valueBoolean：true＝有，false＝沒有。"
* #mechanical-heart-valve "機械瓣膜" "是否裝有機械心臟瓣膜。valueBoolean：true＝有，false＝沒有。"
* #prosthetic-heart-valve "人工瓣膜" "是否裝有人工心臟瓣膜（prosthetic valve）。valueBoolean：true＝有，false＝沒有。"
* #other-heart-disease "其他心臟病" "其他心臟病的註記內容。valueString，原樣填入文字。"
* #other-heart-disease-name "其他心臟病名稱" "其他心臟病的名稱。valueString，原樣填入文字。"
* #endocarditis-history "心內膜炎病史" "是否有心內膜炎。valueBoolean：true＝有，false＝沒有。"
* #cardiac-myxoma-history "心臟黏液瘤病史" "是否有心臟黏液瘤。valueBoolean：true＝有，false＝沒有。"
* #rheumatic-heart-disease-history "風濕性心臟病病史" "是否有風濕性心臟病。valueBoolean：true＝有，false＝沒有。"
* #patent-foramen-ovale "開放性卵圓孔" "是否有開放性卵圓孔（PFO）。valueBoolean：true＝有，false＝沒有。"

// 中風分類評估（StrokeClinicalAssessment）
* #stroke-type-infarction "中風類型：腦梗塞" "本次中風是否為腦梗塞。valueString，原樣填入來源內容。"
* #stroke-type-tia "中風類型：短暫性腦缺血" "本次是否為短暫性腦缺血（TIA）。valueBoolean：true＝是，false＝否。"
* #stroke-type-ich "中風類型：腦出血" "本次中風是否為腦出血（ICH）。valueBoolean：true＝是，false＝否。"
* #stroke-type-sah "中風類型：蜘蛛網膜下腔出血" "本次中風是否為蜘蛛網膜下腔出血（SAH）。valueBoolean：true＝是，false＝否。"
* #stroke-subtype-tia-ich-sah "TIA／ICH／SAH 次分類" "短暫性腦缺血、腦出血或蜘蛛網膜下腔出血的次分類。valueString，原樣填入文字。常見內容如 Carotid、VB、Hypertensive、Non-Hypertensive、aneurysm、Angio negative。"
* #toast-classification "TOAST 分類" "缺血性中風的 TOAST 病因分類。valueCodeableConcept：1＝大動脈粥狀硬化，3＝心因性栓塞，4＝其他特定病因，5＝病因不明，svo＝小血管阻塞。"
* #toast-laa-extracranial "TOAST 大動脈粥狀硬化：顱外" "大動脈粥狀硬化病灶是否位於顱外。valueBoolean：true＝是，false＝否。"
* #toast-laa-intracranial "TOAST 大動脈粥狀硬化：顱內" "大動脈粥狀硬化病灶是否位於顱內。valueBoolean：true＝是，false＝否。"
* #toast-specific-etiology "TOAST 其他特定病因說明" "TOAST 分類為其他特定病因時的病因說明。valueString，原樣填入文字。"
* #ecg-atrial-fibrillation "心電圖心房顫動" "本次心電圖是否顯示心房顫動。valueBoolean：true＝是，false＝否。"
* #ich-score "ICH 分數" "腦出血病人的 ICH 嚴重度分數（通常為 0–6 分）。valueString，原樣填入來源分數。"
* #hunt-hess-grade "Hunt and Hess 分級" "蜘蛛網膜下腔出血病人的 Hunt and Hess 臨床分級（通常為 1–5 級）。valueString，原樣填入來源分級。"
* #pre-stroke-independent "中風前可獨立生活" "本次中風前是否能獨立生活。valueBoolean：true＝是，false＝否。"

// 照護流程紀錄（StrokeCareProcess）
* #no-pre-admission-medication "住院前無用藥" "住院前是否未用任何登錄藥物類別。valueBoolean：true＝是，false＝否。"
* #icu-admission "入住加護病房" "住院期間是否入住加護病房（ICU）。valueBoolean：true＝有，false＝沒有。"
* #first-ct-mri-from-outside-hospital "首次 CT／MRI 為外院影像" "第一次 CT 或 MRI 是否在外院完成。valueBoolean：true＝是，false＝否。"
* #ivtpa-not-given-main-reason "未施打 IV-tPA 主要原因" "未施打靜脈血栓溶解劑（IV-tPA）的主因。valueCodeableConcept：REA01＝發作超過 3 小時或發作時間不明，REA02＝發作至到院 2 小時內但不符合施打條件，REA03＝發作至到院 2 至 3 小時內但不符合施打條件。"
* #ivtpa-not-given-onset-over-3h "未施打 IV-tPA：發作超過 3 小時" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：給藥前缺血性中風發作超過 3 小時。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-mild-or-improving "未施打 IV-tPA：症狀輕微或快速改善" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：給藥前症狀快速改善或輕微（例如 NIHSS < 4）。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-severe-stroke "未施打 IV-tPA：嚴重中風" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：臨床或影像判定為嚴重中風（例如 NIHSS > 25）。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-age-out-of-range "未施打 IV-tPA：年齡不符" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：年齡 18 歲以下或 80 歲以上。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-prior-stroke-with-diabetes "未施打 IV-tPA：曾中風合併糖尿病" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：曾中風且合併糖尿病。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-high-blood-pressure "未施打 IV-tPA：血壓過高" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：收縮壓 > 185 mmHg 或舒張壓 > 110 mmHg。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-recent-stroke-or-head-trauma "未施打 IV-tPA：近期中風或頭部外傷" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：近 3 個月內曾中風或嚴重頭部外傷。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-seizure-at-onset "未施打 IV-tPA：發作時併發癲癇" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：中風發作時併發癲癇。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-oral-anticoagulant "未施打 IV-tPA：正使用口服抗凝血劑" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：正使用口服抗凝血劑（例如 warfarin，INR > 1.3）。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #ivtpa-not-given-family-refusal "未施打 IV-tPA：家屬拒絕" "未施打靜脈血栓溶解劑（IV-tPA）的原因之一：家屬拒絕。valueBoolean：true＝有此原因，false＝沒有此原因。"
* #no-antithrombotic-within-24h "EVT 後 24 小時內未用抗血栓藥" "EVT 後 24 小時內未用抗血栓藥物。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #no-surgery "無手術治療" "住院期間未接受手術治療。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #no-discharge-medication "離院時無用藥" "離院時是否未用任何登錄藥物類別。valueBoolean：true＝是，false＝否。"

// 住院併發症與惡化（StrokeComplication）
* #no-complication "無住院併發症" "住院期間未發生併發症。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #complication-pneumonia "住院併發症：肺炎" "住院期間是否發生肺炎。valueBoolean：true＝有，false＝沒有。"
* #complication-sepsis "住院併發症：敗血症" "住院期間是否發生敗血症。valueBoolean：true＝有，false＝沒有。"
* #complication-urinary-tract-infection "住院併發症：泌尿道感染" "住院期間是否發生泌尿道感染。valueBoolean：true＝有，false＝沒有。"
* #complication-acute-coronary-syndrome "住院併發症：急性冠心症" "住院期間是否發生急性冠心症。valueBoolean：true＝有，false＝沒有。"
* #complication-upper-gi-bleeding "住院併發症：上消化道出血" "住院期間是否發生上消化道出血。valueBoolean：true＝有，false＝沒有。"
* #complication-seizure "住院併發症：癲癇發作" "住院期間是否發生癲癇發作。valueBoolean：true＝有，false＝沒有。"
* #complication-renal-failure "住院併發症：腎衰竭" "住院期間是否發生腎衰竭。valueBoolean：true＝有，false＝沒有。"
* #complication-deep-vein-thrombosis "住院併發症：深部靜脈栓塞" "住院期間是否發生深部靜脈栓塞。valueBoolean：true＝有，false＝沒有。"
* #neurologic-deterioration-nihss-2-or-more "中風惡化（NIHSS 增加至少 2 分）" "住院期間是否發生中風惡化，以 NIHSS 至少增加 2 分為判定標準。valueBoolean：true＝有，false＝沒有。與 neurologic-deterioration-criteria-unspecified 的判定標準不同。"
* #neurologic-deterioration-criteria-unspecified "中風惡化（判定標準未定）" "住院期間是否發生中風惡化，未指明判定標準與計算區間。valueBoolean：true＝有，false＝沒有。與 neurologic-deterioration-nihss-2-or-more 的判定標準不同。"
* #complication-other "住院併發症：其他" "住院期間是否發生其他併發症。valueBoolean：true＝有，false＝沒有。"
* #complication-other-name "其他住院併發症名稱" "其他住院併發症的名稱。valueString，原樣填入文字。"
* #deterioration-cause-herniation "惡化原因：腦疝脫" "住院期間神經學惡化的原因是否為腦疝脫。valueBoolean：true＝是，false＝否。"
* #deterioration-cause-hemorrhagic-infarct-36h "惡化原因：36 小時內出血性梗塞" "住院期間神經學惡化的原因是否為 36 小時內出血性梗塞。valueBoolean：true＝是，false＝否。"
* #deterioration-cause-hematoma-expansion "惡化原因：血腫擴大" "住院期間神經學惡化的原因是否為血腫擴大（腦出血）。valueBoolean：true＝是，false＝否。"
* #deterioration-cause-vasospasm "惡化原因：血管痙攣" "住院期間神經學惡化的原因是否為血管痙攣（蜘蛛網膜下腔出血）。valueBoolean：true＝是，false＝否。"
* #deterioration-cause-rebleeding "惡化原因：再出血" "住院期間神經學惡化的原因是否為再出血（蜘蛛網膜下腔出血）。valueBoolean：true＝是，false＝否。"
* #deterioration-cause-medical-problem "惡化原因：內科問題" "住院期間神經學惡化的原因是否為內科問題。valueBoolean：true＝是，false＝否。"

// EVT 處置細節（StrokeEvtProcedureDetail）
* #no-perfusion-imaging "未執行灌流影像" "EVT 前未執行 CT 灌流或 MR 灌流影像。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #ct-perfusion-performed "執行 CT 灌流影像" "EVT 前是否執行 CT 灌流影像（CTP）。valueBoolean：true＝有，false＝沒有。"
* #mr-perfusion-performed "執行 MR 灌流影像" "EVT 前是否執行 MR 灌流影像（MRP）。valueBoolean：true＝有，false＝沒有。"
* #perfusion-analysis-rapid "以 RAPID 軟體分析灌流影像" "灌流影像是否以 RAPID 軟體分析。valueBoolean：true＝是，false＝否。"
* #perfusion-analysis-other-software "以其他軟體分析灌流影像" "灌流影像是否以 RAPID 以外的軟體分析。valueBoolean：true＝是，false＝否。"
* #aortic-arch-type "主動脈弓分型" "主動脈弓分型。valueCodeableConcept：1＝第 I 型，2＝第 II 型，3＝第 III 型。"
* #right-cca-stenosis "右總頸動脈狹窄程度" "右側總頸動脈的狹窄程度分組。valueCodeableConcept：1＝< 50%，2＝50–99%，3＝100%（完全阻塞）。"
* #left-cca-stenosis "左總頸動脈狹窄程度" "左側總頸動脈的狹窄程度分組。valueCodeableConcept：1＝< 50%，2＝50–99%，3＝100%（完全阻塞）。"
* #right-vertebral-artery-stenosis "右椎動脈狹窄程度" "右側椎動脈的狹窄程度分組。valueCodeableConcept：1＝< 50%，2＝50–99%，3＝100%（完全阻塞）。"
* #left-vertebral-artery-stenosis "左椎動脈狹窄程度" "左側椎動脈的狹窄程度分組。valueCodeableConcept：1＝< 50%，2＝50–99%，3＝100%（完全阻塞）。"
* #right-ica-stenosis "右內頸動脈狹窄程度" "右側內頸動脈的狹窄程度分組。valueCodeableConcept：1＝< 50%，2＝50–99%，3＝100%（完全阻塞）。"
* #left-ica-stenosis "左內頸動脈狹窄程度" "左側內頸動脈的狹窄程度分組。valueCodeableConcept：1＝< 50%，2＝50–99%，3＝100%（完全阻塞）。"
* #target-vessel-cervical-ica "目標血管：頸段內頸動脈" "EVT 的目標血管是否包含頸段內頸動脈（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-cervical-ica-right "目標血管：右側頸段內頸動脈" "EVT 的目標血管是否包含右側頸段內頸動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-cervical-ica-left "目標血管：左側頸段內頸動脈" "EVT 的目標血管是否包含左側頸段內頸動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-ica-terminus "目標血管：內頸動脈末端" "EVT 的目標血管是否包含內頸動脈末端（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-ica-terminus-right "目標血管：右側內頸動脈末端" "EVT 的目標血管是否包含右側內頸動脈末端。valueBoolean：true＝是，false＝否。"
* #target-vessel-ica-terminus-left "目標血管：左側內頸動脈末端" "EVT 的目標血管是否包含左側內頸動脈末端。valueBoolean：true＝是，false＝否。"
* #target-vessel-m1 "目標血管：中大腦動脈 M1 段" "EVT 的目標血管是否包含中大腦動脈 M1 段（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-m1-right "目標血管：右側中大腦動脈 M1 段" "EVT 的目標血管是否包含右側中大腦動脈 M1 段。valueBoolean：true＝是，false＝否。"
* #target-vessel-m1-left "目標血管：左側中大腦動脈 M1 段" "EVT 的目標血管是否包含左側中大腦動脈 M1 段。valueBoolean：true＝是，false＝否。"
* #target-vessel-m2 "目標血管：中大腦動脈 M2 段" "EVT 的目標血管是否包含中大腦動脈 M2 段（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-m2-right "目標血管：右側中大腦動脈 M2 段" "EVT 的目標血管是否包含右側中大腦動脈 M2 段。valueBoolean：true＝是，false＝否。"
* #target-vessel-m2-left "目標血管：左側中大腦動脈 M2 段" "EVT 的目標血管是否包含左側中大腦動脈 M2 段。valueBoolean：true＝是，false＝否。"
* #target-vessel-m3 "目標血管：中大腦動脈 M3 段" "EVT 的目標血管是否包含中大腦動脈 M3 段（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-m3-right "目標血管：右側中大腦動脈 M3 段" "EVT 的目標血管是否包含右側中大腦動脈 M3 段。valueBoolean：true＝是，false＝否。"
* #target-vessel-m3-left "目標血管：左側中大腦動脈 M3 段" "EVT 的目標血管是否包含左側中大腦動脈 M3 段。valueBoolean：true＝是，false＝否。"
* #target-vessel-aca "目標血管：前大腦動脈" "EVT 的目標血管是否包含前大腦動脈（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-aca-right "目標血管：右側前大腦動脈" "EVT 的目標血管是否包含右側前大腦動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-aca-left "目標血管：左側前大腦動脈" "EVT 的目標血管是否包含左側前大腦動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-pca "目標血管：後大腦動脈" "EVT 的目標血管是否包含後大腦動脈（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-pca-right "目標血管：右側後大腦動脈" "EVT 的目標血管是否包含右側後大腦動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-pca-left "目標血管：左側後大腦動脈" "EVT 的目標血管是否包含左側後大腦動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-basilar-artery "目標血管：基底動脈" "EVT 的目標血管是否包含基底動脈（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-vertebral-artery "目標血管：椎動脈" "EVT 的目標血管是否包含椎動脈（未區分側別）。valueBoolean：true＝是，false＝否。"
* #target-vessel-vertebral-artery-right "目標血管：右側椎動脈" "EVT 的目標血管是否包含右側椎動脈。valueBoolean：true＝是，false＝否。"
* #target-vessel-vertebral-artery-left "目標血管：左側椎動脈" "EVT 的目標血管是否包含左側椎動脈。valueBoolean：true＝是，false＝否。"
* #general-anesthesia "全身麻醉" "EVT 時是否採全身麻醉。valueBoolean：true＝是，false＝否。"
* #procedural-sedation "鎮靜" "EVT 時是否使用鎮靜。valueBoolean：true＝是，false＝否。"
* #no-evt-treatment-technique "未使用 EVT 治療技術" "EVT 過程未使用任何列出的治療技術（例如支架取栓、抽吸取栓、置放支架）。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #balloon-guide-catheter "使用球囊導引導管" "EVT 是否使用球囊導引導管（BGC）。valueBoolean：true＝有，false＝沒有。"
* #aspiration-strategy "抽吸取栓策略" "抽吸取栓採用的策略。valueCodeableConcept：1＝只用抽吸導管，2＝Solumbra（支架取栓器合併抽吸），3＝混合使用。"
* #stent-retriever-pass-count "支架取栓次數" "支架取栓器的取栓次數（pass 數）。valueString，原樣填入來源內容。"
* #aspiration-strategy-supplement "抽吸取栓策略（補充）" "抽吸取栓策略的補充選項。valueCodeableConcept：4＝先抽吸取栓，再接續救援治療。此項與 aspiration-strategy 分開記錄。"
* #aspiration-rescue-strategy "抽吸失敗後救援策略" "抽吸取栓未成功時採用的救援治療。valueCodeableConcept：rescue-sr＝改用支架取栓器，rescue-angioplasty＝血管成形術，rescue-thrombolysis＝血栓溶解，rescue-other＝其他。"
* #aspiration-rescue-other "抽吸失敗後其他救援方式" "抽吸失敗後救援策略為「其他」時的說明。valueString，原樣填入文字。"
* #stent-retriever-rescue-performed "支架取栓後救援治療" "支架取栓後是否接續救援治療。valueBoolean：true＝有，false＝沒有。"
* #stent-retriever-rescue-strategy "支架取栓後救援策略" "支架取栓後採用的救援治療。valueCodeableConcept：rescue-aspiration＝改用抽吸，rescue-angioplasty＝血管成形術，rescue-thrombolysis＝血栓溶解，rescue-other＝其他。"
* #stent-retriever-rescue-other "支架取栓後其他救援方式" "支架取栓後救援策略為「其他」時的說明。valueString，原樣填入文字。"

// EVT 術後結果（StrokeEvtOutcome）
* #final-tici-grade "最終 TICI 分級" "EVT 結束時的再灌流程度，以 TICI 分級表示。valueCodeableConcept：0、1、2a、2b、2c、3，等級越高代表再灌流越完整。"
* #rethrombosis-within-10-minutes "5–10 分鐘內再血栓" "血管再通後 5 至 10 分鐘內是否再形成血栓。valueBoolean：true＝有，false＝沒有。"
* #new-territory-embolism "新血管區域栓塞" "EVT 後是否在原本未受影響的血管區域發生栓塞。valueBoolean：true＝有，false＝沒有。"
* #new-territory-embolism-detail "新血管區域栓塞說明" "新血管區域栓塞的位置或細節。valueString，原樣填入文字。"
* #post-evt-bp-target "EVT 後血壓控制目標" "EVT 後的血壓控制目標上限。valueCodeableConcept：1＝< 180 mmHg，2＝< 160 mmHg，3＝< 140 mmHg，4＝< 120 mmHg。"
* #no-evt-complication "無 EVT 相關併發症" "EVT 未發生相關併發症。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #evt-arterial-dissection "EVT 血管剝離" "EVT 是否造成血管剝離。valueBoolean：true＝有，false＝沒有。"
* #evt-puncture-site-hematoma "EVT 穿刺處血腫" "EVT 後穿刺部位是否發生血腫。valueBoolean：true＝有，false＝沒有。"
* #evt-other-complication "其他 EVT 相關併發症" "是否發生其他 EVT 相關併發症。valueBoolean：true＝有，false＝沒有。"
* #no-follow-up-imaging "無追蹤影像" "EVT 後未執行追蹤影像。勾選時填 valueBoolean = true；未勾選不建立此項。"
* #follow-up-ct-performed "執行追蹤 CT" "EVT 後是否執行追蹤 CT。valueBoolean：true＝有，false＝沒有。"
* #follow-up-mri-performed "執行追蹤 MRI" "EVT 後是否執行追蹤 MRI。valueBoolean：true＝有，false＝沒有。"
* #follow-up-imaging-ich "追蹤影像顯示顱內出血" "EVT 後追蹤影像是否顯示顱內出血。valueBoolean：true＝有，false＝沒有。"
* #follow-up-ich-symptom-type "追蹤影像顱內出血症狀分類" "追蹤影像發現顱內出血時的症狀分類。valueCodeableConcept：1＝有症狀（36 小時內 NIHSS 增加 4 分），2＝無症狀。"
* #follow-up-imaging-infarct "追蹤影像顯示梗塞" "EVT 後追蹤影像是否顯示梗塞。valueBoolean：true＝有，false＝沒有。"
* #follow-up-imaging-other-finding "追蹤影像其他發現" "EVT 後追蹤影像是否有其他發現。valueBoolean：true＝有，false＝沒有。"

// 離院與追蹤結果（StrokeOutcome）
* #discharge-death-cause "離院死亡原因" "病人於本次住院期間死亡、以死亡離院時的死因類別。valueCodeableConcept：1＝中風直接致死，2＝其他。"
* #discharge-death-cause-other "離院其他死亡原因說明" "離院死亡原因為「其他」時的說明。valueString，原樣填入文字。"
* #discharge-destination "離院去向" "病人離院後的去處。valueCodeableConcept：1＝回家，2＝護理之家，3＝呼吸照護病房，4＝轉院。"
* #three-month-residence "中風後 3 個月所在處所" "中風後 3 個月追蹤時病人所在處所。valueCodeableConcept：1＝住家，2＝護理之家，3＝呼吸照護病房，4＝本院住院中，5＝轉至其他醫院，6＝失聯。"
* #three-month-follow-up-not-completed "3 個月追蹤未完成" "中風後 3 個月追蹤是否未完成。valueBoolean：true＝未完成，false＝否。"
* #follow-up-care-status "追蹤期間醫療狀態" "追蹤期間病人的醫療狀態。valueCodeableConcept：1＝繼續回診服藥，2＝拒絕回診，3＝死亡。"
* #follow-up-refusal-reason "拒絕回診說明" "病人拒絕回診的原因說明。valueString，原樣填入文字。"
* #follow-up-death-cause "追蹤期間死亡原因" "追蹤期間的死因類別。valueCodeableConcept：1＝因中風死亡，2＝其他。"
* #follow-up-death-hemorrhagic-stroke "因出血性中風死亡" "追蹤期間是否因出血性中風死亡。valueBoolean：true＝是，false＝否。"
* #follow-up-death-ischemic-stroke "因缺血性中風死亡" "追蹤期間是否因缺血性中風死亡。valueBoolean：true＝是，false＝否。"
* #follow-up-death-cause-other "追蹤期間其他死亡原因說明" "追蹤期間死亡原因為「其他」時的說明。valueString，原樣填入文字。"
* #recurrent-stroke "追蹤期間再中風" "追蹤期間是否再次中風。valueBoolean：true＝有，false＝沒有。"
* #recurrent-hemorrhagic-stroke "再發出血性中風" "追蹤期間的再中風是否為出血性中風。valueBoolean：true＝是，false＝否。"
* #recurrent-ischemic-stroke "再發缺血性中風" "追蹤期間的再中風是否為缺血性中風。valueBoolean：true＝是，false＝否。"
* #recurrent-stroke-date "再中風日期" "追蹤期間再次中風的日期，填 valueDateTime，格式 YYYY-MM-DD；只知道年月時填 YYYY-MM。"

// 影像判讀結果（StrokeImagingResult）
* #aspects-score "ASPECTS 分數" "EVT 前影像的 Alberta 中風早期 CT 分數（ASPECTS），用來評估中大腦動脈供血區的早期缺血變化。填 valueInteger，範圍 0–10，分數越低代表缺血範圍越大。"
* #perfusion-mismatch-ratio "灌流 mismatch 比值" "灌流影像低灌流體積與核心梗塞體積的比值，依影像分析軟體輸出的原值填 valueQuantity，單位 1（無單位比值）。無法計算時不填值，改填 dataAbsentReason = unknown；實際為 0 時照填 0。"
* #perfusion-core-volume "灌流核心梗塞體積" "灌流影像判定的核心梗塞體積（CBF < 30% 區域），填 valueQuantity，單位 mL。"
* #perfusion-mismatch-volume "灌流 mismatch 體積" "灌流影像低灌流區與核心梗塞區的體積差，依影像分析軟體輸出的原值填 valueQuantity，單位 mL。"
* #mcta-collateral-grade "多期 CTA 側枝循環分級" "多期電腦斷層血管攝影（mCTA）的側枝循環分組。valueCodeableConcept：1＝0–2 分，2＝3–4 分，3＝5 分。"
* #aspects-affected-side "ASPECTS 影響側" "ASPECTS 評估的受影響腦側。valueCodeableConcept：L＝左腦，R＝右腦。"
* #cta-affected-side "CTA 影響側" "電腦斷層血管攝影（CTA）判讀的受影響腦側。valueCodeableConcept：L＝左腦，R＝右腦。"
* #tmax-over-6s-volume "Tmax > 6 秒體積" "灌流影像中 Tmax 大於 6 秒的低灌流體積，填 valueQuantity，單位 mL。"
* #hypoperfusion-intensity-ratio "低灌流強度比值（HIR）" "Tmax 大於 10 秒體積除以 Tmax 大於 6 秒體積的比值，填 valueQuantity，單位 1（無單位比值），數值介於 0 至 1。"

// 處置時點結果（StrokeProcedureResult）
* #reperfusion-time "再灌流時間" "治療後達到腦部再灌流的日期與時間，填 valueDateTime。有日期與時間時，時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；時區確認後填完整日期時間與時區（例如 +08:00），來源只到分鐘時，秒填 00。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間沒有日期時，改以 StrokeEventTimeOnly 擴充保留時間。"
* #first-recanalization-time "首次血管再通時間" "EVT 中目標血管第一次再通的日期與時間，填 valueDateTime。有日期與時間時，時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；時區確認後填完整日期時間與時區（例如 +08:00），來源只到分鐘時，秒填 00。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間沒有日期時，改以 StrokeEventTimeOnly 擴充保留時間。"
* #final-recanalization-time "最終血管再通時間" "EVT 結束時目標血管最終再通的日期與時間，填 valueDateTime。有日期與時間時，時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；時區確認後填完整日期時間與時區（例如 +08:00），來源只到分鐘時，秒填 00。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間沒有日期時，改以 StrokeEventTimeOnly 擴充保留時間。"

// 檢驗結果（StrokeLaboratory）
* #hemoglobin "血紅素（Hb）" "血液中的血紅素濃度，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #hematocrit "血比容（Hct）" "紅血球占全血體積的比例，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #platelet-count "血小板數" "血液中的血小板數量，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #ptt "部分凝血活酶時間（PTT）" "部分凝血活酶時間檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #prothrombin-time "凝血酶原時間（PT）" "凝血酶原時間檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #pt-inr "凝血酶原時間國際標準化比值（INR）" "凝血酶原時間的國際標準化比值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #hba1c "糖化血色素（HbA1c）" "糖化血色素檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #wbc-count "白血球數（WBC）" "血液中的白血球數量，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #glucose-at-emergency "急診血糖" "到院急診時測得的血糖值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #bun "血中尿素氮（BUN）" "血中尿素氮檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #creatinine "肌酸酐" "血液肌酸酐檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #fasting-glucose-first "第一次空腹血糖" "住院後第一次空腹血糖值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #total-cholesterol "總膽固醇" "血液總膽固醇檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #triglyceride "三酸甘油脂" "血液三酸甘油脂檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #hdl-cholesterol "高密度脂蛋白膽固醇（HDL-C）" "高密度脂蛋白膽固醇檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #ldl-cholesterol "低密度脂蛋白膽固醇（LDL-C）" "低密度脂蛋白膽固醇檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #ast "天門冬胺酸轉胺酶（AST／GOT）" "天門冬胺酸轉胺酶檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #alt "丙胺酸轉胺酶（ALT／GPT）" "丙胺酸轉胺酶檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #ptt-control "PTT 對照值" "部分凝血活酶時間檢驗的正常對照值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #albumin "白蛋白" "血液白蛋白檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #crp "C 反應蛋白（CRP）" "C 反應蛋白檢驗值，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
* #ua-unspecified "UA（項目待確認）" "UA 檢驗值，未區分尿酸或尿液檢查，填 valueQuantity。單位依實際檢驗結果以 UCUM 填寫，尚未確認時只填數值；未檢驗時不填數值，改填 dataAbsentReason = unknown。"
