// 原始值群組依 input/fsh/logicals/lm_*.fsh 的元素逐一列出；邏輯模型增刪欄位時須同步更新本檔。
Instance: stroke-registry
InstanceOf: Questionnaire
Usage: #definition
Title: "腦中風登錄表單"
Description: "腦中風登錄共用表單定義。包含正規化題目，以及個管系統、EVT 登錄與 RAPID 三個來源的原始值群組。"
* url = "http://vgh-stroke-ig.fhir.tw/Questionnaire/stroke-registry"
* version = "0.1.0"
* name = "StrokeRegistry"
* title = "腦中風登錄表單"
* status = #draft
* experimental = false
* publisher = "高雄榮民總醫院 (VGHKS)"
* subjectType = #Patient
* description = "腦中風登錄共用表單定義，供 StrokeRegistryResponse 回覆使用。正規化題目收納無法安全轉成臨床資源的欄位；原始值群組（raw.ncva、raw.evt、raw.rapid）依各來源邏輯模型列出各欄位，以字串保存原始值。"
* purpose = "所有來源的登錄回覆皆使用本表單。每個來源、每份表單、每位個案各建一份回覆，只填該來源有的題目。原始值群組中，資料表為群組題目，可重複的資料表（NIHSS、mRS 評估）每列建一個群組；欄位為字串題目，linkId 填 `raw.<來源>.<邏輯模型元素路徑>`。"
* item[0].linkId = "demographics.consent"
* item[0].text = "研究同意書簽署狀態"
* item[0].type = #boolean
* item[1].linkId = "demographics.consentDate"
* item[1].text = "研究同意書簽署日期"
* item[1].type = #date
* item[2].linkId = "inpatientTreatment.tre09"
* item[2].text = "住院期間簽署 DNR"
* item[2].type = #boolean
* item[3].linkId = "preEvt.beforeEvtIvtpa"
* item[3].text = "EVT 前 IV-tPA 施打院所"
* item[3].type = #choice
* item[3].answerValueSet = Canonical(StrokePreEvtIvtpaSiteVS)
* item[4].linkId = "rapid.rpreqno"
* item[4].text = "RAPID 影像申請序號"
* item[4].type = #string
* item[5].linkId = "discharge.leavePlaceHospital"
* item[5].text = "離院轉入醫院"
* item[5].type = #string
* item[6].linkId = "followUp3Month.traceThreePlaceHospital"
* item[6].text = "中風後 3 個月所在醫院"
* item[6].type = #string
* item[7].linkId = "followUpEvent.traceTreat1Hospital"
* item[7].text = "追蹤回診醫院"
* item[7].type = #string
* item[8].linkId = "followUpEvent.traceTreat2StrokeHospital"
* item[8].text = "再中風就醫醫院"
* item[8].type = #string
* item[9].linkId = "unresolved.NCVA.COMASCALE.UNNAMED_COL_19"
* item[9].text = "昏迷指數與生命徵象的額外欄位（第 19 欄，待確認）"
* item[9].type = #string
* item[10].linkId = "unresolved.NCVA.mRS.UNNAMED_COL_06"
* item[10].text = "mRS 評估的額外欄位（第 6 欄，待確認）"
* item[10].type = #string
* item[10].repeats = true
* item[11].linkId = "unresolved.NCVA.mRS.UNNAMED_COL_07"
* item[11].text = "mRS 評估的額外欄位（第 7 欄，待確認）"
* item[11].type = #string
* item[11].repeats = true
* item[12].linkId = "raw.ncva"
* item[12].text = "個管系統原始值"
* item[12].type = #group
* item[12].item[0].linkId = "raw.ncva.hisnummark"
* item[12].item[0].text = "病歷號"
* item[12].item[0].type = #string
* item[12].item[1].linkId = "raw.ncva.cmseqno"
* item[12].item[1].text = "個管流水序號"
* item[12].item[1].type = #string
* item[12].item[2].linkId = "raw.ncva.caseMain"
* item[12].item[2].text = "腦中風個案主檔"
* item[12].item[2].type = #group
* item[12].item[2].item[0].linkId = "raw.ncva.caseMain.occdate"
* item[12].item[2].item[0].text = "發病日期"
* item[12].item[2].item[0].type = #string
* item[12].item[2].item[1].linkId = "raw.ncva.caseMain.occtime"
* item[12].item[2].item[1].text = "發生時間"
* item[12].item[2].item[1].type = #string
* item[12].item[2].item[2].linkId = "raw.ncva.caseMain.arrdate"
* item[12].item[2].item[2].text = "到院日期"
* item[12].item[2].item[2].type = #string
* item[12].item[2].item[3].linkId = "raw.ncva.caseMain.arrtime"
* item[12].item[2].item[3].text = "到院時間"
* item[12].item[2].item[3].type = #string
* item[12].item[2].item[4].linkId = "raw.ncva.caseMain.hdisdt"
* item[12].item[2].item[4].text = "病患離院日期"
* item[12].item[2].item[4].type = #string
* item[12].item[2].item[5].linkId = "raw.ncva.caseMain.psex"
* item[12].item[2].item[5].text = "病患性別"
* item[12].item[2].item[5].type = #string
* item[12].item[2].item[6].linkId = "raw.ncva.caseMain.hage"
* item[12].item[2].item[6].text = "病患年齡"
* item[12].item[2].item[6].type = #string
* item[12].item[2].item[7].linkId = "raw.ncva.caseMain.height"
* item[12].item[2].item[7].text = "病患身高"
* item[12].item[2].item[7].type = #string
* item[12].item[2].item[8].linkId = "raw.ncva.caseMain.weight"
* item[12].item[2].item[8].text = "病患體重"
* item[12].item[2].item[8].type = #string
* item[12].item[2].item[9].linkId = "raw.ncva.caseMain.edulevelcode"
* item[12].item[2].item[9].text = "病患教育程度代碼"
* item[12].item[2].item[9].type = #string
* item[12].item[2].item[10].linkId = "raw.ncva.caseMain.ocpcode"
* item[12].item[2].item[10].text = "職業選項代碼"
* item[12].item[2].item[10].type = #string
* item[12].item[2].item[11].linkId = "raw.ncva.caseMain.patfrom"
* item[12].item[2].item[11].text = "入院方式"
* item[12].item[2].item[11].type = #string
* item[12].item[2].item[12].linkId = "raw.ncva.caseMain.reachwaycode"
* item[12].item[2].item[12].text = "到院方式代碼"
* item[12].item[2].item[12].type = #string
* item[12].item[2].item[13].linkId = "raw.ncva.caseMain.levoption"
* item[12].item[2].item[13].text = "離院情形代碼"
* item[12].item[2].item[13].type = #string
* item[12].item[3].linkId = "raw.ncva.comaScale"
* item[12].item[3].text = "昏迷指數與生命徵象"
* item[12].item[3].type = #group
* item[12].item[3].item[0].linkId = "raw.ncva.comaScale.gcsM"
* item[12].item[3].item[0].text = "GCS 動作反應"
* item[12].item[3].item[0].type = #string
* item[12].item[3].item[1].linkId = "raw.ncva.comaScale.gcsE"
* item[12].item[3].item[1].text = "GCS 睜眼反應"
* item[12].item[3].item[1].type = #string
* item[12].item[3].item[2].linkId = "raw.ncva.comaScale.gcsV"
* item[12].item[3].item[2].text = "GCS 語言反應"
* item[12].item[3].item[2].type = #string
* item[12].item[3].item[3].linkId = "raw.ncva.comaScale.sbp"
* item[12].item[3].item[3].text = "收縮壓"
* item[12].item[3].item[3].type = #string
* item[12].item[3].item[4].linkId = "raw.ncva.comaScale.dbp"
* item[12].item[3].item[4].text = "舒張壓"
* item[12].item[3].item[4].type = #string
* item[12].item[3].item[5].linkId = "raw.ncva.comaScale.bt"
* item[12].item[3].item[5].text = "體溫"
* item[12].item[3].item[5].type = #string
* item[12].item[3].item[6].linkId = "raw.ncva.comaScale.hr"
* item[12].item[3].item[6].text = "心跳"
* item[12].item[3].item[6].type = #string
* item[12].item[3].item[7].linkId = "raw.ncva.comaScale.rr"
* item[12].item[3].item[7].text = "呼吸"
* item[12].item[3].item[7].type = #string
* item[12].item[3].item[8].linkId = "raw.ncva.comaScale.icd10"
* item[12].item[3].item[8].text = "ICD-10 診斷碼"
* item[12].item[3].item[8].type = #string
* item[12].item[3].item[9].linkId = "raw.ncva.comaScale.infarct"
* item[12].item[3].item[9].text = "腦梗塞"
* item[12].item[3].item[9].type = #string
* item[12].item[3].item[10].linkId = "raw.ncva.comaScale.stkdiagnosisoption1"
* item[12].item[3].item[10].text = "TOAST 分類"
* item[12].item[3].item[10].type = #string
* item[12].item[3].item[11].linkId = "raw.ncva.comaScale.stkdiagnosisoption2"
* item[12].item[3].item[11].text = "TOAST 次分類"
* item[12].item[3].item[11].type = #string
* item[12].item[3].item[12].linkId = "raw.ncva.comaScale.tia"
* item[12].item[3].item[12].text = "短暫性腦缺血"
* item[12].item[3].item[12].type = #string
* item[12].item[3].item[13].linkId = "raw.ncva.comaScale.ich"
* item[12].item[3].item[13].text = "腦出血"
* item[12].item[3].item[13].type = #string
* item[12].item[3].item[14].linkId = "raw.ncva.comaScale.sah"
* item[12].item[3].item[14].text = "蜘蛛網膜下腔出血"
* item[12].item[3].item[14].type = #string
* item[12].item[3].item[15].linkId = "raw.ncva.comaScale.stkdiagnosisoption3"
* item[12].item[3].item[15].text = "TIA／ICH／SAH 次分類"
* item[12].item[3].item[15].type = #string
* item[12].item[3].item[16].linkId = "raw.ncva.comaScale.unnamedCol19"
* item[12].item[3].item[16].text = "未命名欄位（第 19 欄）"
* item[12].item[3].item[16].type = #string
* item[12].item[4].linkId = "raw.ncva.nihss"
* item[12].item[4].text = "NIHSS 評估"
* item[12].item[4].type = #group
* item[12].item[4].repeats = true
* item[12].item[4].item[0].linkId = "raw.ncva.nihss.freqno"
* item[12].item[4].item[0].text = "評估次數"
* item[12].item[4].item[0].type = #string
* item[12].item[4].item[1].linkId = "raw.ncva.nihss.oneA"
* item[12].item[4].item[1].text = "1a 意識程度"
* item[12].item[4].item[1].type = #string
* item[12].item[4].item[2].linkId = "raw.ncva.nihss.oneB"
* item[12].item[4].item[2].text = "1b 意識提問"
* item[12].item[4].item[2].type = #string
* item[12].item[4].item[3].linkId = "raw.ncva.nihss.oneC"
* item[12].item[4].item[3].text = "1c 意識指令"
* item[12].item[4].item[3].type = #string
* item[12].item[4].item[4].linkId = "raw.ncva.nihss.two"
* item[12].item[4].item[4].text = "2 眼球運動"
* item[12].item[4].item[4].type = #string
* item[12].item[4].item[5].linkId = "raw.ncva.nihss.three"
* item[12].item[4].item[5].text = "3 視野"
* item[12].item[4].item[5].type = #string
* item[12].item[4].item[6].linkId = "raw.ncva.nihss.four"
* item[12].item[4].item[6].text = "4 顏面麻痺"
* item[12].item[4].item[6].type = #string
* item[12].item[4].item[7].linkId = "raw.ncva.nihss.fiveAl"
* item[12].item[4].item[7].text = "5a 左上肢運動"
* item[12].item[4].item[7].type = #string
* item[12].item[4].item[8].linkId = "raw.ncva.nihss.fiveBr"
* item[12].item[4].item[8].text = "5b 右上肢運動"
* item[12].item[4].item[8].type = #string
* item[12].item[4].item[9].linkId = "raw.ncva.nihss.sixAl"
* item[12].item[4].item[9].text = "6a 左下肢運動"
* item[12].item[4].item[9].type = #string
* item[12].item[4].item[10].linkId = "raw.ncva.nihss.sixBr"
* item[12].item[4].item[10].text = "6b 右下肢運動"
* item[12].item[4].item[10].type = #string
* item[12].item[4].item[11].linkId = "raw.ncva.nihss.seven"
* item[12].item[4].item[11].text = "7 肢體運動失調"
* item[12].item[4].item[11].type = #string
* item[12].item[4].item[12].linkId = "raw.ncva.nihss.eight"
* item[12].item[4].item[12].text = "8 感覺"
* item[12].item[4].item[12].type = #string
* item[12].item[4].item[13].linkId = "raw.ncva.nihss.nine"
* item[12].item[4].item[13].text = "9 語言"
* item[12].item[4].item[13].type = #string
* item[12].item[4].item[14].linkId = "raw.ncva.nihss.ten"
* item[12].item[4].item[14].text = "10 構音障礙"
* item[12].item[4].item[14].type = #string
* item[12].item[4].item[15].linkId = "raw.ncva.nihss.eleven"
* item[12].item[4].item[15].text = "11 忽略"
* item[12].item[4].item[15].type = #string
* item[12].item[4].item[16].linkId = "raw.ncva.nihss.total"
* item[12].item[4].item[16].text = "NIHSS 總分"
* item[12].item[4].item[16].type = #string
* item[12].item[4].item[17].linkId = "raw.ncva.nihss.inpdate"
* item[12].item[4].item[17].text = "評估日期"
* item[12].item[4].item[17].type = #string
* item[12].item[4].item[18].linkId = "raw.ncva.nihss.inptime"
* item[12].item[4].item[18].text = "評估時間"
* item[12].item[4].item[18].type = #string
* item[12].item[4].item[19].linkId = "raw.ncva.nihss.arrdate"
* item[12].item[4].item[19].text = "入院日期"
* item[12].item[4].item[19].type = #string
* item[12].item[4].item[20].linkId = "raw.ncva.nihss.hdisdt"
* item[12].item[4].item[20].text = "離院日期"
* item[12].item[4].item[20].type = #string
* item[12].item[5].linkId = "raw.ncva.mrs"
* item[12].item[5].text = "mRS 評估"
* item[12].item[5].type = #group
* item[12].item[5].repeats = true
* item[12].item[5].item[0].linkId = "raw.ncva.mrs.freqno"
* item[12].item[5].item[0].text = "評估次數"
* item[12].item[5].item[0].type = #string
* item[12].item[5].item[1].linkId = "raw.ncva.mrs.mrsrate"
* item[12].item[5].item[1].text = "mRS 分數"
* item[12].item[5].item[1].type = #string
* item[12].item[5].item[2].linkId = "raw.ncva.mrs.inpdate"
* item[12].item[5].item[2].text = "評估日期"
* item[12].item[5].item[2].type = #string
* item[12].item[5].item[3].linkId = "raw.ncva.mrs.unnamedCol06"
* item[12].item[5].item[3].text = "未命名欄位（第 6 欄）"
* item[12].item[5].item[3].type = #string
* item[12].item[5].item[4].linkId = "raw.ncva.mrs.unnamedCol07"
* item[12].item[5].item[4].text = "未命名欄位（第 7 欄）"
* item[12].item[5].item[4].type = #string
* item[12].item[6].linkId = "raw.ncva.ich"
* item[12].item[6].text = "ICH 分數"
* item[12].item[6].type = #group
* item[12].item[6].item[0].linkId = "raw.ncva.ich.ichScore"
* item[12].item[6].item[0].text = "ICH 分數"
* item[12].item[6].item[0].type = #string
* item[12].item[6].item[1].linkId = "raw.ncva.ich.formdt"
* item[12].item[6].item[1].text = "評估日期"
* item[12].item[6].item[1].type = #string
* item[12].item[7].linkId = "raw.ncva.hhs"
* item[12].item[7].text = "Hunt and Hess 分級"
* item[12].item[7].type = #group
* item[12].item[7].item[0].linkId = "raw.ncva.hhs.hlsGrade"
* item[12].item[7].item[0].text = "Hunt and Hess 分級"
* item[12].item[7].item[0].type = #string
* item[12].item[7].item[1].linkId = "raw.ncva.hhs.formdt"
* item[12].item[7].item[1].text = "評估日期"
* item[12].item[7].item[1].type = #string
* item[12].item[8].linkId = "raw.ncva.heartDisease"
* item[12].item[8].text = "心臟疾病"
* item[12].item[8].type = #group
* item[12].item[8].item[0].linkId = "raw.ncva.heartDisease.thd01"
* item[12].item[8].item[0].text = "心房顫動"
* item[12].item[8].item[0].type = #string
* item[12].item[8].item[1].linkId = "raw.ncva.heartDisease.thd02"
* item[12].item[8].item[1].text = "其他缺血性心臟病"
* item[12].item[8].item[1].type = #string
* item[12].item[8].item[2].linkId = "raw.ncva.heartDisease.thd03"
* item[12].item[8].item[2].text = "瓣膜置換"
* item[12].item[8].item[2].type = #string
* item[12].item[8].item[3].linkId = "raw.ncva.heartDisease.thd04"
* item[12].item[8].item[3].text = "心內膜炎"
* item[12].item[8].item[3].type = #string
* item[12].item[8].item[4].linkId = "raw.ncva.heartDisease.thd05"
* item[12].item[8].item[4].text = "心臟黏液瘤"
* item[12].item[8].item[4].type = #string
* item[12].item[8].item[5].linkId = "raw.ncva.heartDisease.thd06"
* item[12].item[8].item[5].text = "心衰竭"
* item[12].item[8].item[5].type = #string
* item[12].item[8].item[6].linkId = "raw.ncva.heartDisease.thd07"
* item[12].item[8].item[6].text = "4 週內急性心肌梗塞"
* item[12].item[8].item[6].type = #string
* item[12].item[8].item[7].linkId = "raw.ncva.heartDisease.thd08"
* item[12].item[8].item[7].text = "風濕性心臟病"
* item[12].item[8].item[7].type = #string
* item[12].item[8].item[8].linkId = "raw.ncva.heartDisease.thd09"
* item[12].item[8].item[8].text = "開放性卵圓孔"
* item[12].item[8].item[8].type = #string
* item[12].item[9].linkId = "raw.ncva.treatment"
* item[12].item[9].text = "住院治療"
* item[12].item[9].type = #group
* item[12].item[9].item[0].linkId = "raw.ncva.treatment.tre01"
* item[12].item[9].item[0].text = "Aggrenox"
* item[12].item[9].item[0].type = #string
* item[12].item[9].item[1].linkId = "raw.ncva.treatment.tre02"
* item[12].item[9].item[1].text = "Aspirin"
* item[12].item[9].item[1].type = #string
* item[12].item[9].item[2].linkId = "raw.ncva.treatment.tre03"
* item[12].item[9].item[2].text = "Ticlopidine"
* item[12].item[9].item[2].type = #string
* item[12].item[9].item[3].linkId = "raw.ncva.treatment.tre05"
* item[12].item[9].item[3].text = "Warfarin"
* item[12].item[9].item[3].type = #string
* item[12].item[9].item[4].linkId = "raw.ncva.treatment.tre06"
* item[12].item[9].item[4].text = "動脈內取栓"
* item[12].item[9].item[4].type = #string
* item[12].item[9].item[5].linkId = "raw.ncva.treatment.tre07"
* item[12].item[9].item[5].text = "導尿管"
* item[12].item[9].item[5].type = #string
* item[12].item[9].item[6].linkId = "raw.ncva.treatment.tre09"
* item[12].item[9].item[6].text = "簽署 DNR"
* item[12].item[9].item[6].type = #string
* item[12].item[9].item[7].linkId = "raw.ncva.treatment.tre10"
* item[12].item[9].item[7].text = "復健"
* item[12].item[9].item[7].type = #string
* item[12].item[9].item[8].linkId = "raw.ncva.treatment.tre13"
* item[12].item[9].item[8].text = "Clopidogrel"
* item[12].item[9].item[8].type = #string
* item[12].item[9].item[9].linkId = "raw.ncva.treatment.tre14"
* item[12].item[9].item[9].text = "Pletaal"
* item[12].item[9].item[9].type = #string
* item[12].item[9].item[10].linkId = "raw.ncva.treatment.tre15"
* item[12].item[9].item[10].text = "低分子量肝素"
* item[12].item[9].item[10].type = #string
* item[12].item[9].item[11].linkId = "raw.ncva.treatment.tre16"
* item[12].item[9].item[11].text = "靜脈 t-PA"
* item[12].item[9].item[11].type = #string
* item[12].item[9].item[12].linkId = "raw.ncva.treatment.tre17"
* item[12].item[9].item[12].text = "呼吸器"
* item[12].item[9].item[12].type = #string
* item[12].item[9].item[13].linkId = "raw.ncva.treatment.tre18"
* item[12].item[9].item[13].text = "鼻胃管"
* item[12].item[9].item[13].type = #string
* item[12].item[9].item[14].linkId = "raw.ncva.treatment.tre19"
* item[12].item[9].item[14].text = "吞嚥篩檢"
* item[12].item[9].item[14].type = #string
* item[12].item[9].item[15].linkId = "raw.ncva.treatment.tre20"
* item[12].item[9].item[15].text = "入住加護病房"
* item[12].item[9].item[15].type = #string
* item[12].item[9].item[16].linkId = "raw.ncva.treatment.tre21"
* item[12].item[9].item[16].text = "戒菸衛教"
* item[12].item[9].item[16].type = #string
* item[12].item[9].item[17].linkId = "raw.ncva.treatment.tre22"
* item[12].item[9].item[17].text = "中風衛教"
* item[12].item[9].item[17].type = #string
* item[12].item[9].item[18].linkId = "raw.ncva.treatment.tre23"
* item[12].item[9].item[18].text = "手術治療"
* item[12].item[9].item[18].type = #string
* item[12].item[9].item[19].linkId = "raw.ncva.treatment.tre27"
* item[12].item[9].item[19].text = "Apixaban"
* item[12].item[9].item[19].type = #string
* item[12].item[9].item[20].linkId = "raw.ncva.treatment.tre28"
* item[12].item[9].item[20].text = "Dabigatran"
* item[12].item[9].item[20].type = #string
* item[12].item[9].item[21].linkId = "raw.ncva.treatment.tre29"
* item[12].item[9].item[21].text = "Edoxaban"
* item[12].item[9].item[21].type = #string
* item[12].item[9].item[22].linkId = "raw.ncva.treatment.tre30"
* item[12].item[9].item[22].text = "Rivaroxaban"
* item[12].item[9].item[22].type = #string
* item[12].item[9].item[23].linkId = "raw.ncva.treatment.tre31"
* item[12].item[9].item[23].text = "Ticagrelor"
* item[12].item[9].item[23].type = #string
* item[12].item[10].linkId = "raw.ncva.dischargeDrug"
* item[12].item[10].text = "出院帶藥"
* item[12].item[10].type = #group
* item[12].item[10].item[0].linkId = "raw.ncva.dischargeDrug.drg01"
* item[12].item[10].item[0].text = "Aspirin"
* item[12].item[10].item[0].type = #string
* item[12].item[10].item[1].linkId = "raw.ncva.dischargeDrug.drg02"
* item[12].item[10].item[1].text = "Aggrenox"
* item[12].item[10].item[1].type = #string
* item[12].item[10].item[2].linkId = "raw.ncva.dischargeDrug.drg03"
* item[12].item[10].item[2].text = "Ticlopidine"
* item[12].item[10].item[2].type = #string
* item[12].item[10].item[3].linkId = "raw.ncva.dischargeDrug.drg04"
* item[12].item[10].item[3].text = "Clopidogrel"
* item[12].item[10].item[3].type = #string
* item[12].item[10].item[4].linkId = "raw.ncva.dischargeDrug.drg05"
* item[12].item[10].item[4].text = "Pletaal"
* item[12].item[10].item[4].type = #string
* item[12].item[10].item[5].linkId = "raw.ncva.dischargeDrug.drg06"
* item[12].item[10].item[5].text = "降血壓藥"
* item[12].item[10].item[5].type = #string
* item[12].item[10].item[6].linkId = "raw.ncva.dischargeDrug.drg07"
* item[12].item[10].item[6].text = "Warfarin"
* item[12].item[10].item[6].type = #string
* item[12].item[10].item[7].linkId = "raw.ncva.dischargeDrug.drg08"
* item[12].item[10].item[7].text = "糖尿病藥"
* item[12].item[10].item[7].type = #string
* item[12].item[10].item[8].linkId = "raw.ncva.dischargeDrug.sub01"
* item[12].item[10].item[8].text = "口服降血糖藥"
* item[12].item[10].item[8].type = #string
* item[12].item[10].item[9].linkId = "raw.ncva.dischargeDrug.sub02"
* item[12].item[10].item[9].text = "胰島素"
* item[12].item[10].item[9].type = #string
* item[12].item[10].item[10].linkId = "raw.ncva.dischargeDrug.sub03"
* item[12].item[10].item[10].text = "statin 類降血脂藥"
* item[12].item[10].item[10].type = #string
* item[12].item[10].item[11].linkId = "raw.ncva.dischargeDrug.sub04"
* item[12].item[10].item[11].text = "非 statin 類降血脂藥"
* item[12].item[10].item[11].type = #string
* item[12].item[10].item[12].linkId = "raw.ncva.dischargeDrug.drg12"
* item[12].item[10].item[12].text = "Apixaban"
* item[12].item[10].item[12].type = #string
* item[12].item[10].item[13].linkId = "raw.ncva.dischargeDrug.drg13"
* item[12].item[10].item[13].text = "Dabigatran"
* item[12].item[10].item[13].type = #string
* item[12].item[10].item[14].linkId = "raw.ncva.dischargeDrug.drg14"
* item[12].item[10].item[14].text = "Edoxaban"
* item[12].item[10].item[14].type = #string
* item[12].item[10].item[15].linkId = "raw.ncva.dischargeDrug.drg15"
* item[12].item[10].item[15].text = "Rivaroxaban"
* item[12].item[10].item[15].type = #string
* item[12].item[10].item[16].linkId = "raw.ncva.dischargeDrug.drg16"
* item[12].item[10].item[16].text = "Ticagrelor"
* item[12].item[10].item[16].type = #string
* item[12].item[11].linkId = "raw.ncva.deterioration"
* item[12].item[11].text = "惡化原因"
* item[12].item[11].type = #group
* item[12].item[11].item[0].linkId = "raw.ncva.deterioration.det01"
* item[12].item[11].item[0].text = "中風惡化"
* item[12].item[11].item[0].type = #string
* item[12].item[11].item[1].linkId = "raw.ncva.deterioration.det02"
* item[12].item[11].item[1].text = "腦疝脫"
* item[12].item[11].item[1].type = #string
* item[12].item[11].item[2].linkId = "raw.ncva.deterioration.det03"
* item[12].item[11].item[2].text = "36 小時內出血性梗塞"
* item[12].item[11].item[2].type = #string
* item[12].item[11].item[3].linkId = "raw.ncva.deterioration.det04"
* item[12].item[11].item[3].text = "血腫擴大"
* item[12].item[11].item[3].type = #string
* item[12].item[11].item[4].linkId = "raw.ncva.deterioration.det05"
* item[12].item[11].item[4].text = "血管痙攣"
* item[12].item[11].item[4].type = #string
* item[12].item[11].item[5].linkId = "raw.ncva.deterioration.det06"
* item[12].item[11].item[5].text = "再出血"
* item[12].item[11].item[5].type = #string
* item[12].item[11].item[6].linkId = "raw.ncva.deterioration.det07"
* item[12].item[11].item[6].text = "內科問題"
* item[12].item[11].item[6].type = #string
* item[12].item[12].linkId = "raw.ncva.riskFactor"
* item[12].item[12].text = "危險因子"
* item[12].item[12].type = #group
* item[12].item[12].item[0].linkId = "raw.ncva.riskFactor.ht"
* item[12].item[12].item[0].text = "高血壓"
* item[12].item[12].item[0].type = #string
* item[12].item[12].item[1].linkId = "raw.ncva.riskFactor.htcurrent"
* item[12].item[12].item[1].text = "本次新診斷高血壓"
* item[12].item[12].item[1].type = #string
* item[12].item[12].item[2].linkId = "raw.ncva.riskFactor.previoustia"
* item[12].item[12].item[2].text = "既往短暫性腦缺血"
* item[12].item[12].item[2].type = #string
* item[12].item[12].item[3].linkId = "raw.ncva.riskFactor.cancer"
* item[12].item[12].item[3].text = "癌症"
* item[12].item[12].item[3].type = #string
* item[12].item[12].item[4].linkId = "raw.ncva.riskFactor.hypercholesterolemia"
* item[12].item[12].item[4].text = "高膽固醇"
* item[12].item[12].item[4].type = #string
* item[12].item[12].item[5].linkId = "raw.ncva.riskFactor.smoking"
* item[12].item[12].item[5].text = "吸菸"
* item[12].item[12].item[5].type = #string
* item[12].item[12].item[6].linkId = "raw.ncva.riskFactor.smokingtiming"
* item[12].item[12].item[6].text = "吸菸狀態"
* item[12].item[12].item[6].type = #string
* item[12].item[12].item[7].linkId = "raw.ncva.riskFactor.smokingquantity"
* item[12].item[12].item[7].text = "每日吸菸量"
* item[12].item[12].item[7].type = #string
* item[12].item[12].item[8].linkId = "raw.ncva.riskFactor.smokingyears"
* item[12].item[12].item[8].text = "吸菸年數"
* item[12].item[12].item[8].type = #string
* item[12].item[12].item[9].linkId = "raw.ncva.riskFactor.heartdisease"
* item[12].item[12].item[9].text = "心臟病"
* item[12].item[12].item[9].type = #string
* item[12].item[12].item[10].linkId = "raw.ncva.riskFactor.pad"
* item[12].item[12].item[10].text = "周邊動脈疾病"
* item[12].item[12].item[10].type = #string
* item[12].item[12].item[11].linkId = "raw.ncva.riskFactor.dm"
* item[12].item[12].item[11].text = "糖尿病"
* item[12].item[12].item[11].type = #string
* item[12].item[12].item[12].linkId = "raw.ncva.riskFactor.dmcurrent"
* item[12].item[12].item[12].text = "本次新診斷糖尿病"
* item[12].item[12].item[12].type = #string
* item[12].item[12].item[13].linkId = "raw.ncva.riskFactor.alcohol"
* item[12].item[12].item[13].text = "飲酒"
* item[12].item[12].item[13].type = #string
* item[12].item[12].item[14].linkId = "raw.ncva.riskFactor.hypertriglyceridemia"
* item[12].item[12].item[14].text = "高三酸甘油脂"
* item[12].item[12].item[14].type = #string
* item[12].item[12].item[15].linkId = "raw.ncva.riskFactor.polycythemia"
* item[12].item[12].item[15].text = "紅血球增多症"
* item[12].item[12].item[15].type = #string
* item[12].item[12].item[16].linkId = "raw.ncva.riskFactor.uremia"
* item[12].item[12].item[16].text = "尿毒症"
* item[12].item[12].item[16].type = #string
* item[12].item[12].item[17].linkId = "raw.ncva.riskFactor.previousci"
* item[12].item[12].item[17].text = "既往腦梗塞"
* item[12].item[12].item[17].type = #string
* item[12].item[12].item[18].linkId = "raw.ncva.riskFactor.previousch"
* item[12].item[12].item[18].text = "既往腦出血"
* item[12].item[12].item[18].type = #string
* item[12].item[13].linkId = "raw.ncva.familyHistory"
* item[12].item[13].text = "家族病史"
* item[12].item[13].type = #group
* item[12].item[13].item[0].linkId = "raw.ncva.familyHistory.isHbr"
* item[12].item[13].item[0].text = "高血壓家族史"
* item[12].item[13].item[0].type = #string
* item[12].item[13].item[1].linkId = "raw.ncva.familyHistory.isDm"
* item[12].item[13].item[1].text = "糖尿病家族史"
* item[12].item[13].item[1].type = #string
* item[12].item[13].item[2].linkId = "raw.ncva.familyHistory.isIhd"
* item[12].item[13].item[2].text = "缺血性心臟病家族史"
* item[12].item[13].item[2].type = #string
* item[12].item[13].item[3].linkId = "raw.ncva.familyHistory.isTia"
* item[12].item[13].item[3].text = "中風或短暫性腦缺血家族史"
* item[12].item[13].item[3].type = #string
* item[12].item[14].linkId = "raw.ncva.examResult"
* item[12].item[14].text = "檢驗結果"
* item[12].item[14].type = #group
* item[12].item[14].item[0].linkId = "raw.ncva.examResult.ecgOption"
* item[12].item[14].item[0].text = "心電圖心房顫動"
* item[12].item[14].item[0].type = #string
* item[12].item[14].item[1].linkId = "raw.ncva.examResult.hb"
* item[12].item[14].item[1].text = "血紅素"
* item[12].item[14].item[1].type = #string
* item[12].item[14].item[2].linkId = "raw.ncva.examResult.hct"
* item[12].item[14].item[2].text = "血比容"
* item[12].item[14].item[2].type = #string
* item[12].item[14].item[3].linkId = "raw.ncva.examResult.platelet"
* item[12].item[14].item[3].text = "血小板"
* item[12].item[14].item[3].type = #string
* item[12].item[14].item[4].linkId = "raw.ncva.examResult.wbc"
* item[12].item[14].item[4].text = "白血球"
* item[12].item[14].item[4].type = #string
* item[12].item[14].item[5].linkId = "raw.ncva.examResult.ptt"
* item[12].item[14].item[5].text = "部分凝血活酶時間"
* item[12].item[14].item[5].type = #string
* item[12].item[14].item[6].linkId = "raw.ncva.examResult.pttControl"
* item[12].item[14].item[6].text = "PTT 對照值"
* item[12].item[14].item[6].type = #string
* item[12].item[14].item[7].linkId = "raw.ncva.examResult.ptInr"
* item[12].item[14].item[7].text = "凝血酶原時間 INR"
* item[12].item[14].item[7].type = #string
* item[12].item[14].item[8].linkId = "raw.ncva.examResult.glucoseEr"
* item[12].item[14].item[8].text = "急診血糖"
* item[12].item[14].item[8].type = #string
* item[12].item[14].item[9].linkId = "raw.ncva.examResult.bun"
* item[12].item[14].item[9].text = "血中尿素氮"
* item[12].item[14].item[9].type = #string
* item[12].item[14].item[10].linkId = "raw.ncva.examResult.creatinine"
* item[12].item[14].item[10].text = "肌酸酐"
* item[12].item[14].item[10].type = #string
* item[12].item[14].item[11].linkId = "raw.ncva.examResult.albumin"
* item[12].item[14].item[11].text = "白蛋白"
* item[12].item[14].item[11].type = #string
* item[12].item[14].item[12].linkId = "raw.ncva.examResult.crp"
* item[12].item[14].item[12].text = "C 反應蛋白"
* item[12].item[14].item[12].type = #string
* item[12].item[14].item[13].linkId = "raw.ncva.examResult.hba1c"
* item[12].item[14].item[13].text = "糖化血色素"
* item[12].item[14].item[13].type = #string
* item[12].item[14].item[14].linkId = "raw.ncva.examResult.gluAc"
* item[12].item[14].item[14].text = "空腹血糖"
* item[12].item[14].item[14].type = #string
* item[12].item[14].item[15].linkId = "raw.ncva.examResult.ua"
* item[12].item[14].item[15].text = "UA"
* item[12].item[14].item[15].type = #string
* item[12].item[14].item[16].linkId = "raw.ncva.examResult.tCho"
* item[12].item[14].item[16].text = "總膽固醇"
* item[12].item[14].item[16].type = #string
* item[12].item[14].item[17].linkId = "raw.ncva.examResult.tg"
* item[12].item[14].item[17].text = "三酸甘油脂"
* item[12].item[14].item[17].type = #string
* item[12].item[14].item[18].linkId = "raw.ncva.examResult.hdl"
* item[12].item[14].item[18].text = "高密度脂蛋白膽固醇"
* item[12].item[14].item[18].type = #string
* item[12].item[14].item[19].linkId = "raw.ncva.examResult.ldl"
* item[12].item[14].item[19].text = "低密度脂蛋白膽固醇"
* item[12].item[14].item[19].type = #string
* item[12].item[14].item[20].linkId = "raw.ncva.examResult.got"
* item[12].item[14].item[20].text = "AST／GOT"
* item[12].item[14].item[20].type = #string
* item[12].item[14].item[21].linkId = "raw.ncva.examResult.gpt"
* item[12].item[14].item[21].text = "ALT／GPT"
* item[12].item[14].item[21].type = #string
* item[12].item[15].linkId = "raw.ncva.timesheet"
* item[12].item[15].text = "腦中風個管時間表"
* item[12].item[15].type = #group
* item[12].item[15].item[0].linkId = "raw.ncva.timesheet.ctmridate"
* item[12].item[15].item[0].text = "第一次 CT/MRI 日期"
* item[12].item[15].item[0].type = #string
* item[12].item[15].item[1].linkId = "raw.ncva.timesheet.ctmritime"
* item[12].item[15].item[1].text = "第一次 CT/MRI 時間"
* item[12].item[15].item[1].type = #string
* item[12].item[15].item[2].linkId = "raw.ncva.timesheet.isctmrifromoutside"
* item[12].item[15].item[2].text = "CT/MRI 是否為外片"
* item[12].item[15].item[2].type = #string
* item[12].item[15].item[3].linkId = "raw.ncva.timesheet.ivtpadate"
* item[12].item[15].item[3].text = "執行 IVtPA 日期"
* item[12].item[15].item[3].type = #string
* item[12].item[15].item[4].linkId = "raw.ncva.timesheet.ivtpatime"
* item[12].item[15].item[4].text = "執行 IVtPA 時間"
* item[12].item[15].item[4].type = #string
* item[12].item[15].item[5].linkId = "raw.ncva.timesheet.ivtpareason"
* item[12].item[15].item[5].text = "未執行 IVtPA 主要原因"
* item[12].item[15].item[5].type = #string
* item[12].item[15].item[6].linkId = "raw.ncva.timesheet.ivtpasub01"
* item[12].item[15].item[6].text = "未執行 IVtPA 次要原因 1"
* item[12].item[15].item[6].type = #string
* item[12].item[15].item[7].linkId = "raw.ncva.timesheet.ivtpasub02"
* item[12].item[15].item[7].text = "未執行 IVtPA 次要原因 2"
* item[12].item[15].item[7].type = #string
* item[12].item[15].item[8].linkId = "raw.ncva.timesheet.ivtpasub03"
* item[12].item[15].item[8].text = "未執行 IVtPA 次要原因 3"
* item[12].item[15].item[8].type = #string
* item[12].item[15].item[9].linkId = "raw.ncva.timesheet.ivtpasub04"
* item[12].item[15].item[9].text = "未執行 IVtPA 次要原因 4"
* item[12].item[15].item[9].type = #string
* item[12].item[15].item[10].linkId = "raw.ncva.timesheet.ivtpasub05"
* item[12].item[15].item[10].text = "未執行 IVtPA 次要原因 5"
* item[12].item[15].item[10].type = #string
* item[12].item[15].item[11].linkId = "raw.ncva.timesheet.ivtpasub06"
* item[12].item[15].item[11].text = "未執行 IVtPA 次要原因 6"
* item[12].item[15].item[11].type = #string
* item[12].item[15].item[12].linkId = "raw.ncva.timesheet.ivtpasub07"
* item[12].item[15].item[12].text = "未執行 IVtPA 次要原因 7"
* item[12].item[15].item[12].type = #string
* item[12].item[15].item[13].linkId = "raw.ncva.timesheet.ivtpasub08"
* item[12].item[15].item[13].text = "未執行 IVtPA 次要原因 8"
* item[12].item[15].item[13].type = #string
* item[12].item[15].item[14].linkId = "raw.ncva.timesheet.ivtpasub09"
* item[12].item[15].item[14].text = "未執行 IVtPA 次要原因 9"
* item[12].item[15].item[14].type = #string
* item[12].item[15].item[15].linkId = "raw.ncva.timesheet.ivtpasub10"
* item[12].item[15].item[15].text = "未執行 IVtPA 次要原因 10"
* item[12].item[15].item[15].type = #string
* item[12].item[15].item[16].linkId = "raw.ncva.timesheet.ivtpadoze"
* item[12].item[15].item[16].text = "IV-tPA 劑量"
* item[12].item[15].item[16].type = #string
* item[12].item[15].item[17].linkId = "raw.ncva.timesheet.hadmdt"
* item[12].item[15].item[17].text = "轉住院日期"
* item[12].item[15].item[17].type = #string
* item[12].item[15].item[18].linkId = "raw.ncva.timesheet.ctadate"
* item[12].item[15].item[18].text = "CTA 日期"
* item[12].item[15].item[18].type = #string
* item[12].item[15].item[19].linkId = "raw.ncva.timesheet.ctatime"
* item[12].item[15].item[19].text = "CTA 時間"
* item[12].item[15].item[19].type = #string
* item[12].item[15].item[20].linkId = "raw.ncva.timesheet.puncturedt"
* item[12].item[15].item[20].text = "動脈穿刺日期"
* item[12].item[15].item[20].type = #string
* item[12].item[15].item[21].linkId = "raw.ncva.timesheet.puncturetm"
* item[12].item[15].item[21].text = "動脈穿刺時間"
* item[12].item[15].item[21].type = #string
* item[12].item[15].item[22].linkId = "raw.ncva.timesheet.perfusiondta"
* item[12].item[15].item[22].text = "再灌流日期"
* item[12].item[15].item[22].type = #string
* item[12].item[15].item[23].linkId = "raw.ncva.timesheet.perfusiontma"
* item[12].item[15].item[23].text = "再灌流時間"
* item[12].item[15].item[23].type = #string
* item[13].linkId = "raw.evt"
* item[13].text = "EVT 登錄原始值"
* item[13].type = #group
* item[13].item[0].linkId = "raw.evt.caseId"
* item[13].item[0].text = "EVT 登錄個案識別碼"
* item[13].item[0].type = #string
* item[13].item[1].linkId = "raw.evt.demographics"
* item[13].item[1].text = "基本資料"
* item[13].item[1].type = #group
* item[13].item[1].item[0].linkId = "raw.evt.demographics.hospitalCode"
* item[13].item[1].item[0].text = "登錄醫院"
* item[13].item[1].item[0].type = #string
* item[13].item[1].item[1].linkId = "raw.evt.demographics.birthday"
* item[13].item[1].item[1].text = "出生年月"
* item[13].item[1].item[1].type = #string
* item[13].item[1].item[2].linkId = "raw.evt.demographics.sex"
* item[13].item[1].item[2].text = "病患性別"
* item[13].item[1].item[2].type = #string
* item[13].item[1].item[3].linkId = "raw.evt.demographics.height"
* item[13].item[1].item[3].text = "身高"
* item[13].item[1].item[3].type = #string
* item[13].item[1].item[4].linkId = "raw.evt.demographics.weight"
* item[13].item[1].item[4].text = "體重"
* item[13].item[1].item[4].type = #string
* item[13].item[1].item[5].linkId = "raw.evt.demographics.hospitalizationCode"
* item[13].item[1].item[5].text = "就醫／住院來源類別"
* item[13].item[1].item[5].type = #string
* item[13].item[1].item[6].linkId = "raw.evt.demographics.arrivalCode"
* item[13].item[1].item[6].text = "到院方式"
* item[13].item[1].item[6].type = #string
* item[13].item[1].item[7].linkId = "raw.evt.demographics.dateHospitalization"
* item[13].item[1].item[7].text = "住院日期"
* item[13].item[1].item[7].type = #string
* item[13].item[1].item[8].linkId = "raw.evt.demographics.dateHospitalizationNo"
* item[13].item[1].item[8].text = "未住院註記"
* item[13].item[1].item[8].type = #string
* item[13].item[1].item[9].linkId = "raw.evt.demographics.dateLeave"
* item[13].item[1].item[9].text = "離院日期"
* item[13].item[1].item[9].type = #string
* item[13].item[1].item[10].linkId = "raw.evt.demographics.consent"
* item[13].item[1].item[10].text = "研究同意書簽署狀態"
* item[13].item[1].item[10].type = #string
* item[13].item[1].item[11].linkId = "raw.evt.demographics.consentDate"
* item[13].item[1].item[11].text = "研究同意書簽署日期"
* item[13].item[1].item[11].type = #string
* item[13].item[2].linkId = "raw.evt.administration"
* item[13].item[2].text = "資料管理"
* item[13].item[2].type = #group
* item[13].item[2].item[0].linkId = "raw.evt.administration.registrar"
* item[13].item[2].item[0].text = "登錄經手人員"
* item[13].item[2].item[0].type = #string
* item[13].item[2].item[1].linkId = "raw.evt.administration.edit"
* item[13].item[2].item[1].text = "主表登錄狀態"
* item[13].item[2].item[1].type = #string
* item[13].item[2].item[2].linkId = "raw.evt.administration.traceEdit"
* item[13].item[2].item[2].text = "追蹤表登錄狀態"
* item[13].item[2].item[2].type = #string
* item[13].item[2].item[3].linkId = "raw.evt.administration.keyinDate"
* item[13].item[2].item[3].text = "資料登錄日期時間"
* item[13].item[2].item[3].type = #string
* item[13].item[3].linkId = "raw.evt.timeline"
* item[13].item[3].text = "發病與到院時間"
* item[13].item[3].type = #group
* item[13].item[3].item[0].linkId = "raw.evt.timeline.happenDate"
* item[13].item[3].item[0].text = "中風發病日期"
* item[13].item[3].item[0].type = #string
* item[13].item[3].item[1].linkId = "raw.evt.timeline.happenTime"
* item[13].item[3].item[1].text = "中風發病時間"
* item[13].item[3].item[1].type = #string
* item[13].item[3].item[2].linkId = "raw.evt.timeline.happenNotsure"
* item[13].item[3].item[2].text = "發病時間不確定註記"
* item[13].item[3].item[2].type = #string
* item[13].item[3].item[3].linkId = "raw.evt.timeline.finalNormalDate"
* item[13].item[3].item[3].text = "最後正常日期"
* item[13].item[3].item[3].type = #string
* item[13].item[3].item[4].linkId = "raw.evt.timeline.finalNormalTime"
* item[13].item[3].item[4].text = "最後正常時間"
* item[13].item[3].item[4].type = #string
* item[13].item[3].item[5].linkId = "raw.evt.timeline.wakeUpStroke"
* item[13].item[3].item[5].text = "醒後中風註記"
* item[13].item[3].item[5].type = #string
* item[13].item[3].item[6].linkId = "raw.evt.timeline.erDateOther"
* item[13].item[3].item[6].text = "到他院急診日期"
* item[13].item[3].item[6].type = #string
* item[13].item[3].item[7].linkId = "raw.evt.timeline.erTimeOther"
* item[13].item[3].item[7].text = "到他院急診時間"
* item[13].item[3].item[7].type = #string
* item[13].item[3].item[8].linkId = "raw.evt.timeline.erDateHere"
* item[13].item[3].item[8].text = "到本院急診日期"
* item[13].item[3].item[8].type = #string
* item[13].item[3].item[9].linkId = "raw.evt.timeline.erTimeHere"
* item[13].item[3].item[9].text = "到本院急診時間"
* item[13].item[3].item[9].type = #string
* item[13].item[4].linkId = "raw.evt.vitalSigns"
* item[13].item[4].text = "GCS 與生命徵象"
* item[13].item[4].type = #group
* item[13].item[4].item[0].linkId = "raw.evt.vitalSigns.gcsE"
* item[13].item[4].item[0].text = "GCS 睜眼反應"
* item[13].item[4].item[0].type = #string
* item[13].item[4].item[1].linkId = "raw.evt.vitalSigns.gcsV"
* item[13].item[4].item[1].text = "GCS 語言反應"
* item[13].item[4].item[1].type = #string
* item[13].item[4].item[2].linkId = "raw.evt.vitalSigns.gcsM"
* item[13].item[4].item[2].text = "GCS 動作反應"
* item[13].item[4].item[2].type = #string
* item[13].item[4].item[3].linkId = "raw.evt.vitalSigns.sbp"
* item[13].item[4].item[3].text = "收縮壓"
* item[13].item[4].item[3].type = #string
* item[13].item[4].item[4].linkId = "raw.evt.vitalSigns.dbp"
* item[13].item[4].item[4].text = "舒張壓"
* item[13].item[4].item[4].type = #string
* item[13].item[4].item[5].linkId = "raw.evt.vitalSigns.bt"
* item[13].item[4].item[5].text = "體溫"
* item[13].item[4].item[5].type = #string
* item[13].item[4].item[6].linkId = "raw.evt.vitalSigns.hr"
* item[13].item[4].item[6].text = "心率"
* item[13].item[4].item[6].type = #string
* item[13].item[4].item[7].linkId = "raw.evt.vitalSigns.rr"
* item[13].item[4].item[7].text = "呼吸頻率"
* item[13].item[4].item[7].type = #string
* item[13].item[5].linkId = "raw.evt.risk"
* item[13].item[5].text = "危險因子"
* item[13].item[5].type = #group
* item[13].item[5].item[0].linkId = "raw.evt.risk.riskHt"
* item[13].item[5].item[0].text = "高血壓病史"
* item[13].item[5].item[0].type = #string
* item[13].item[5].item[1].linkId = "raw.evt.risk.riskHtCurrent"
* item[13].item[5].item[1].text = "本次新診斷高血壓"
* item[13].item[5].item[1].type = #string
* item[13].item[5].item[2].linkId = "raw.evt.risk.riskDm"
* item[13].item[5].item[2].text = "糖尿病病史"
* item[13].item[5].item[2].type = #string
* item[13].item[5].item[3].linkId = "raw.evt.risk.riskDmCurrent"
* item[13].item[5].item[3].text = "本次新診斷糖尿病"
* item[13].item[5].item[3].type = #string
* item[13].item[5].item[4].linkId = "raw.evt.risk.riskCva"
* item[13].item[5].item[4].text = "既往腦中風病史"
* item[13].item[5].item[4].type = #string
* item[13].item[5].item[5].linkId = "raw.evt.risk.riskCvaCi"
* item[13].item[5].item[5].text = "既往腦梗塞病史"
* item[13].item[5].item[5].type = #string
* item[13].item[5].item[6].linkId = "raw.evt.risk.riskCvaCh"
* item[13].item[5].item[6].text = "既往腦出血病史"
* item[13].item[5].item[6].type = #string
* item[13].item[5].item[7].linkId = "raw.evt.risk.riskTia"
* item[13].item[5].item[7].text = "既往短暫性腦缺血病史"
* item[13].item[5].item[7].type = #string
* item[13].item[5].item[8].linkId = "raw.evt.risk.riskHeart"
* item[13].item[5].item[8].text = "心臟病病史"
* item[13].item[5].item[8].type = #string
* item[13].item[5].item[9].linkId = "raw.evt.risk.riskCkd"
* item[13].item[5].item[9].text = "慢性腎臟病病史"
* item[13].item[5].item[9].type = #string
* item[13].item[5].item[10].linkId = "raw.evt.risk.riskCkdDialysis"
* item[13].item[5].item[10].text = "透析註記"
* item[13].item[5].item[10].type = #string
* item[13].item[5].item[11].linkId = "raw.evt.risk.riskPad"
* item[13].item[5].item[11].text = "周邊動脈疾病病史"
* item[13].item[5].item[11].type = #string
* item[13].item[5].item[12].linkId = "raw.evt.risk.riskDyslipid"
* item[13].item[5].item[12].text = "血脂異常病史"
* item[13].item[5].item[12].type = #string
* item[13].item[5].item[13].linkId = "raw.evt.risk.riskLipidHyt"
* item[13].item[5].item[13].text = "高三酸甘油脂病史"
* item[13].item[5].item[13].type = #string
* item[13].item[5].item[14].linkId = "raw.evt.risk.riskLipidHyc"
* item[13].item[5].item[14].text = "高膽固醇病史"
* item[13].item[5].item[14].type = #string
* item[13].item[5].item[15].linkId = "raw.evt.risk.riskSmoking"
* item[13].item[5].item[15].text = "吸菸史"
* item[13].item[5].item[15].type = #string
* item[13].item[5].item[16].linkId = "raw.evt.risk.riskSmokingFreq"
* item[13].item[5].item[16].text = "每日吸菸量"
* item[13].item[5].item[16].type = #string
* item[13].item[5].item[17].linkId = "raw.evt.risk.riskSmokingYear"
* item[13].item[5].item[17].text = "吸菸年數"
* item[13].item[5].item[17].type = #string
* item[13].item[5].item[18].linkId = "raw.evt.risk.riskSmokingCurrent"
* item[13].item[5].item[18].text = "目前／過去吸菸狀態"
* item[13].item[5].item[18].type = #string
* item[13].item[5].item[19].linkId = "raw.evt.risk.riskAlcohol"
* item[13].item[5].item[19].text = "飲酒史"
* item[13].item[5].item[19].type = #string
* item[13].item[5].item[20].linkId = "raw.evt.risk.riskCancer"
* item[13].item[5].item[20].text = "癌症病史"
* item[13].item[5].item[20].type = #string
* item[13].item[5].item[21].linkId = "raw.evt.risk.riskCancerName"
* item[13].item[5].item[21].text = "癌症名稱"
* item[13].item[5].item[21].type = #string
* item[13].item[5].item[22].linkId = "raw.evt.risk.riskOther"
* item[13].item[5].item[22].text = "其他危險因子註記"
* item[13].item[5].item[22].type = #string
* item[13].item[5].item[23].linkId = "raw.evt.risk.riskOtherName"
* item[13].item[5].item[23].text = "其他危險因子名稱"
* item[13].item[5].item[23].type = #string
* item[13].item[6].linkId = "raw.evt.cardiacHistory"
* item[13].item[6].text = "心臟病史"
* item[13].item[6].type = #group
* item[13].item[6].item[0].linkId = "raw.evt.cardiacHistory.heartNone"
* item[13].item[6].item[0].text = "無心臟病註記"
* item[13].item[6].item[0].type = #string
* item[13].item[6].item[1].linkId = "raw.evt.cardiacHistory.heartAf"
* item[13].item[6].item[1].text = "心房顫動病史"
* item[13].item[6].item[1].type = #string
* item[13].item[6].item[2].linkId = "raw.evt.cardiacHistory.heartAfCurrent"
* item[13].item[6].item[2].text = "本次新診斷心房顫動"
* item[13].item[6].item[2].type = #string
* item[13].item[6].item[3].linkId = "raw.evt.cardiacHistory.heartIs"
* item[13].item[6].item[3].text = "缺血性心臟病病史"
* item[13].item[6].item[3].type = #string
* item[13].item[6].item[4].linkId = "raw.evt.cardiacHistory.heartAmi"
* item[13].item[6].item[4].text = "急性心肌梗塞病史"
* item[13].item[6].item[4].type = #string
* item[13].item[6].item[5].linkId = "raw.evt.cardiacHistory.heartValvular"
* item[13].item[6].item[5].text = "心瓣膜疾病"
* item[13].item[6].item[5].type = #string
* item[13].item[6].item[6].linkId = "raw.evt.cardiacHistory.heartValvularName"
* item[13].item[6].item[6].text = "心瓣膜疾病名稱"
* item[13].item[6].item[6].type = #string
* item[13].item[6].item[7].linkId = "raw.evt.cardiacHistory.heartHf"
* item[13].item[6].item[7].text = "心衰竭病史"
* item[13].item[6].item[7].type = #string
* item[13].item[6].item[8].linkId = "raw.evt.cardiacHistory.heartValvularReplace"
* item[13].item[6].item[8].text = "瓣膜置換病史"
* item[13].item[6].item[8].type = #string
* item[13].item[6].item[9].linkId = "raw.evt.cardiacHistory.heartValvularMech"
* item[13].item[6].item[9].text = "機械瓣膜"
* item[13].item[6].item[9].type = #string
* item[13].item[6].item[10].linkId = "raw.evt.cardiacHistory.heartValvularPros"
* item[13].item[6].item[10].text = "prosthetic valve 註記"
* item[13].item[6].item[10].type = #string
* item[13].item[6].item[11].linkId = "raw.evt.cardiacHistory.heartOther"
* item[13].item[6].item[11].text = "其他心臟病註記"
* item[13].item[6].item[11].type = #string
* item[13].item[6].item[12].linkId = "raw.evt.cardiacHistory.heartOtherName"
* item[13].item[6].item[12].text = "其他心臟病名稱"
* item[13].item[6].item[12].type = #string
* item[13].item[7].linkId = "raw.evt.laboratory"
* item[13].item[7].text = "檢驗結果"
* item[13].item[7].type = #group
* item[13].item[7].item[0].linkId = "raw.evt.laboratory.bloodHb"
* item[13].item[7].item[0].text = "血紅素"
* item[13].item[7].item[0].type = #string
* item[13].item[7].item[1].linkId = "raw.evt.laboratory.bloodHct"
* item[13].item[7].item[1].text = "血比容"
* item[13].item[7].item[1].type = #string
* item[13].item[7].item[2].linkId = "raw.evt.laboratory.bloodPlatelet"
* item[13].item[7].item[2].text = "血小板"
* item[13].item[7].item[2].type = #string
* item[13].item[7].item[3].linkId = "raw.evt.laboratory.bloodPtt"
* item[13].item[7].item[3].text = "部分凝血活酶時間"
* item[13].item[7].item[3].type = #string
* item[13].item[7].item[4].linkId = "raw.evt.laboratory.bloodPt"
* item[13].item[7].item[4].text = "凝血酶原時間／比值（定義待確認）"
* item[13].item[7].item[4].type = #string
* item[13].item[7].item[5].linkId = "raw.evt.laboratory.bloodInr"
* item[13].item[7].item[5].text = "凝血國際標準化比值"
* item[13].item[7].item[5].type = #string
* item[13].item[7].item[6].linkId = "raw.evt.laboratory.bloodHba1c"
* item[13].item[7].item[6].text = "糖化血色素"
* item[13].item[7].item[6].type = #string
* item[13].item[7].item[7].linkId = "raw.evt.laboratory.bloodWbc"
* item[13].item[7].item[7].text = "白血球"
* item[13].item[7].item[7].type = #string
* item[13].item[7].item[8].linkId = "raw.evt.laboratory.bloodGluEr"
* item[13].item[7].item[8].text = "急診血糖"
* item[13].item[7].item[8].type = #string
* item[13].item[7].item[9].linkId = "raw.evt.laboratory.bloodBun"
* item[13].item[7].item[9].text = "血中尿素氮"
* item[13].item[7].item[9].type = #string
* item[13].item[7].item[10].linkId = "raw.evt.laboratory.bloodCreatinine"
* item[13].item[7].item[10].text = "肌酸酐"
* item[13].item[7].item[10].type = #string
* item[13].item[7].item[11].linkId = "raw.evt.laboratory.bloodGluAc"
* item[13].item[7].item[11].text = "第一次空腹血糖"
* item[13].item[7].item[11].type = #string
* item[13].item[7].item[12].linkId = "raw.evt.laboratory.bloodTcho"
* item[13].item[7].item[12].text = "總膽固醇"
* item[13].item[7].item[12].type = #string
* item[13].item[7].item[13].linkId = "raw.evt.laboratory.bloodTg"
* item[13].item[7].item[13].text = "三酸甘油脂"
* item[13].item[7].item[13].type = #string
* item[13].item[7].item[14].linkId = "raw.evt.laboratory.bloodHdl"
* item[13].item[7].item[14].text = "高密度脂蛋白膽固醇"
* item[13].item[7].item[14].type = #string
* item[13].item[7].item[15].linkId = "raw.evt.laboratory.bloodLdl"
* item[13].item[7].item[15].text = "低密度脂蛋白膽固醇"
* item[13].item[7].item[15].type = #string
* item[13].item[7].item[16].linkId = "raw.evt.laboratory.bloodAst"
* item[13].item[7].item[16].text = "AST／GOT"
* item[13].item[7].item[16].type = #string
* item[13].item[7].item[17].linkId = "raw.evt.laboratory.bloodAlt"
* item[13].item[7].item[17].text = "ALT／GPT"
* item[13].item[7].item[17].type = #string
* item[13].item[8].linkId = "raw.evt.diagnosis"
* item[13].item[8].text = "TOAST 診斷分類"
* item[13].item[8].type = #group
* item[13].item[8].item[0].linkId = "raw.evt.diagnosis.toast"
* item[13].item[8].item[0].text = "缺血性中風 TOAST 分類"
* item[13].item[8].item[0].type = #string
* item[13].item[8].item[1].linkId = "raw.evt.diagnosis.toastLaExtra"
* item[13].item[8].item[1].text = "TOAST 大動脈粥樣硬化－顱外"
* item[13].item[8].item[1].type = #string
* item[13].item[8].item[2].linkId = "raw.evt.diagnosis.toastLaIntra"
* item[13].item[8].item[2].text = "TOAST 大動脈粥樣硬化－顱內"
* item[13].item[8].item[2].type = #string
* item[13].item[8].item[3].linkId = "raw.evt.diagnosis.toastSpecificEtiology"
* item[13].item[8].item[3].text = "TOAST 特定病因說明"
* item[13].item[8].item[3].type = #string
* item[13].item[9].linkId = "raw.evt.preAdmissionMedication"
* item[13].item[9].text = "住院前用藥"
* item[13].item[9].type = #group
* item[13].item[9].item[0].linkId = "raw.evt.preAdmissionMedication.historyHospNone"
* item[13].item[9].item[0].text = "住院前無用藥註記"
* item[13].item[9].item[0].type = #string
* item[13].item[9].item[1].linkId = "raw.evt.preAdmissionMedication.historyHospAc"
* item[13].item[9].item[1].text = "住院前抗凝血藥"
* item[13].item[9].item[1].type = #string
* item[13].item[9].item[2].linkId = "raw.evt.preAdmissionMedication.historyHospAcVka"
* item[13].item[9].item[2].text = "住院前維生素 K 拮抗劑"
* item[13].item[9].item[2].type = #string
* item[13].item[9].item[3].linkId = "raw.evt.preAdmissionMedication.historyHospAcNoac"
* item[13].item[9].item[3].text = "住院前非維生素 K 口服抗凝血藥"
* item[13].item[9].item[3].type = #string
* item[13].item[9].item[4].linkId = "raw.evt.preAdmissionMedication.historyHospAcOther"
* item[13].item[9].item[4].text = "住院前其他抗凝血藥"
* item[13].item[9].item[4].type = #string
* item[13].item[9].item[5].linkId = "raw.evt.preAdmissionMedication.historyHospAcNoacName"
* item[13].item[9].item[5].text = "住院前 NOAC 藥品類別"
* item[13].item[9].item[5].type = #string
* item[13].item[9].item[6].linkId = "raw.evt.preAdmissionMedication.historyHospAp"
* item[13].item[9].item[6].text = "住院前抗血小板藥"
* item[13].item[9].item[6].type = #string
* item[13].item[9].item[7].linkId = "raw.evt.preAdmissionMedication.historyHospAntiht"
* item[13].item[9].item[7].text = "住院前降血壓藥"
* item[13].item[9].item[7].type = #string
* item[13].item[9].item[8].linkId = "raw.evt.preAdmissionMedication.historyHospArrhythmia"
* item[13].item[9].item[8].text = "住院前抗心律不整藥"
* item[13].item[9].item[8].type = #string
* item[13].item[9].item[9].linkId = "raw.evt.preAdmissionMedication.historyHospDmdrug"
* item[13].item[9].item[9].text = "住院前糖尿病藥"
* item[13].item[9].item[9].type = #string
* item[13].item[9].item[10].linkId = "raw.evt.preAdmissionMedication.historyHospLld"
* item[13].item[9].item[10].text = "住院前降血脂藥"
* item[13].item[9].item[10].type = #string
* item[13].item[9].item[11].linkId = "raw.evt.preAdmissionMedication.historyHospLldStatin"
* item[13].item[9].item[11].text = "住院前 statin 類降血脂藥"
* item[13].item[9].item[11].type = #string
* item[13].item[9].item[12].linkId = "raw.evt.preAdmissionMedication.historyHospLldNonstatin"
* item[13].item[9].item[12].text = "住院前非 statin 類降血脂藥"
* item[13].item[9].item[12].type = #string
* item[13].item[10].linkId = "raw.evt.dischargeMedication"
* item[13].item[10].text = "離院用藥"
* item[13].item[10].type = #group
* item[13].item[10].item[0].linkId = "raw.evt.dischargeMedication.historyLeaveNone"
* item[13].item[10].item[0].text = "離院時無用藥註記"
* item[13].item[10].item[0].type = #string
* item[13].item[10].item[1].linkId = "raw.evt.dischargeMedication.historyLeaveAc"
* item[13].item[10].item[1].text = "離院時抗凝血藥"
* item[13].item[10].item[1].type = #string
* item[13].item[10].item[2].linkId = "raw.evt.dischargeMedication.historyLeaveAcVka"
* item[13].item[10].item[2].text = "離院時維生素 K 拮抗劑"
* item[13].item[10].item[2].type = #string
* item[13].item[10].item[3].linkId = "raw.evt.dischargeMedication.historyLeaveAcNoac"
* item[13].item[10].item[3].text = "離院時非維生素 K 口服抗凝血藥"
* item[13].item[10].item[3].type = #string
* item[13].item[10].item[4].linkId = "raw.evt.dischargeMedication.historyLeaveAcOther"
* item[13].item[10].item[4].text = "離院時其他抗凝血藥"
* item[13].item[10].item[4].type = #string
* item[13].item[10].item[5].linkId = "raw.evt.dischargeMedication.historyLeaveAcNoacName"
* item[13].item[10].item[5].text = "離院時 NOAC 藥品類別"
* item[13].item[10].item[5].type = #string
* item[13].item[10].item[6].linkId = "raw.evt.dischargeMedication.historyLeaveAp"
* item[13].item[10].item[6].text = "離院時抗血小板藥"
* item[13].item[10].item[6].type = #string
* item[13].item[10].item[7].linkId = "raw.evt.dischargeMedication.historyLeaveAntiht"
* item[13].item[10].item[7].text = "離院時降血壓藥"
* item[13].item[10].item[7].type = #string
* item[13].item[10].item[8].linkId = "raw.evt.dischargeMedication.historyLeaveArrhythmia"
* item[13].item[10].item[8].text = "離院時抗心律不整藥"
* item[13].item[10].item[8].type = #string
* item[13].item[10].item[9].linkId = "raw.evt.dischargeMedication.historyLeaveDmdrug"
* item[13].item[10].item[9].text = "離院時糖尿病藥"
* item[13].item[10].item[9].type = #string
* item[13].item[10].item[10].linkId = "raw.evt.dischargeMedication.historyLeaveLld"
* item[13].item[10].item[10].text = "離院時降血脂藥"
* item[13].item[10].item[10].type = #string
* item[13].item[10].item[11].linkId = "raw.evt.dischargeMedication.historyLeaveLldStatin"
* item[13].item[10].item[11].text = "離院時 statin 類降血脂藥"
* item[13].item[10].item[11].type = #string
* item[13].item[10].item[12].linkId = "raw.evt.dischargeMedication.historyLeaveLldNonstatin"
* item[13].item[10].item[12].text = "離院時非 statin 類降血脂藥"
* item[13].item[10].item[12].type = #string
* item[13].item[11].linkId = "raw.evt.surgery"
* item[13].item[11].text = "手術治療"
* item[13].item[11].type = #group
* item[13].item[11].item[0].linkId = "raw.evt.surgery.treatNone"
* item[13].item[11].item[0].text = "無手術治療註記"
* item[13].item[11].item[0].type = #string
* item[13].item[11].item[1].linkId = "raw.evt.surgery.treatCraniectomy"
* item[13].item[11].item[1].text = "顱骨切除減壓手術"
* item[13].item[11].item[1].type = #string
* item[13].item[11].item[2].linkId = "raw.evt.surgery.treatHematomaEvacuation"
* item[13].item[11].item[2].text = "血腫清除手術"
* item[13].item[11].item[2].type = #string
* item[13].item[11].item[3].linkId = "raw.evt.surgery.treatEvd"
* item[13].item[11].item[3].text = "腦室外引流"
* item[13].item[11].item[3].type = #string
* item[13].item[11].item[4].linkId = "raw.evt.surgery.treatVpShunt"
* item[13].item[11].item[4].text = "腦室腹腔分流"
* item[13].item[11].item[4].type = #string
* item[13].item[11].item[5].linkId = "raw.evt.surgery.treatOther"
* item[13].item[11].item[5].text = "其他手術治療註記"
* item[13].item[11].item[5].type = #string
* item[13].item[11].item[6].linkId = "raw.evt.surgery.treatOtherName"
* item[13].item[11].item[6].text = "其他手術治療名稱"
* item[13].item[11].item[6].type = #string
* item[13].item[12].linkId = "raw.evt.complication"
* item[13].item[12].text = "住院併發症"
* item[13].item[12].type = #group
* item[13].item[12].item[0].linkId = "raw.evt.complication.complicationNone"
* item[13].item[12].item[0].text = "無併發症註記"
* item[13].item[12].item[0].type = #string
* item[13].item[12].item[1].linkId = "raw.evt.complication.complicationPneumonia"
* item[13].item[12].item[1].text = "肺炎"
* item[13].item[12].item[1].type = #string
* item[13].item[12].item[2].linkId = "raw.evt.complication.complicationSepsis"
* item[13].item[12].item[2].text = "敗血症"
* item[13].item[12].item[2].type = #string
* item[13].item[12].item[3].linkId = "raw.evt.complication.complicationUti"
* item[13].item[12].item[3].text = "泌尿道感染"
* item[13].item[12].item[3].type = #string
* item[13].item[12].item[4].linkId = "raw.evt.complication.complicationAcs"
* item[13].item[12].item[4].text = "急性冠心症"
* item[13].item[12].item[4].type = #string
* item[13].item[12].item[5].linkId = "raw.evt.complication.complicationUgi"
* item[13].item[12].item[5].text = "上消化道出血"
* item[13].item[12].item[5].type = #string
* item[13].item[12].item[6].linkId = "raw.evt.complication.complicationSeizure"
* item[13].item[12].item[6].text = "癲癇發作"
* item[13].item[12].item[6].type = #string
* item[13].item[12].item[7].linkId = "raw.evt.complication.complicationRf"
* item[13].item[12].item[7].text = "腎衰竭"
* item[13].item[12].item[7].type = #string
* item[13].item[12].item[8].linkId = "raw.evt.complication.complicationDvt"
* item[13].item[12].item[8].text = "深部靜脈栓塞"
* item[13].item[12].item[8].type = #string
* item[13].item[12].item[9].linkId = "raw.evt.complication.complicationEvolution"
* item[13].item[12].item[9].text = "中風惡化"
* item[13].item[12].item[9].type = #string
* item[13].item[12].item[10].linkId = "raw.evt.complication.complicationOther"
* item[13].item[12].item[10].text = "其他併發症註記"
* item[13].item[12].item[10].type = #string
* item[13].item[12].item[11].linkId = "raw.evt.complication.complicationOtherName"
* item[13].item[12].item[11].text = "其他併發症名稱"
* item[13].item[12].item[11].type = #string
* item[13].item[13].linkId = "raw.evt.nihssAdmission"
* item[13].item[13].text = "NIHSS 最初進院"
* item[13].item[13].type = #group
* item[13].item[13].item[0].linkId = "raw.evt.nihssAdmission.nihssHospitalizationDate"
* item[13].item[13].item[0].text = "NIHSS 最初進院－評估日期"
* item[13].item[13].item[0].type = #string
* item[13].item[13].item[1].linkId = "raw.evt.nihssAdmission.nihssHospitalizationTime"
* item[13].item[13].item[1].text = "NIHSS 最初進院－評估時間"
* item[13].item[13].item[1].type = #string
* item[13].item[13].item[2].linkId = "raw.evt.nihssAdmission.nihssHospitalization1a"
* item[13].item[13].item[2].text = "NIHSS 最初進院－意識程度"
* item[13].item[13].item[2].type = #string
* item[13].item[13].item[3].linkId = "raw.evt.nihssAdmission.nihssHospitalization1b"
* item[13].item[13].item[3].text = "NIHSS 最初進院－意識提問"
* item[13].item[13].item[3].type = #string
* item[13].item[13].item[4].linkId = "raw.evt.nihssAdmission.nihssHospitalization1c"
* item[13].item[13].item[4].text = "NIHSS 最初進院－意識指令"
* item[13].item[13].item[4].type = #string
* item[13].item[13].item[5].linkId = "raw.evt.nihssAdmission.nihssHospitalization2"
* item[13].item[13].item[5].text = "NIHSS 最初進院－眼球運動"
* item[13].item[13].item[5].type = #string
* item[13].item[13].item[6].linkId = "raw.evt.nihssAdmission.nihssHospitalization3"
* item[13].item[13].item[6].text = "NIHSS 最初進院－視野"
* item[13].item[13].item[6].type = #string
* item[13].item[13].item[7].linkId = "raw.evt.nihssAdmission.nihssHospitalization4"
* item[13].item[13].item[7].text = "NIHSS 最初進院－顏面麻痺"
* item[13].item[13].item[7].type = #string
* item[13].item[13].item[8].linkId = "raw.evt.nihssAdmission.nihssHospitalization5aL"
* item[13].item[13].item[8].text = "NIHSS 最初進院－左上肢運動"
* item[13].item[13].item[8].type = #string
* item[13].item[13].item[9].linkId = "raw.evt.nihssAdmission.nihssHospitalization5bR"
* item[13].item[13].item[9].text = "NIHSS 最初進院－右上肢運動"
* item[13].item[13].item[9].type = #string
* item[13].item[13].item[10].linkId = "raw.evt.nihssAdmission.nihssHospitalization6aL"
* item[13].item[13].item[10].text = "NIHSS 最初進院－左下肢運動"
* item[13].item[13].item[10].type = #string
* item[13].item[13].item[11].linkId = "raw.evt.nihssAdmission.nihssHospitalization6bR"
* item[13].item[13].item[11].text = "NIHSS 最初進院－右下肢運動"
* item[13].item[13].item[11].type = #string
* item[13].item[13].item[12].linkId = "raw.evt.nihssAdmission.nihssHospitalization7"
* item[13].item[13].item[12].text = "NIHSS 最初進院－肢體運動失調"
* item[13].item[13].item[12].type = #string
* item[13].item[13].item[13].linkId = "raw.evt.nihssAdmission.nihssHospitalization8"
* item[13].item[13].item[13].text = "NIHSS 最初進院－感覺"
* item[13].item[13].item[13].type = #string
* item[13].item[13].item[14].linkId = "raw.evt.nihssAdmission.nihssHospitalization9"
* item[13].item[13].item[14].text = "NIHSS 最初進院－語言"
* item[13].item[13].item[14].type = #string
* item[13].item[13].item[15].linkId = "raw.evt.nihssAdmission.nihssHospitalization10"
* item[13].item[13].item[15].text = "NIHSS 最初進院－構音"
* item[13].item[13].item[15].type = #string
* item[13].item[13].item[16].linkId = "raw.evt.nihssAdmission.nihssHospitalization11"
* item[13].item[13].item[16].text = "NIHSS 最初進院－忽略"
* item[13].item[13].item[16].type = #string
* item[13].item[13].item[17].linkId = "raw.evt.nihssAdmission.nihssHospitalizationTotal"
* item[13].item[13].item[17].text = "NIHSS 最初進院－總分"
* item[13].item[13].item[17].type = #string
* item[13].item[14].linkId = "raw.evt.nihssBeforeNeedle"
* item[13].item[14].text = "NIHSS 施針前"
* item[13].item[14].type = #group
* item[13].item[14].item[0].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedleDate"
* item[13].item[14].item[0].text = "NIHSS 施針前－評估日期"
* item[13].item[14].item[0].type = #string
* item[13].item[14].item[1].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedleTime"
* item[13].item[14].item[1].text = "NIHSS 施針前－評估時間"
* item[13].item[14].item[1].type = #string
* item[13].item[14].item[2].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle1a"
* item[13].item[14].item[2].text = "NIHSS 施針前－意識程度"
* item[13].item[14].item[2].type = #string
* item[13].item[14].item[3].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle1b"
* item[13].item[14].item[3].text = "NIHSS 施針前－意識提問"
* item[13].item[14].item[3].type = #string
* item[13].item[14].item[4].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle1c"
* item[13].item[14].item[4].text = "NIHSS 施針前－意識指令"
* item[13].item[14].item[4].type = #string
* item[13].item[14].item[5].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle2"
* item[13].item[14].item[5].text = "NIHSS 施針前－眼球運動"
* item[13].item[14].item[5].type = #string
* item[13].item[14].item[6].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle3"
* item[13].item[14].item[6].text = "NIHSS 施針前－視野"
* item[13].item[14].item[6].type = #string
* item[13].item[14].item[7].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle4"
* item[13].item[14].item[7].text = "NIHSS 施針前－顏面麻痺"
* item[13].item[14].item[7].type = #string
* item[13].item[14].item[8].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle5aL"
* item[13].item[14].item[8].text = "NIHSS 施針前－左上肢運動"
* item[13].item[14].item[8].type = #string
* item[13].item[14].item[9].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle5bR"
* item[13].item[14].item[9].text = "NIHSS 施針前－右上肢運動"
* item[13].item[14].item[9].type = #string
* item[13].item[14].item[10].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle6aL"
* item[13].item[14].item[10].text = "NIHSS 施針前－左下肢運動"
* item[13].item[14].item[10].type = #string
* item[13].item[14].item[11].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle6bR"
* item[13].item[14].item[11].text = "NIHSS 施針前－右下肢運動"
* item[13].item[14].item[11].type = #string
* item[13].item[14].item[12].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle7"
* item[13].item[14].item[12].text = "NIHSS 施針前－肢體運動失調"
* item[13].item[14].item[12].type = #string
* item[13].item[14].item[13].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle8"
* item[13].item[14].item[13].text = "NIHSS 施針前－感覺"
* item[13].item[14].item[13].type = #string
* item[13].item[14].item[14].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle9"
* item[13].item[14].item[14].text = "NIHSS 施針前－語言"
* item[13].item[14].item[14].type = #string
* item[13].item[14].item[15].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle10"
* item[13].item[14].item[15].text = "NIHSS 施針前－構音"
* item[13].item[14].item[15].type = #string
* item[13].item[14].item[16].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedle11"
* item[13].item[14].item[16].text = "NIHSS 施針前－忽略"
* item[13].item[14].item[16].type = #string
* item[13].item[14].item[17].linkId = "raw.evt.nihssBeforeNeedle.nihssBeforeNeedleTotal"
* item[13].item[14].item[17].text = "NIHSS 施針前－總分"
* item[13].item[14].item[17].type = #string
* item[13].item[15].linkId = "raw.evt.nihss24Hour"
* item[13].item[15].text = "NIHSS 治療後 24 小時"
* item[13].item[15].type = #group
* item[13].item[15].item[0].linkId = "raw.evt.nihss24Hour.nihss24hDate"
* item[13].item[15].item[0].text = "NIHSS 治療後 24 小時－評估日期"
* item[13].item[15].item[0].type = #string
* item[13].item[15].item[1].linkId = "raw.evt.nihss24Hour.nihss24hTime"
* item[13].item[15].item[1].text = "NIHSS 治療後 24 小時－評估時間"
* item[13].item[15].item[1].type = #string
* item[13].item[15].item[2].linkId = "raw.evt.nihss24Hour.nihss24h1a"
* item[13].item[15].item[2].text = "NIHSS 治療後 24 小時－意識程度"
* item[13].item[15].item[2].type = #string
* item[13].item[15].item[3].linkId = "raw.evt.nihss24Hour.nihss24h1b"
* item[13].item[15].item[3].text = "NIHSS 治療後 24 小時－意識提問"
* item[13].item[15].item[3].type = #string
* item[13].item[15].item[4].linkId = "raw.evt.nihss24Hour.nihss24h1c"
* item[13].item[15].item[4].text = "NIHSS 治療後 24 小時－意識指令"
* item[13].item[15].item[4].type = #string
* item[13].item[15].item[5].linkId = "raw.evt.nihss24Hour.nihss24h2"
* item[13].item[15].item[5].text = "NIHSS 治療後 24 小時－眼球運動"
* item[13].item[15].item[5].type = #string
* item[13].item[15].item[6].linkId = "raw.evt.nihss24Hour.nihss24h3"
* item[13].item[15].item[6].text = "NIHSS 治療後 24 小時－視野"
* item[13].item[15].item[6].type = #string
* item[13].item[15].item[7].linkId = "raw.evt.nihss24Hour.nihss24h4"
* item[13].item[15].item[7].text = "NIHSS 治療後 24 小時－顏面麻痺"
* item[13].item[15].item[7].type = #string
* item[13].item[15].item[8].linkId = "raw.evt.nihss24Hour.nihss24h5aL"
* item[13].item[15].item[8].text = "NIHSS 治療後 24 小時－左上肢運動"
* item[13].item[15].item[8].type = #string
* item[13].item[15].item[9].linkId = "raw.evt.nihss24Hour.nihss24h5bR"
* item[13].item[15].item[9].text = "NIHSS 治療後 24 小時－右上肢運動"
* item[13].item[15].item[9].type = #string
* item[13].item[15].item[10].linkId = "raw.evt.nihss24Hour.nihss24h6aL"
* item[13].item[15].item[10].text = "NIHSS 治療後 24 小時－左下肢運動"
* item[13].item[15].item[10].type = #string
* item[13].item[15].item[11].linkId = "raw.evt.nihss24Hour.nihss24h6bR"
* item[13].item[15].item[11].text = "NIHSS 治療後 24 小時－右下肢運動"
* item[13].item[15].item[11].type = #string
* item[13].item[15].item[12].linkId = "raw.evt.nihss24Hour.nihss24h7"
* item[13].item[15].item[12].text = "NIHSS 治療後 24 小時－肢體運動失調"
* item[13].item[15].item[12].type = #string
* item[13].item[15].item[13].linkId = "raw.evt.nihss24Hour.nihss24h8"
* item[13].item[15].item[13].text = "NIHSS 治療後 24 小時－感覺"
* item[13].item[15].item[13].type = #string
* item[13].item[15].item[14].linkId = "raw.evt.nihss24Hour.nihss24h9"
* item[13].item[15].item[14].text = "NIHSS 治療後 24 小時－語言"
* item[13].item[15].item[14].type = #string
* item[13].item[15].item[15].linkId = "raw.evt.nihss24Hour.nihss24h10"
* item[13].item[15].item[15].text = "NIHSS 治療後 24 小時－構音"
* item[13].item[15].item[15].type = #string
* item[13].item[15].item[16].linkId = "raw.evt.nihss24Hour.nihss24h11"
* item[13].item[15].item[16].text = "NIHSS 治療後 24 小時－忽略"
* item[13].item[15].item[16].type = #string
* item[13].item[15].item[17].linkId = "raw.evt.nihss24Hour.nihss24hTotal"
* item[13].item[15].item[17].text = "NIHSS 治療後 24 小時－總分"
* item[13].item[15].item[17].type = #string
* item[13].item[16].linkId = "raw.evt.discharge"
* item[13].item[16].text = "離院結果"
* item[13].item[16].type = #group
* item[13].item[16].item[0].linkId = "raw.evt.discharge.leaveMrs"
* item[13].item[16].item[0].text = "離院 mRS 評分"
* item[13].item[16].item[0].type = #string
* item[13].item[16].item[1].linkId = "raw.evt.discharge.leave"
* item[13].item[16].item[1].text = "離院情形"
* item[13].item[16].item[1].type = #string
* item[13].item[16].item[2].linkId = "raw.evt.discharge.leaveDeadDate"
* item[13].item[16].item[2].text = "離院死亡日期"
* item[13].item[16].item[2].type = #string
* item[13].item[16].item[3].linkId = "raw.evt.discharge.leaveDeadCause"
* item[13].item[16].item[3].text = "離院死亡原因類別"
* item[13].item[16].item[3].type = #string
* item[13].item[16].item[4].linkId = "raw.evt.discharge.leaveDeadCauseOther"
* item[13].item[16].item[4].text = "離院其他死亡原因"
* item[13].item[16].item[4].type = #string
* item[13].item[16].item[5].linkId = "raw.evt.discharge.leavePlace"
* item[13].item[16].item[5].text = "離院去向"
* item[13].item[16].item[5].type = #string
* item[13].item[16].item[6].linkId = "raw.evt.discharge.leavePlaceHospital"
* item[13].item[16].item[6].text = "離院轉入醫院"
* item[13].item[16].item[6].type = #string
* item[13].item[17].linkId = "raw.evt.preEvt"
* item[13].item[17].text = "EVT 前評估與治療"
* item[13].item[17].type = #group
* item[13].item[17].item[0].linkId = "raw.evt.preEvt.beforeEvtCtDate"
* item[13].item[17].item[0].text = "EVT 前 CT 日期"
* item[13].item[17].item[0].type = #string
* item[13].item[17].item[1].linkId = "raw.evt.preEvt.beforeEvtCtTime"
* item[13].item[17].item[1].text = "EVT 前 CT 時間"
* item[13].item[17].item[1].type = #string
* item[13].item[17].item[2].linkId = "raw.evt.preEvt.beforeEvtCtaDate"
* item[13].item[17].item[2].text = "EVT 前 CTA 日期"
* item[13].item[17].item[2].type = #string
* item[13].item[17].item[3].linkId = "raw.evt.preEvt.beforeEvtCtaTime"
* item[13].item[17].item[3].text = "EVT 前 CTA 時間"
* item[13].item[17].item[3].type = #string
* item[13].item[17].item[4].linkId = "raw.evt.preEvt.beforeEvtMriDate"
* item[13].item[17].item[4].text = "EVT 前 MRI 日期"
* item[13].item[17].item[4].type = #string
* item[13].item[17].item[5].linkId = "raw.evt.preEvt.beforeEvtMriTime"
* item[13].item[17].item[5].text = "EVT 前 MRI 時間"
* item[13].item[17].item[5].type = #string
* item[13].item[17].item[6].linkId = "raw.evt.preEvt.beforeEvtIvtpa"
* item[13].item[17].item[6].text = "EVT 前 IV-tPA 施打醫院／未施打"
* item[13].item[17].item[6].type = #string
* item[13].item[17].item[7].linkId = "raw.evt.preEvt.beforeEvtIvtpaDate"
* item[13].item[17].item[7].text = "EVT 前 IV-tPA 日期"
* item[13].item[17].item[7].type = #string
* item[13].item[17].item[8].linkId = "raw.evt.preEvt.beforeEvtIvtpaTime"
* item[13].item[17].item[8].text = "EVT 前 IV-tPA 時間"
* item[13].item[17].item[8].type = #string
* item[13].item[17].item[9].linkId = "raw.evt.preEvt.beforeEvtIvtpaDose"
* item[13].item[17].item[9].text = "EVT 前 IV-tPA 劑量"
* item[13].item[17].item[9].type = #string
* item[13].item[18].linkId = "raw.evt.imaging"
* item[13].item[18].text = "影像與灌流評估"
* item[13].item[18].type = #group
* item[13].item[18].item[0].linkId = "raw.evt.imaging.aspects"
* item[13].item[18].item[0].text = "EVT 前 ASPECTS 分數"
* item[13].item[18].item[0].type = #string
* item[13].item[18].item[1].linkId = "raw.evt.imaging.ctpMrpNone"
* item[13].item[18].item[1].text = "未執行 CTP／MRP 註記"
* item[13].item[18].item[1].type = #string
* item[13].item[18].item[2].linkId = "raw.evt.imaging.ctp"
* item[13].item[18].item[2].text = "CT 灌流影像檢查註記"
* item[13].item[18].item[2].type = #string
* item[13].item[18].item[3].linkId = "raw.evt.imaging.mrp"
* item[13].item[18].item[3].text = "MR 灌流影像檢查註記"
* item[13].item[18].item[3].type = #string
* item[13].item[18].item[4].linkId = "raw.evt.imaging.analysisRapid"
* item[13].item[18].item[4].text = "採用 RAPID 分析註記"
* item[13].item[18].item[4].type = #string
* item[13].item[18].item[5].linkId = "raw.evt.imaging.analysisOther"
* item[13].item[18].item[5].text = "採用其他影像分析註記"
* item[13].item[18].item[5].type = #string
* item[13].item[18].item[6].linkId = "raw.evt.imaging.ratio"
* item[13].item[18].item[6].text = "灌流影像 mismatch 比值"
* item[13].item[18].item[6].type = #string
* item[13].item[18].item[7].linkId = "raw.evt.imaging.core"
* item[13].item[18].item[7].text = "灌流影像核心體積"
* item[13].item[18].item[7].type = #string
* item[13].item[18].item[8].linkId = "raw.evt.imaging.mismatchVol"
* item[13].item[18].item[8].text = "灌流影像 mismatch 體積"
* item[13].item[18].item[8].type = #string
* item[13].item[18].item[9].linkId = "raw.evt.imaging.mCTAScore"
* item[13].item[18].item[9].text = "多期 CTA 側枝循環分組"
* item[13].item[18].item[9].type = #string
* item[13].item[19].linkId = "raw.evt.targetVessel"
* item[13].item[19].text = "EVT 目標血管"
* item[13].item[19].type = #group
* item[13].item[19].item[0].linkId = "raw.evt.targetVessel.targetCervicalIca"
* item[13].item[19].item[0].text = "頸段內頸動脈目標血管註記"
* item[13].item[19].item[0].type = #string
* item[13].item[19].item[1].linkId = "raw.evt.targetVessel.targetCervicalIcaR"
* item[13].item[19].item[1].text = "右側頸段內頸動脈目標血管註記"
* item[13].item[19].item[1].type = #string
* item[13].item[19].item[2].linkId = "raw.evt.targetVessel.targetCervicalIcaL"
* item[13].item[19].item[2].text = "左側頸段內頸動脈目標血管註記"
* item[13].item[19].item[2].type = #string
* item[13].item[19].item[3].linkId = "raw.evt.targetVessel.targetCarotidTerminius"
* item[13].item[19].item[3].text = "內頸動脈末端目標血管註記"
* item[13].item[19].item[3].type = #string
* item[13].item[19].item[4].linkId = "raw.evt.targetVessel.targetCarotidTerminiusR"
* item[13].item[19].item[4].text = "右側內頸動脈末端目標血管註記"
* item[13].item[19].item[4].type = #string
* item[13].item[19].item[5].linkId = "raw.evt.targetVessel.targetCarotidTerminiusL"
* item[13].item[19].item[5].text = "左側內頸動脈末端目標血管註記"
* item[13].item[19].item[5].type = #string
* item[13].item[19].item[6].linkId = "raw.evt.targetVessel.targetM1"
* item[13].item[19].item[6].text = "中大腦動脈 M1 目標血管註記"
* item[13].item[19].item[6].type = #string
* item[13].item[19].item[7].linkId = "raw.evt.targetVessel.targetM1R"
* item[13].item[19].item[7].text = "右側中大腦動脈 M1 目標血管註記"
* item[13].item[19].item[7].type = #string
* item[13].item[19].item[8].linkId = "raw.evt.targetVessel.targetM1L"
* item[13].item[19].item[8].text = "左側中大腦動脈 M1 目標血管註記"
* item[13].item[19].item[8].type = #string
* item[13].item[19].item[9].linkId = "raw.evt.targetVessel.targetM2"
* item[13].item[19].item[9].text = "中大腦動脈 M2 目標血管註記"
* item[13].item[19].item[9].type = #string
* item[13].item[19].item[10].linkId = "raw.evt.targetVessel.targetM2R"
* item[13].item[19].item[10].text = "右側中大腦動脈 M2 目標血管註記"
* item[13].item[19].item[10].type = #string
* item[13].item[19].item[11].linkId = "raw.evt.targetVessel.targetM2L"
* item[13].item[19].item[11].text = "左側中大腦動脈 M2 目標血管註記"
* item[13].item[19].item[11].type = #string
* item[13].item[19].item[12].linkId = "raw.evt.targetVessel.targetM3"
* item[13].item[19].item[12].text = "中大腦動脈 M3 目標血管註記"
* item[13].item[19].item[12].type = #string
* item[13].item[19].item[13].linkId = "raw.evt.targetVessel.targetM3R"
* item[13].item[19].item[13].text = "右側中大腦動脈 M3 目標血管註記"
* item[13].item[19].item[13].type = #string
* item[13].item[19].item[14].linkId = "raw.evt.targetVessel.targetM3L"
* item[13].item[19].item[14].text = "左側中大腦動脈 M3 目標血管註記"
* item[13].item[19].item[14].type = #string
* item[13].item[19].item[15].linkId = "raw.evt.targetVessel.targetAca"
* item[13].item[19].item[15].text = "前大腦動脈目標血管註記"
* item[13].item[19].item[15].type = #string
* item[13].item[19].item[16].linkId = "raw.evt.targetVessel.targetAcaR"
* item[13].item[19].item[16].text = "右側前大腦動脈目標血管註記"
* item[13].item[19].item[16].type = #string
* item[13].item[19].item[17].linkId = "raw.evt.targetVessel.targetAcaL"
* item[13].item[19].item[17].text = "左側前大腦動脈目標血管註記"
* item[13].item[19].item[17].type = #string
* item[13].item[19].item[18].linkId = "raw.evt.targetVessel.targetPca"
* item[13].item[19].item[18].text = "後大腦動脈目標血管註記"
* item[13].item[19].item[18].type = #string
* item[13].item[19].item[19].linkId = "raw.evt.targetVessel.targetPcaR"
* item[13].item[19].item[19].text = "右側後大腦動脈目標血管註記"
* item[13].item[19].item[19].type = #string
* item[13].item[19].item[20].linkId = "raw.evt.targetVessel.targetPcaL"
* item[13].item[19].item[20].text = "左側後大腦動脈目標血管註記"
* item[13].item[19].item[20].type = #string
* item[13].item[19].item[21].linkId = "raw.evt.targetVessel.targetBa"
* item[13].item[19].item[21].text = "基底動脈目標血管註記"
* item[13].item[19].item[21].type = #string
* item[13].item[19].item[22].linkId = "raw.evt.targetVessel.targetVa"
* item[13].item[19].item[22].text = "椎動脈目標血管註記"
* item[13].item[19].item[22].type = #string
* item[13].item[19].item[23].linkId = "raw.evt.targetVessel.targetVaR"
* item[13].item[19].item[23].text = "右側椎動脈目標血管註記"
* item[13].item[19].item[23].type = #string
* item[13].item[19].item[24].linkId = "raw.evt.targetVessel.targetVaL"
* item[13].item[19].item[24].text = "左側椎動脈目標血管註記"
* item[13].item[19].item[24].type = #string
* item[13].item[20].linkId = "raw.evt.evtComplication"
* item[13].item[20].text = "EVT 相關併發症"
* item[13].item[20].type = #group
* item[13].item[20].item[0].linkId = "raw.evt.evtComplication.afterEvtComplicationNone"
* item[13].item[20].item[0].text = "無 EVT 相關併發症註記"
* item[13].item[20].item[0].type = #string
* item[13].item[20].item[1].linkId = "raw.evt.evtComplication.afterEvtComplicateDissect"
* item[13].item[20].item[1].text = "EVT 後血管剝離"
* item[13].item[20].item[1].type = #string
* item[13].item[20].item[2].linkId = "raw.evt.evtComplication.afterEvtComplicationPh"
* item[13].item[20].item[2].text = "EVT 後穿刺處血腫"
* item[13].item[20].item[2].type = #string
* item[13].item[20].item[3].linkId = "raw.evt.evtComplication.afterEvtComplicationOther"
* item[13].item[20].item[3].text = "其他 EVT 相關併發症"
* item[13].item[20].item[3].type = #string
* item[13].item[21].linkId = "raw.evt.followUpImaging"
* item[13].item[21].text = "追蹤影像"
* item[13].item[21].type = #group
* item[13].item[21].item[0].linkId = "raw.evt.followUpImaging.imageNone"
* item[13].item[21].item[0].text = "無追蹤影像註記"
* item[13].item[21].item[0].type = #string
* item[13].item[21].item[1].linkId = "raw.evt.followUpImaging.imageCt"
* item[13].item[21].item[1].text = "有追蹤 CT 影像"
* item[13].item[21].item[1].type = #string
* item[13].item[21].item[2].linkId = "raw.evt.followUpImaging.imageCtDate"
* item[13].item[21].item[2].text = "追蹤 CT 日期"
* item[13].item[21].item[2].type = #string
* item[13].item[21].item[3].linkId = "raw.evt.followUpImaging.imageCtTime"
* item[13].item[21].item[3].text = "追蹤 CT 時間"
* item[13].item[21].item[3].type = #string
* item[13].item[21].item[4].linkId = "raw.evt.followUpImaging.imageMr"
* item[13].item[21].item[4].text = "有追蹤 MR 影像"
* item[13].item[21].item[4].type = #string
* item[13].item[21].item[5].linkId = "raw.evt.followUpImaging.imageMrDate"
* item[13].item[21].item[5].text = "追蹤 MR 日期"
* item[13].item[21].item[5].type = #string
* item[13].item[21].item[6].linkId = "raw.evt.followUpImaging.imageMrTime"
* item[13].item[21].item[6].text = "追蹤 MR 時間"
* item[13].item[21].item[6].type = #string
* item[13].item[21].item[7].linkId = "raw.evt.followUpImaging.imageIch"
* item[13].item[21].item[7].text = "追蹤影像顱內出血"
* item[13].item[21].item[7].type = #string
* item[13].item[21].item[8].linkId = "raw.evt.followUpImaging.imageIchDetail"
* item[13].item[21].item[8].text = "追蹤出血症狀分類"
* item[13].item[21].item[8].type = #string
* item[13].item[21].item[9].linkId = "raw.evt.followUpImaging.imageInfarct"
* item[13].item[21].item[9].text = "追蹤影像梗塞"
* item[13].item[21].item[9].type = #string
* item[13].item[21].item[10].linkId = "raw.evt.followUpImaging.imageOther"
* item[13].item[21].item[10].text = "其他追蹤影像結果註記"
* item[13].item[21].item[10].type = #string
* item[13].item[22].linkId = "raw.evt.anesthesia"
* item[13].item[22].text = "麻醉與鎮靜"
* item[13].item[22].type = #group
* item[13].item[22].item[0].linkId = "raw.evt.anesthesia.generalAnesthesia"
* item[13].item[22].item[0].text = "全身麻醉註記"
* item[13].item[22].item[0].type = #string
* item[13].item[22].item[1].linkId = "raw.evt.anesthesia.sedation"
* item[13].item[22].item[1].text = "鎮靜註記"
* item[13].item[22].item[1].type = #string
* item[13].item[22].item[2].linkId = "raw.evt.anesthesia.sedationName"
* item[13].item[22].item[2].text = "鎮靜藥物名稱"
* item[13].item[22].item[2].type = #string
* item[13].item[22].item[3].linkId = "raw.evt.anesthesia.sedationDose"
* item[13].item[22].item[3].text = "鎮靜劑量／持續時間"
* item[13].item[22].item[3].type = #string
* item[13].item[23].linkId = "raw.evt.puncture"
* item[13].item[23].text = "穿刺資訊"
* item[13].item[23].type = #group
* item[13].item[23].item[0].linkId = "raw.evt.puncture.punctureDate"
* item[13].item[23].item[0].text = "穿刺日期"
* item[13].item[23].item[0].type = #string
* item[13].item[23].item[1].linkId = "raw.evt.puncture.punctureTime"
* item[13].item[23].item[1].text = "穿刺時間"
* item[13].item[23].item[1].type = #string
* item[13].item[23].item[2].linkId = "raw.evt.puncture.punctureArea"
* item[13].item[23].item[2].text = "穿刺部位"
* item[13].item[23].item[2].type = #string
* item[13].item[24].linkId = "raw.evt.vascularAnatomy"
* item[13].item[24].text = "血管解剖與狹窄"
* item[13].item[24].type = #group
* item[13].item[24].item[0].linkId = "raw.evt.vascularAnatomy.aorticArch"
* item[13].item[24].item[0].text = "主動脈弓型態"
* item[13].item[24].item[0].type = #string
* item[13].item[24].item[1].linkId = "raw.evt.vascularAnatomy.ccaR"
* item[13].item[24].item[1].text = "右總頸動脈狹窄分組"
* item[13].item[24].item[1].type = #string
* item[13].item[24].item[2].linkId = "raw.evt.vascularAnatomy.ccaL"
* item[13].item[24].item[2].text = "左總頸動脈狹窄分組"
* item[13].item[24].item[2].type = #string
* item[13].item[24].item[3].linkId = "raw.evt.vascularAnatomy.rva"
* item[13].item[24].item[3].text = "右椎動脈狹窄分組"
* item[13].item[24].item[3].type = #string
* item[13].item[24].item[4].linkId = "raw.evt.vascularAnatomy.lva"
* item[13].item[24].item[4].text = "左椎動脈狹窄分組"
* item[13].item[24].item[4].type = #string
* item[13].item[24].item[5].linkId = "raw.evt.vascularAnatomy.icaR"
* item[13].item[24].item[5].text = "右內頸動脈狹窄分組"
* item[13].item[24].item[5].type = #string
* item[13].item[24].item[6].linkId = "raw.evt.vascularAnatomy.icaL"
* item[13].item[24].item[6].text = "左內頸動脈狹窄分組"
* item[13].item[24].item[6].type = #string
* item[13].item[25].linkId = "raw.evt.evtProcedure"
* item[13].item[25].text = "EVT 治療"
* item[13].item[25].type = #group
* item[13].item[25].item[0].linkId = "raw.evt.evtProcedure.evtTreatNone"
* item[13].item[25].item[0].text = "無 EVT 治療項目註記"
* item[13].item[25].item[0].type = #string
* item[13].item[25].item[1].linkId = "raw.evt.evtProcedure.evtTreatBalloonGuiding"
* item[13].item[25].item[1].text = "使用球囊導引導管"
* item[13].item[25].item[1].type = #string
* item[13].item[25].item[2].linkId = "raw.evt.evtProcedure.evtTreatStenting"
* item[13].item[25].item[2].text = "置放支架"
* item[13].item[25].item[2].type = #string
* item[13].item[25].item[3].linkId = "raw.evt.evtProcedure.evtTreatSuction"
* item[13].item[25].item[3].text = "抽吸取栓"
* item[13].item[25].item[3].type = #string
* item[13].item[25].item[4].linkId = "raw.evt.evtProcedure.evtTreatSuctionDetail"
* item[13].item[25].item[4].text = "抽吸策略類別"
* item[13].item[25].item[4].type = #string
* item[13].item[25].item[5].linkId = "raw.evt.evtProcedure.evtTreatIntraArterial"
* item[13].item[25].item[5].text = "動脈內藥物治療"
* item[13].item[25].item[5].type = #string
* item[13].item[25].item[6].linkId = "raw.evt.evtProcedure.evtTreatIntraArterialName"
* item[13].item[25].item[6].text = "動脈內治療藥物名稱"
* item[13].item[25].item[6].type = #string
* item[13].item[25].item[7].linkId = "raw.evt.evtProcedure.evtTreatIntraArterialDose"
* item[13].item[25].item[7].text = "動脈內治療藥物劑量"
* item[13].item[25].item[7].type = #string
* item[13].item[25].item[8].linkId = "raw.evt.evtProcedure.evtTreatStentriever"
* item[13].item[25].item[8].text = "支架取栓器使用註記"
* item[13].item[25].item[8].type = #string
* item[13].item[25].item[9].linkId = "raw.evt.evtProcedure.evtTreatStentrieverNo"
* item[13].item[25].item[9].text = "取栓次數（原文 Press No.）"
* item[13].item[25].item[9].type = #string
* item[13].item[25].item[10].linkId = "raw.evt.evtProcedure.evtTreatBalloonAngioplasty"
* item[13].item[25].item[10].text = "球囊血管成形術"
* item[13].item[25].item[10].type = #string
* item[13].item[25].item[11].linkId = "raw.evt.evtProcedure.evtTreatSuctionDetail1"
* item[13].item[25].item[11].text = "抽吸後救援策略補充欄"
* item[13].item[25].item[11].type = #string
* item[13].item[25].item[12].linkId = "raw.evt.evtProcedure.evtTreatSuctionCs"
* item[13].item[25].item[12].text = "抽吸失敗後救援策略"
* item[13].item[25].item[12].type = #string
* item[13].item[25].item[13].linkId = "raw.evt.evtProcedure.evtTreatSuctionCsOther"
* item[13].item[25].item[13].text = "抽吸救援其他方式"
* item[13].item[25].item[13].type = #string
* item[13].item[25].item[14].linkId = "raw.evt.evtProcedure.evtTreatStentrieverCs"
* item[13].item[25].item[14].text = "支架取栓後救援治療註記"
* item[13].item[25].item[14].type = #string
* item[13].item[25].item[15].linkId = "raw.evt.evtProcedure.evtTreatStentrieverCsDetail"
* item[13].item[25].item[15].text = "支架取栓後救援策略"
* item[13].item[25].item[15].type = #string
* item[13].item[25].item[16].linkId = "raw.evt.evtProcedure.evtTreatStentrieverCsOther"
* item[13].item[25].item[16].text = "支架取栓救援其他方式"
* item[13].item[25].item[16].type = #string
* item[13].item[26].linkId = "raw.evt.antithrombotic24Hour"
* item[13].item[26].text = "24 小時內抗血栓治療"
* item[13].item[26].type = #group
* item[13].item[26].item[0].linkId = "raw.evt.antithrombotic24Hour.antiThromboticsNone"
* item[13].item[26].item[0].text = "24 小時內未用抗血栓藥註記"
* item[13].item[26].item[0].type = #string
* item[13].item[26].item[1].linkId = "raw.evt.antithrombotic24Hour.antiThromboticsInhibitor"
* item[13].item[26].item[1].text = "24 小時內使用 inhibitor 註記"
* item[13].item[26].item[1].type = #string
* item[13].item[26].item[2].linkId = "raw.evt.antithrombotic24Hour.antiThromboticsDapt"
* item[13].item[26].item[2].text = "24 小時內雙重抗血小板治療"
* item[13].item[26].item[2].type = #string
* item[13].item[26].item[3].linkId = "raw.evt.antithrombotic24Hour.antiThromboticsSapt"
* item[13].item[26].item[3].text = "24 小時內單一抗血小板治療"
* item[13].item[26].item[3].type = #string
* item[13].item[26].item[4].linkId = "raw.evt.antithrombotic24Hour.antiThromboticsAc"
* item[13].item[26].item[4].text = "24 小時內抗凝血治療"
* item[13].item[26].item[4].type = #string
* item[13].item[26].item[5].linkId = "raw.evt.antithrombotic24Hour.antiThromboticsAcDetail"
* item[13].item[26].item[5].text = "24 小時內抗凝血藥物類別"
* item[13].item[26].item[5].type = #string
* item[13].item[27].linkId = "raw.evt.evtOutcome"
* item[13].item[27].text = "EVT 術後結果"
* item[13].item[27].type = #group
* item[13].item[27].item[0].linkId = "raw.evt.evtOutcome.finalTici"
* item[13].item[27].item[0].text = "最終 TICI 再灌流等級"
* item[13].item[27].item[0].type = #string
* item[13].item[27].item[1].linkId = "raw.evt.evtOutcome.reThrombosis"
* item[13].item[27].item[1].text = "5 至 10 分鐘內再血栓形成"
* item[13].item[27].item[1].type = #string
* item[13].item[27].item[2].linkId = "raw.evt.evtOutcome.embolismNew"
* item[13].item[27].item[2].text = "新血管區域栓塞"
* item[13].item[27].item[2].type = #string
* item[13].item[27].item[3].linkId = "raw.evt.evtOutcome.embolismNewDetail"
* item[13].item[27].item[3].text = "新血管區域栓塞細項"
* item[13].item[27].item[3].type = #string
* item[13].item[27].item[4].linkId = "raw.evt.evtOutcome.afterEvtBp"
* item[13].item[27].item[4].text = "EVT 術後血壓控制分組"
* item[13].item[27].item[4].type = #string
* item[13].item[28].linkId = "raw.evt.recanalization"
* item[13].item[28].text = "血管再通時間"
* item[13].item[28].type = #group
* item[13].item[28].item[0].linkId = "raw.evt.recanalization.recanalizationFirstDate"
* item[13].item[28].item[0].text = "首次再通日期"
* item[13].item[28].item[0].type = #string
* item[13].item[28].item[1].linkId = "raw.evt.recanalization.recanalizationFirstTime"
* item[13].item[28].item[1].text = "首次再通時間"
* item[13].item[28].item[1].type = #string
* item[13].item[28].item[2].linkId = "raw.evt.recanalization.recanalizationFinalDate"
* item[13].item[28].item[2].text = "最終再通日期"
* item[13].item[28].item[2].type = #string
* item[13].item[28].item[3].linkId = "raw.evt.recanalization.recanalizationFinalTime"
* item[13].item[28].item[3].text = "最終再通時間"
* item[13].item[28].item[3].type = #string
* item[13].item[29].linkId = "raw.evt.followUp3Month"
* item[13].item[29].text = "中風後 3 個月追蹤"
* item[13].item[29].type = #group
* item[13].item[29].item[0].linkId = "raw.evt.followUp3Month.traceThreeDate"
* item[13].item[29].item[0].text = "中風後 3 個月追蹤日期"
* item[13].item[29].item[0].type = #string
* item[13].item[29].item[1].linkId = "raw.evt.followUp3Month.traceThreeMrs"
* item[13].item[29].item[1].text = "中風後 3 個月 mRS 評分"
* item[13].item[29].item[1].type = #string
* item[13].item[29].item[2].linkId = "raw.evt.followUp3Month.traceThreePlace"
* item[13].item[29].item[2].text = "中風後 3 個月所在處所"
* item[13].item[29].item[2].type = #string
* item[13].item[29].item[3].linkId = "raw.evt.followUp3Month.traceThreePlaceHospital"
* item[13].item[29].item[3].text = "中風後 3 個月所在醫院"
* item[13].item[29].item[3].type = #string
* item[13].item[29].item[4].linkId = "raw.evt.followUp3Month.traceThreeNonFollow"
* item[13].item[29].item[4].text = "3 個月追蹤未完成註記"
* item[13].item[29].item[4].type = #string
* item[13].item[30].linkId = "raw.evt.followUpEvent"
* item[13].item[30].text = "追蹤醫療事件"
* item[13].item[30].type = #group
* item[13].item[30].item[0].linkId = "raw.evt.followUpEvent.traceTreat1"
* item[13].item[30].item[0].text = "追蹤醫療狀態"
* item[13].item[30].item[0].type = #string
* item[13].item[30].item[1].linkId = "raw.evt.followUpEvent.traceTreat1Hospital"
* item[13].item[30].item[1].text = "追蹤回診醫院"
* item[13].item[30].item[1].type = #string
* item[13].item[30].item[2].linkId = "raw.evt.followUpEvent.traceTreat1Refuse"
* item[13].item[30].item[2].text = "拒絕回診說明"
* item[13].item[30].item[2].type = #string
* item[13].item[30].item[3].linkId = "raw.evt.followUpEvent.traceTreat1DeadDate"
* item[13].item[30].item[3].text = "追蹤死亡日期"
* item[13].item[30].item[3].type = #string
* item[13].item[30].item[4].linkId = "raw.evt.followUpEvent.traceTreat1DeadCause"
* item[13].item[30].item[4].text = "追蹤死亡原因類別"
* item[13].item[30].item[4].type = #string
* item[13].item[30].item[5].linkId = "raw.evt.followUpEvent.traceTreat1DeadStrokeIch"
* item[13].item[30].item[5].text = "因出血性中風死亡註記"
* item[13].item[30].item[5].type = #string
* item[13].item[30].item[6].linkId = "raw.evt.followUpEvent.traceTreat1DeadStrokeIs"
* item[13].item[30].item[6].text = "因缺血性中風死亡註記"
* item[13].item[30].item[6].type = #string
* item[13].item[30].item[7].linkId = "raw.evt.followUpEvent.traceTreat1DeadOther"
* item[13].item[30].item[7].text = "追蹤其他死亡原因"
* item[13].item[30].item[7].type = #string
* item[13].item[30].item[8].linkId = "raw.evt.followUpEvent.traceTreat2"
* item[13].item[30].item[8].text = "追蹤再中風狀態"
* item[13].item[30].item[8].type = #string
* item[13].item[30].item[9].linkId = "raw.evt.followUpEvent.traceTreat2StrokeIch"
* item[13].item[30].item[9].text = "再發出血性中風"
* item[13].item[30].item[9].type = #string
* item[13].item[30].item[10].linkId = "raw.evt.followUpEvent.traceTreat2StrokeIs"
* item[13].item[30].item[10].text = "再發缺血性中風"
* item[13].item[30].item[10].type = #string
* item[13].item[30].item[11].linkId = "raw.evt.followUpEvent.traceTreat2StrokeDate"
* item[13].item[30].item[11].text = "再中風日期"
* item[13].item[30].item[11].type = #string
* item[13].item[30].item[12].linkId = "raw.evt.followUpEvent.traceTreat2StrokeHospital"
* item[13].item[30].item[12].text = "再中風就醫醫院"
* item[13].item[30].item[12].type = #string
* item[13].item[31].linkId = "raw.evt.preStrokeFunction"
* item[13].item[31].text = "中風前功能"
* item[13].item[31].type = #group
* item[13].item[31].item[0].linkId = "raw.evt.preStrokeFunction.preStrokeMRS"
* item[13].item[31].item[0].text = "本次中風前 mRS 評分"
* item[13].item[31].item[0].type = #string
* item[13].item[31].item[1].linkId = "raw.evt.preStrokeFunction.preStrokeIndependent"
* item[13].item[31].item[1].text = "本次中風前可獨立生活註記"
* item[13].item[31].item[1].type = #string
* item[14].linkId = "raw.rapid"
* item[14].text = "RAPID 原始值"
* item[14].type = #group
* item[14].item[0].linkId = "raw.rapid.hisnummark"
* item[14].item[0].text = "病歷號"
* item[14].item[0].type = #string
* item[14].item[1].linkId = "raw.rapid.rpreqno"
* item[14].item[1].text = "申請序號"
* item[14].item[1].type = #string
* item[14].item[2].linkId = "raw.rapid.scantype"
* item[14].item[2].text = "掃描類型"
* item[14].item[2].type = #string
* item[14].item[3].linkId = "raw.rapid.latestseriesdate"
* item[14].item[3].text = "最近一次掃描 series 日期"
* item[14].item[3].type = #string
* item[14].item[4].linkId = "raw.rapid.aspectsAffectedside"
* item[14].item[4].text = "ASPECTS 影響側"
* item[14].item[4].type = #string
* item[14].item[5].linkId = "raw.rapid.aspects"
* item[14].item[5].text = "ASPECTS 分數"
* item[14].item[5].type = #string
* item[14].item[6].linkId = "raw.rapid.ctaAffectedside"
* item[14].item[6].text = "CTA 影響側"
* item[14].item[6].type = #string
* item[14].item[7].linkId = "raw.rapid.cbfVolume"
* item[14].item[7].text = "CBF<30% 體積"
* item[14].item[7].type = #string
* item[14].item[8].linkId = "raw.rapid.tmaxVolume"
* item[14].item[8].text = "Tmax>6 秒體積"
* item[14].item[8].type = #string
* item[14].item[9].linkId = "raw.rapid.mismatchVolume"
* item[14].item[9].text = "不一致體積"
* item[14].item[9].type = #string
* item[14].item[10].linkId = "raw.rapid.mismatchRatio"
* item[14].item[10].text = "不一致比率"
* item[14].item[10].type = #string
* item[14].item[11].linkId = "raw.rapid.hypoperfusionIntensityRatio"
* item[14].item[11].text = "低灌注強度比值"
* item[14].item[11].type = #string
* item[14].item[12].linkId = "raw.rapid.hid"
* item[14].item[12].text = "醫院代號"
* item[14].item[12].type = #string
* item[14].item[13].linkId = "raw.rapid.zrapid"
* item[14].item[13].text = "日期時戳"
* item[14].item[13].type = #string
* item[14].item[14].linkId = "raw.rapid.mtqualified"
* item[14].item[14].text = "MTQUALIFIED"
* item[14].item[14].type = #string
* item[14].item[15].linkId = "raw.rapid.mtqualified16hDefuse3"
* item[14].item[15].text = "MTQUALIFIED_16H_DEFUSE3"
* item[14].item[15].type = #string
* item[14].item[16].linkId = "raw.rapid.mtqualified6hExtendia"
* item[14].item[16].text = "MTQUALIFIED_6H_EXTENDIA"
* item[14].item[16].type = #string
* item[14].item[17].linkId = "raw.rapid.mtqualified6hSwiftprime"
* item[14].item[17].text = "MTQUALIFIED_6H_SWIFTPRIME"
* item[14].item[17].type = #string
