Instance: stroke-registry-response-evt-example
InstanceOf: StrokeRegistryResponse
Title: "腦中風 EVT 登錄主表回覆範例"
Description: "EVT 登錄主表已結案回覆範例，含正規化題目與部分原始值。本範例刻意示範時區確認前的寫法：authored 只填日期，時間以 StrokeEventTimeOnly 擴充附在 authored；原值保留在 raw.evt.administration.keyinDate。"
Usage: #example
* identifier.system = "http://www.vghks.gov.tw/evt-registry-id"
* identifier.value = "EVT-EXAMPLE-0001"
* status = #completed
* subject = Reference(Patient/stroke-patient-example)
* encounter = Reference(Encounter/stroke-encounter-example)
* authored = "2025-03-20"
* authored.extension[StrokeEventTimeOnly].valueTime = "14:30:00"
* author = Reference(Practitioner/stroke-practitioner-example)
* item[consent].text = "研究同意書簽署狀態"
* item[consent].answer.valueBoolean = true
* item[consentDate].text = "研究同意書簽署日期"
* item[consentDate].answer.valueDate = "2025-01-16"
* item[beforeEvtIvtpa].text = "EVT 前 IV-tPA 施打院所"
* item[beforeEvtIvtpa].answer.valueCoding = StrokePreEvtIvtpaSiteCS#1 "本院施打"
* item[dischargeTransferHospital].text = "離院轉入醫院"
* item[dischargeTransferHospital].answer.valueString = "範例復健醫院"
* item[rawEvt].text = "EVT 登錄原始值"
* item[rawEvt].item[0].linkId = "raw.evt.caseId"
* item[rawEvt].item[0].text = "EVT 登錄個案識別碼"
* item[rawEvt].item[0].answer.valueString = "EVT-EXAMPLE-0001"
* item[rawEvt].item[1].linkId = "raw.evt.demographics"
* item[rawEvt].item[1].text = "基本資料"
* item[rawEvt].item[1].item[0].linkId = "raw.evt.demographics.consent"
* item[rawEvt].item[1].item[0].text = "研究同意書簽署狀態"
* item[rawEvt].item[1].item[0].answer.valueString = "1"
* item[rawEvt].item[1].item[1].linkId = "raw.evt.demographics.consentDate"
* item[rawEvt].item[1].item[1].text = "研究同意書簽署日期"
* item[rawEvt].item[1].item[1].answer.valueString = "2025-01-16"
* item[rawEvt].item[2].linkId = "raw.evt.administration"
* item[rawEvt].item[2].text = "資料管理"
* item[rawEvt].item[2].item[0].linkId = "raw.evt.administration.edit"
* item[rawEvt].item[2].item[0].text = "主表登錄狀態"
* item[rawEvt].item[2].item[0].answer.valueString = "2"
* item[rawEvt].item[2].item[1].linkId = "raw.evt.administration.keyinDate"
* item[rawEvt].item[2].item[1].text = "資料登錄日期時間"
* item[rawEvt].item[2].item[1].answer.valueString = "2025-03-20 14:30:00"
* item[rawEvt].item[3].linkId = "raw.evt.discharge"
* item[rawEvt].item[3].text = "離院結果"
* item[rawEvt].item[3].item[0].linkId = "raw.evt.discharge.leavePlace"
* item[rawEvt].item[3].item[0].text = "離院去向"
* item[rawEvt].item[3].item[0].answer.valueString = "4"
* item[rawEvt].item[3].item[1].linkId = "raw.evt.discharge.leavePlaceHospital"
* item[rawEvt].item[3].item[1].text = "離院轉入醫院"
* item[rawEvt].item[3].item[1].answer.valueString = "範例復健醫院"
* item[rawEvt].item[4].linkId = "raw.evt.preEvt"
* item[rawEvt].item[4].text = "EVT 前評估與治療"
* item[rawEvt].item[4].item[0].linkId = "raw.evt.preEvt.beforeEvtIvtpa"
* item[rawEvt].item[4].item[0].text = "EVT 前 IV-tPA 施打醫院／未施打"
* item[rawEvt].item[4].item[0].answer.valueString = "1"

Instance: stroke-registry-response-rapid-example
InstanceOf: StrokeRegistryResponse
Title: "腦中風 RAPID 影像分析回覆範例"
Description: "RAPID 影像分析回覆範例。來源沒有表單狀態，status 填 in-progress；沒有登錄時間，authored 以 data-absent-reason 表示。"
Usage: #example
* status = #in-progress
* subject = Reference(Patient/stroke-patient-example)
* authored.extension[dataAbsentReason].valueCode = #unknown
* item[rapidRequestNo].text = "RAPID 影像申請序號"
* item[rapidRequestNo].answer.valueString = "REQ-EXAMPLE-0001"
* item[rawRapid].text = "RAPID 原始值"
* item[rawRapid].item[0].linkId = "raw.rapid.rpreqno"
* item[rawRapid].item[0].text = "申請序號"
* item[rawRapid].item[0].answer.valueString = "REQ-EXAMPLE-0001"
* item[rawRapid].item[1].linkId = "raw.rapid.scantype"
* item[rawRapid].item[1].text = "掃描類型"
* item[rawRapid].item[1].answer.valueString = "CTP"
* item[rawRapid].item[2].linkId = "raw.rapid.aspects"
* item[rawRapid].item[2].text = "ASPECTS 分數"
* item[rawRapid].item[2].answer.valueString = "8"
* item[rawRapid].item[3].linkId = "raw.rapid.cbfVolume"
* item[rawRapid].item[3].text = "CBF<30% 體積"
* item[rawRapid].item[3].answer.valueString = "0"
* item[rawRapid].item[4].linkId = "raw.rapid.tmaxVolume"
* item[rawRapid].item[4].text = "Tmax>6 秒體積"
* item[rawRapid].item[4].answer.valueString = "85"
* item[rawRapid].item[5].linkId = "raw.rapid.mismatchRatio"
* item[rawRapid].item[5].text = "不一致比率"
* item[rawRapid].item[5].answer.valueString = "9999"
* item[rawRapid].item[6].linkId = "raw.rapid.hid"
* item[rawRapid].item[6].text = "醫院代號"
* item[rawRapid].item[6].answer.valueString = "1A0"
