Logical: StrokeCaseManagementLM
Id: StrokeCaseManagementLM
Title: "腦中風個管系統資料邏輯模型"
Description: "高雄榮總腦中風個管系統（NCVA）資料交換邏輯模型。依交換譯碼簿整理 14 個資料表。每個個案以病歷號（HISNUMMARK）加個管流水序號（CMSEQNO）識別，各資料表以這兩欄串接。"
* ^status = #draft
* hisnummark 1..1 Identifier "病歷號" "病人在本院的病歷號。分析樣本已去識別化，正式環境為可識別的病歷號。病人與個管事件分開識別。"
* cmseqno 1..1 Identifier "個管流水序號" "個管事件流水序號。同一病人可有多個個管事件，需與病歷號搭配使用。"
* caseMain 1..1 BackboneElement "腦中風個案主檔" "個案基本資料、發病、到院與離院資訊，每個個案一筆。"
  * occdate 0..1 date "發病日期" "發病日期，格式 YYYY-MM-DD。"
  * occtime 0..1 time "發生時間" "發生時間，格式 hh:mm。"
  * arrdate 0..1 date "到院日期" "到院日期，格式 YYYY-MM-DD。"
  * arrtime 0..1 time "到院時間" "到院時間，格式 hh:mm。"
  * hdisdt 0..1 date "病患離院日期" "病患離院日期，格式 YYYY-MM-DD。"
  * psex 0..1 code "病患性別" "病患性別：M＝男性；F＝女性。"
  * hage 0..1 integer "病患年齡" "病患年齡，單位為歲。"
  * height 0..1 decimal "病患身高" "病患身高，單位為 cm。"
  * weight 0..1 decimal "病患體重" "病患體重，單位為 kg。"
  * edulevelcode 0..1 code "病患教育程度代碼" "病患教育程度代碼：EDU00＝無；EDU01＝小學；EDU02＝國中；EDU03＝高中職；EDU04＝大專；EDU05＝研究所；EDU99＝不詳。"
  * ocpcode 0..1 code "職業選項代碼" "職業選項代碼：OCP00＝無；OCP01＝軍；OCP02＝公；OCP03＝教；OCP04＝工；OCP05＝農；OCP06＝商；OCP07＝服務業；OCP08＝學生；OCP09＝退休；OCP99＝其他。"
  * patfrom 0..1 code "入院方式" "入院方式：A＝住院；E＝急診；O＝門診。"
  * reachwaycode 0..1 code "到院方式代碼" "到院方式代碼：SELF＝自行前往；EMG＝使用消防局緊急醫療系統；TRAN＝他院轉入；NONE＝無。"
  * levoption 0..1 code "離院情形代碼" "離院情形代碼：LEV01＝病危自動出院；LEV02＝死亡；LEV03＝出院；LEV05＝轉 PAC。"
* comaScale 0..1 BackboneElement "昏迷指數與生命徵象" "到院時的 GCS、生命徵象與中風診斷分類，每個個案一筆。實際檔案比譯碼簿多一欄。"
  * gcsM 0..1 integer "GCS 動作反應" "GCS 動作反應分數。"
  * gcsE 0..1 integer "GCS 睜眼反應" "GCS 睜眼反應分數。"
  * gcsV 0..1 integer "GCS 語言反應" "GCS 語言反應分數。"
  * sbp 0..1 integer "收縮壓" "收縮壓，單位為 mmHg。"
  * dbp 0..1 integer "舒張壓" "舒張壓，單位為 mmHg。"
  * bt 0..1 decimal "體溫" "體溫，單位為 °C。"
  * hr 0..1 integer "心跳" "心跳，單位為次／分。"
  * rr 0..1 integer "呼吸" "呼吸，單位為次／分。"
  * icd10 0..1 code "ICD-10 診斷碼" "中風診斷的 ICD-10 代碼。"
  * infarct 0..1 code "腦梗塞" "是否為腦梗塞，譯碼簿未定義值域。"
  * stkdiagnosisoption1 0..1 string "TOAST 分類" "缺血性中風 TOAST 分類，以文字儲存。可填：Large artery atherosclerosis；Small vessel occlusion；Cardioembolism；Specific etiology；Undertermined etiology。"
  * stkdiagnosisoption2 0..1 string "TOAST 次分類" "TOAST 次分類，以文字儲存。可填：Extra；Intra；Cerebral venous thrombosis；Moyamoya Synd；Radiation；Dissection；Migraine；Antiphospholipid Ab Synd；Autoummune disease；Hyperfibrinogenemia；Prot C/Prot S deficiency；Antithrombin III deficiency；Homocystinuria；Hypercoagulable state；Cancer；其他；Incomplete Study；Conflict data；Complete Study。"
  * tia 0..1 code "短暫性腦缺血" "短暫性腦缺血：0＝無；1＝有。"
  * ich 0..1 code "腦出血" "腦出血：0＝無；1＝有。"
  * sah 0..1 code "蜘蛛網膜下腔出血" "蜘蛛網膜下腔出血：0＝無；1＝有。"
  * stkdiagnosisoption3 0..1 string "TIA／ICH／SAH 次分類" "TIA、ICH 或 SAH 的次分類，以文字儲存。可填：Carotid；VB；Hypertensive；Non-Hypertensive；aneurysm；Angio negative；未做 Angio；其他。"
  * unnamedCol19 0..1 string "未命名欄位（第 19 欄）" "實際檔案多出的欄位，譯碼簿沒有對應欄序，原值照存。"
* nihss 0..* BackboneElement "NIHSS 評估" "NIHSS 各項分數，每次評估一筆，以 freqno 區分入院或出院。"
  * freqno 1..1 integer "評估次數" "評估次數：1＝入院；2＝出院。"
  * oneA 0..1 integer "1a 意識程度" "NIHSS 1a 意識程度分數。"
  * oneB 0..1 integer "1b 意識提問" "NIHSS 1b 意識提問分數。"
  * oneC 0..1 integer "1c 意識指令" "NIHSS 1c 意識指令分數。"
  * two 0..1 integer "2 眼球運動" "NIHSS 2 眼球運動分數。"
  * three 0..1 integer "3 視野" "NIHSS 3 視野分數。"
  * four 0..1 integer "4 顏面麻痺" "NIHSS 4 顏面麻痺分數。"
  * fiveAl 0..1 integer "5a 左上肢運動" "NIHSS 5a 左上肢運動分數。"
  * fiveBr 0..1 integer "5b 右上肢運動" "NIHSS 5b 右上肢運動分數。"
  * sixAl 0..1 integer "6a 左下肢運動" "NIHSS 6a 左下肢運動分數。"
  * sixBr 0..1 integer "6b 右下肢運動" "NIHSS 6b 右下肢運動分數。"
  * seven 0..1 integer "7 肢體運動失調" "NIHSS 7 肢體運動失調分數。"
  * eight 0..1 integer "8 感覺" "NIHSS 8 感覺分數。"
  * nine 0..1 integer "9 語言" "NIHSS 9 語言分數。"
  * ten 0..1 integer "10 構音障礙" "NIHSS 10 構音障礙分數。"
  * eleven 0..1 integer "11 忽略" "NIHSS 11 忽略分數。"
  * total 0..1 integer "NIHSS 總分" "NIHSS 總分，為 1a 至 11 各項加總。"
  * inpdate 0..1 date "評估日期" "評估日期，格式 YYYY-MM-DD。"
  * inptime 0..1 time "評估時間" "評估時間，格式 hh:mm。"
  * arrdate 0..1 date "入院日期" "入院日期，格式 YYYY-MM-DD。"
  * hdisdt 0..1 date "離院日期" "離院日期，格式 YYYY-MM-DD。"
* mrs 0..* BackboneElement "mRS 評估" "mRS 分數，每次評估一筆，以 freqno 區分評估次數。實際檔案比譯碼簿多兩欄。"
  * freqno 1..1 integer "評估次數" "評估次數。譯碼簿定義 1＝出院；2＝發病後 3 個月。實際資料有 1 至 9。"
  * mrsrate 0..1 integer "mRS 分數" "mRS 分數。"
  * inpdate 0..1 date "評估日期" "評估日期，格式 YYYY-MM-DD。譯碼簿取值規則：出院評估取出院日前後 3 天內，3 個月評估取發病日起第 76 至 104 天內；區間內有多筆時取最後一筆。"
  * unnamedCol06 0..1 string "未命名欄位（第 6 欄）" "實際檔案多出的欄位，譯碼簿沒有對應欄序，原值照存。"
  * unnamedCol07 0..1 string "未命名欄位（第 7 欄）" "實際檔案多出的欄位，譯碼簿沒有對應欄序，原值照存。"
* ich 0..1 BackboneElement "ICH 分數" "腦出血個案的 ICH 分數，每個個案一筆。"
  * ichScore 0..1 string "ICH 分數" "ICH 分數，譯碼簿未定義值域。"
  * formdt 0..1 date "評估日期" "評估日期，格式 YYYY-MM-DD。"
* hhs 0..1 BackboneElement "Hunt and Hess 分級" "蜘蛛網膜下腔出血個案的 Hunt and Hess 分級，每個個案一筆。"
  * hlsGrade 0..1 string "Hunt and Hess 分級" "Hunt and Hess 分級，譯碼簿未定義值域。"
  * formdt 0..1 date "評估日期" "評估日期，格式 YYYY-MM-DD。"
* heartDisease 0..1 BackboneElement "心臟疾病" "個案的心臟疾病史，每個個案一筆。各項填 0＝無；1＝有。"
  * thd01 0..1 code "心房顫動" "是否有心房顫動：0＝無；1＝有。"
  * thd02 0..1 code "其他缺血性心臟病" "是否有其他缺血性心臟病（含 CAD 及陳舊性心肌梗塞）：0＝無；1＝有。"
  * thd03 0..1 code "瓣膜置換" "是否有瓣膜置換：0＝無；1＝有。"
  * thd04 0..1 code "心內膜炎" "是否有心內膜炎：0＝無；1＝有。"
  * thd05 0..1 code "心臟黏液瘤" "是否有心臟黏液瘤：0＝無；1＝有。"
  * thd06 0..1 code "心衰竭" "是否有心衰竭：0＝無；1＝有。"
  * thd07 0..1 code "4 週內急性心肌梗塞" "是否有 4 週內急性心肌梗塞：0＝無；1＝有。"
  * thd08 0..1 code "風濕性心臟病" "是否有風濕性心臟病：0＝無；1＝有。"
  * thd09 0..1 code "開放性卵圓孔" "是否有開放性卵圓孔：0＝無；1＝有。"
* treatment 0..1 BackboneElement "住院治療" "住院期間的用藥與處置，每個個案一筆。各項填 0＝無；1＝有。"
  * tre01 0..1 code "Aggrenox" "住院期間是否使用 Aggrenox：0＝無；1＝有。藥物有多個時間點時，以住院期間為準。"
  * tre02 0..1 code "Aspirin" "住院期間是否使用 Aspirin：0＝無；1＝有。"
  * tre03 0..1 code "Ticlopidine" "住院期間是否使用 Ticlopidine：0＝無；1＝有。"
  * tre05 0..1 code "Warfarin" "住院期間是否使用 Warfarin：0＝無；1＝有。"
  * tre06 0..1 code "動脈內取栓" "住院期間是否執行動脈內取栓：0＝無；1＝有。"
  * tre07 0..1 code "導尿管" "住院期間是否留置導尿管：0＝無；1＝有。"
  * tre09 0..1 code "簽署 DNR" "住院期間是否簽署 DNR：0＝無；1＝有。"
  * tre10 0..1 code "復健" "住院期間是否接受復健：0＝無；1＝有。"
  * tre13 0..1 code "Clopidogrel" "住院期間是否使用 Clopidogrel：0＝無；1＝有。"
  * tre14 0..1 code "Pletaal" "住院期間是否使用 Pletaal：0＝無；1＝有。"
  * tre15 0..1 code "低分子量肝素" "住院期間是否使用低分子量肝素：0＝無；1＝有。"
  * tre16 0..1 code "靜脈 t-PA" "住院期間是否使用靜脈 t-PA：0＝無；1＝有。"
  * tre17 0..1 code "呼吸器" "住院期間是否使用呼吸器：0＝無；1＝有。"
  * tre18 0..1 code "鼻胃管" "住院期間是否留置鼻胃管：0＝無；1＝有。"
  * tre19 0..1 code "吞嚥篩檢" "住院期間是否執行吞嚥篩檢：0＝無；1＝有。"
  * tre20 0..1 code "入住加護病房" "住院期間是否入住加護病房：0＝無；1＝有。"
  * tre21 0..1 code "戒菸衛教" "住院期間是否接受戒菸衛教：0＝無；1＝有。"
  * tre22 0..1 code "中風衛教" "住院期間是否接受中風衛教：0＝無；1＝有。"
  * tre23 0..1 code "手術治療" "住院期間是否接受手術治療：0＝無；1＝有。"
  * tre27 0..1 code "Apixaban" "住院期間是否使用 Apixaban：0＝無；1＝有。"
  * tre28 0..1 code "Dabigatran" "住院期間是否使用 Dabigatran：0＝無；1＝有。"
  * tre29 0..1 code "Edoxaban" "住院期間是否使用 Edoxaban：0＝無；1＝有。"
  * tre30 0..1 code "Rivaroxaban" "住院期間是否使用 Rivaroxaban：0＝無；1＝有。"
  * tre31 0..1 code "Ticagrelor" "住院期間是否使用 Ticagrelor：0＝無；1＝有。"
* dischargeDrug 0..1 BackboneElement "出院帶藥" "出院時的用藥，每個個案一筆。各項填 0＝無；1＝有。"
  * drg01 0..1 code "Aspirin" "出院時是否使用 Aspirin：0＝無；1＝有。"
  * drg02 0..1 code "Aggrenox" "出院時是否使用 Aggrenox：0＝無；1＝有。"
  * drg03 0..1 code "Ticlopidine" "出院時是否使用 Ticlopidine：0＝無；1＝有。"
  * drg04 0..1 code "Clopidogrel" "出院時是否使用 Clopidogrel：0＝無；1＝有。"
  * drg05 0..1 code "Pletaal" "出院時是否使用 Pletaal：0＝無；1＝有。"
  * drg06 0..1 code "降血壓藥" "出院時是否使用降血壓藥：0＝無；1＝有。"
  * drg07 0..1 code "Warfarin" "出院時是否使用 Warfarin：0＝無；1＝有。"
  * drg08 0..1 code "糖尿病藥" "出院時是否使用糖尿病藥：0＝無；1＝有。"
  * sub01 0..1 code "口服降血糖藥" "出院時是否使用口服降血糖藥：0＝無；1＝有。"
  * sub02 0..1 code "胰島素" "出院時是否使用胰島素：0＝無；1＝有。"
  * sub03 0..1 code "statin 類降血脂藥" "出院時是否使用 statin 類降血脂藥：0＝無；1＝有。"
  * sub04 0..1 code "非 statin 類降血脂藥" "出院時是否使用非 statin 類降血脂藥：0＝無；1＝有。部分院所以 FIBRATE 欄記錄，1＝有，空白＝沒有。"
  * drg12 0..1 code "Apixaban" "出院時是否使用 Apixaban：0＝無；1＝有。"
  * drg13 0..1 code "Dabigatran" "出院時是否使用 Dabigatran：0＝無；1＝有。"
  * drg14 0..1 code "Edoxaban" "出院時是否使用 Edoxaban：0＝無；1＝有。"
  * drg15 0..1 code "Rivaroxaban" "出院時是否使用 Rivaroxaban：0＝無；1＝有。"
  * drg16 0..1 code "Ticagrelor" "出院時是否使用 Ticagrelor：0＝無；1＝有。"
* deterioration 0..1 BackboneElement "惡化原因" "住院期間的神經學惡化原因，每個個案一筆。各項填 0＝無；1＝有。"
  * det01 0..1 code "中風惡化" "惡化原因是否為中風惡化：0＝無；1＝有。"
  * det02 0..1 code "腦疝脫" "惡化原因是否為腦疝脫：0＝無；1＝有。"
  * det03 0..1 code "36 小時內出血性梗塞" "惡化原因是否為 36 小時內出血性梗塞：0＝無；1＝有。"
  * det04 0..1 code "血腫擴大" "惡化原因是否為血腫擴大：0＝無；1＝有。"
  * det05 0..1 code "血管痙攣" "惡化原因是否為血管痙攣：0＝無；1＝有。"
  * det06 0..1 code "再出血" "惡化原因是否為再出血：0＝無；1＝有。"
  * det07 0..1 code "內科問題" "惡化原因是否為內科問題：0＝無；1＝有。"
* riskFactor 0..1 BackboneElement "危險因子" "個案的中風危險因子，每個個案一筆。"
  * ht 0..1 code "高血壓" "是否有高血壓危險因子：0＝無；1＝有。"
  * htcurrent 0..1 code "本次新診斷高血壓" "高血壓是否為本次住院才診斷：0＝無；1＝有。"
  * previoustia 0..1 code "既往短暫性腦缺血" "是否有既往短暫性腦缺血危險因子：0＝無；1＝有。"
  * cancer 0..1 code "癌症" "是否有癌症危險因子：0＝無；1＝有。"
  * hypercholesterolemia 0..1 code "高膽固醇" "是否有高膽固醇危險因子：0＝無；1＝有。"
  * smoking 0..1 code "吸菸" "是否有吸菸危險因子：0＝無；1＝有。"
  * smokingtiming 0..1 code "吸菸狀態" "吸菸狀態：Past＝過去吸菸；Current＝目前吸菸。"
  * smokingquantity 0..1 integer "每日吸菸量" "每日吸菸量，單位為支。"
  * smokingyears 0..1 integer "吸菸年數" "吸菸年數，單位為年。"
  * heartdisease 0..1 code "心臟病" "是否有心臟病危險因子：0＝無；1＝有。"
  * pad 0..1 code "周邊動脈疾病" "是否有周邊動脈疾病危險因子：0＝無；1＝有。"
  * dm 0..1 code "糖尿病" "是否有糖尿病危險因子：0＝無；1＝有。"
  * dmcurrent 0..1 code "本次新診斷糖尿病" "糖尿病是否為本次住院才診斷：0＝無；1＝有。"
  * alcohol 0..1 code "飲酒" "是否有飲酒危險因子：0＝無；1＝有。"
  * hypertriglyceridemia 0..1 code "高三酸甘油脂" "是否有高三酸甘油脂危險因子：0＝無；1＝有。"
  * polycythemia 0..1 code "紅血球增多症" "是否有紅血球增多症危險因子：0＝無；1＝有。"
  * uremia 0..1 code "尿毒症" "是否有尿毒症危險因子：0＝無；1＝有。"
  * previousci 0..1 code "既往腦梗塞" "是否有既往腦梗塞危險因子：0＝無；1＝有。"
  * previousch 0..1 code "既往腦出血" "是否有既往腦出血危險因子：0＝無；1＝有。"
* familyHistory 0..1 BackboneElement "家族病史" "個案的家族病史，每個個案一筆。各項填 0＝無；1＝有；2＝不知道。"
  * isHbr 0..1 code "高血壓家族史" "家族是否有高血壓：0＝無；1＝有；2＝不知道。"
  * isDm 0..1 code "糖尿病家族史" "家族是否有糖尿病：0＝無；1＝有；2＝不知道。"
  * isIhd 0..1 code "缺血性心臟病家族史" "家族是否有缺血性心臟病：0＝無；1＝有；2＝不知道。"
  * isTia 0..1 code "中風或短暫性腦缺血家族史" "家族是否有中風或短暫性腦缺血：0＝無；1＝有；2＝不知道。"
* examResult 0..1 BackboneElement "檢驗結果" "心電圖與抽血檢驗結果，每個個案一筆。譯碼簿未列檢驗單位。"
  * ecgOption 0..1 code "心電圖心房顫動" "心電圖是否為心房顫動：0＝不是 Af；1＝Af。"
  * hb 0..1 Quantity "血紅素" "血紅素檢驗值，來源以文字儲存，未列單位。"
  * hct 0..1 Quantity "血比容" "血比容檢驗值，來源以文字儲存，未列單位。"
  * platelet 0..1 Quantity "血小板" "血小板檢驗值，來源以文字儲存，未列單位。"
  * wbc 0..1 Quantity "白血球" "白血球檢驗值，來源以文字儲存，未列單位。"
  * ptt 0..1 Quantity "部分凝血活酶時間" "部分凝血活酶時間檢驗值，來源以文字儲存，未列單位。"
  * pttControl 0..1 Quantity "PTT 對照值" "PTT 對照值檢驗值，來源以文字儲存，未列單位。"
  * ptInr 0..1 Quantity "凝血酶原時間 INR" "凝血酶原時間 INR 檢驗值，來源以文字儲存，未列單位。"
  * glucoseEr 0..1 Quantity "急診血糖" "急診血糖檢驗值，來源以文字儲存，未列單位。"
  * bun 0..1 Quantity "血中尿素氮" "血中尿素氮檢驗值，來源以文字儲存，未列單位。"
  * creatinine 0..1 Quantity "肌酸酐" "肌酸酐檢驗值，來源以文字儲存，未列單位。"
  * albumin 0..1 Quantity "白蛋白" "白蛋白檢驗值，來源以文字儲存，未列單位。"
  * crp 0..1 Quantity "C 反應蛋白" "C 反應蛋白檢驗值，來源以文字儲存，未列單位。"
  * hba1c 0..1 Quantity "糖化血色素" "糖化血色素檢驗值，來源以文字儲存，未列單位。"
  * gluAc 0..1 Quantity "空腹血糖" "空腹血糖檢驗值，來源以文字儲存，未列單位。"
  * ua 0..1 Quantity "UA" "UA 檢驗值，譯碼簿未說明是尿酸還是尿液檢查。"
  * tCho 0..1 Quantity "總膽固醇" "總膽固醇檢驗值，來源以文字儲存，未列單位。"
  * tg 0..1 Quantity "三酸甘油脂" "三酸甘油脂檢驗值，來源以文字儲存，未列單位。"
  * hdl 0..1 Quantity "高密度脂蛋白膽固醇" "高密度脂蛋白膽固醇檢驗值，來源以文字儲存，未列單位。"
  * ldl 0..1 Quantity "低密度脂蛋白膽固醇" "低密度脂蛋白膽固醇檢驗值，來源以文字儲存，未列單位。"
  * got 0..1 Quantity "AST／GOT" "AST／GOT 檢驗值，來源以文字儲存，未列單位。"
  * gpt 0..1 Quantity "ALT／GPT" "ALT／GPT 檢驗值，來源以文字儲存，未列單位。"
* timesheet 0..1 BackboneElement "腦中風個管時間表" "影像、靜脈血栓溶解、轉住院、動脈穿刺與再灌流的時間點，每個個案一筆。"
  * ctmridate 0..1 date "第一次 CT/MRI 日期" "第一次 CT/MRI 日期，格式 YYYY-MM-DD。"
  * ctmritime 0..1 time "第一次 CT/MRI 時間" "第一次 CT/MRI 時間，格式 hh:mm。"
  * isctmrifromoutside 0..1 code "CT/MRI 是否為外片" "第一次 CT／MRI 是否為外院影像：0＝無；1＝有。"
  * ivtpadate 0..1 date "執行 IVtPA 日期" "執行 IVtPA 日期，格式 YYYY-MM-DD。"
  * ivtpatime 0..1 time "執行 IVtPA 時間" "執行 IVtPA 時間，格式 hh:mm。"
  * ivtpareason 0..1 code "未執行 IVtPA 主要原因" "未執行靜脈血栓溶解的主要原因：REA01＝輸注本藥前，急性缺血性中風發作時間已超過 3 小時，或症狀發作時間不明；REA02＝發作至到院 2 小時內，但不符合施打條件；REA03＝發作至到院 2 至 3 小時內，但不符合施打條件。"
  * ivtpasub01 0..1 code "未執行 IVtPA 次要原因 1" "未執行 IVtPA 次要原因 1：0＝無；1＝輸注本藥前，缺血性腦中風發作的時間已經超過 3 小時。"
  * ivtpasub02 0..1 code "未執行 IVtPA 次要原因 2" "未執行 IVtPA 次要原因 2：0＝無；1＝輸注本藥前，急性缺血性腦中風的症狀已迅速改善或症狀輕微(如 NIHSS<4)。"
  * ivtpasub03 0..1 code "未執行 IVtPA 次要原因 3" "未執行 IVtPA 次要原因 3：0＝無；1＝臨床或影像判定為嚴重之中風(如 NIHSS > 25)。"
  * ivtpasub04 0..1 code "未執行 IVtPA 次要原因 4" "未執行 IVtPA 次要原因 4：0＝無；1＝年齡在 18 歲以下，或 80 歲以上。"
  * ivtpasub05 0..1 code "未執行 IVtPA 次要原因 5" "未執行 IVtPA 次要原因 5：0＝無；1＝過去曾中風且合併糖尿病。"
  * ivtpasub06 0..1 code "未執行 IVtPA 次要原因 6" "未執行 IVtPA 次要原因 6：0＝無；1＝收縮壓>185mmHg 或舒張壓>110mmHg。"
  * ivtpasub07 0..1 code "未執行 IVtPA 次要原因 7" "未執行 IVtPA 次要原因 7：0＝無；1＝最近 3 個月內有中風病史或有嚴重性頭部創傷。"
  * ivtpasub08 0..1 code "未執行 IVtPA 次要原因 8" "未執行 IVtPA 次要原因 8：0＝無；1＝中風發作時併發癲癇。"
  * ivtpasub09 0..1 code "未執行 IVtPA 次要原因 9" "未執行 IVtPA 次要原因 9：0＝無；1＝病人正接受口服抗凝血劑，如 warfarin sodium(INR>1.3)。"
  * ivtpasub10 0..1 code "未執行 IVtPA 次要原因 10" "未執行 IVtPA 次要原因 10：0＝無；1＝家屬拒絕。"
  * ivtpadoze 0..1 integer "IV-tPA 劑量" "IV-tPA 劑量，譯碼簿未列單位。"
  * hadmdt 0..1 date "轉住院日期" "轉住院日期，格式 YYYY-MM-DD。"
  * ctadate 0..1 date "CTA 日期" "CTA 日期，格式 YYYY-MM-DD。"
  * ctatime 0..1 time "CTA 時間" "CTA 時間，格式 hh:mm。"
  * puncturedt 0..1 date "動脈穿刺日期" "動脈穿刺日期，格式 YYYY-MM-DD。"
  * puncturetm 0..1 time "動脈穿刺時間" "動脈穿刺時間，格式 hh:mm。"
  * perfusiondta 0..1 date "再灌流日期" "再灌流日期，格式 YYYY-MM-DD。"
  * perfusiontma 0..1 time "再灌流時間" "再灌流時間，格式 hh:mm。"

Mapping: StrokeCaseManagementLMToNCVA
Source: StrokeCaseManagementLM
Target: "urn:vgh-stroke:source:ncva"
Description: "對照 NCVA 腦中風個管系統交換譯碼簿的原始欄位。"
Id: ncva-source
Title: "個管系統原始欄位對照"
* -> "NCVA"
* hisnummark -> "NCVA.*.HISNUMMARK" "各資料表皆有此欄"
* cmseqno -> "NCVA.*.CMSEQNO" "各資料表皆有此欄"
* caseMain -> "NCVA.CASEMAIN"
* caseMain.occdate -> "NCVA.CASEMAIN.OCCDATE"
* caseMain.occtime -> "NCVA.CASEMAIN.OCCTIME"
* caseMain.arrdate -> "NCVA.CASEMAIN.ARRDATE"
* caseMain.arrtime -> "NCVA.CASEMAIN.ARRTIME"
* caseMain.hdisdt -> "NCVA.CASEMAIN.HDISDT"
* caseMain.psex -> "NCVA.CASEMAIN.PSEX"
* caseMain.hage -> "NCVA.CASEMAIN.HAGE"
* caseMain.height -> "NCVA.CASEMAIN.HEIGHT"
* caseMain.weight -> "NCVA.CASEMAIN.WEIGHT"
* caseMain.edulevelcode -> "NCVA.CASEMAIN.EDULEVELCODE"
* caseMain.ocpcode -> "NCVA.CASEMAIN.OCPCODE"
* caseMain.patfrom -> "NCVA.CASEMAIN.PATFROM"
* caseMain.reachwaycode -> "NCVA.CASEMAIN.REACHWAYCODE"
* caseMain.levoption -> "NCVA.CASEMAIN.LEVOPTION"
* comaScale -> "NCVA.COMASCALE"
* comaScale.gcsM -> "NCVA.COMASCALE.GCS_M"
* comaScale.gcsE -> "NCVA.COMASCALE.GCS_E"
* comaScale.gcsV -> "NCVA.COMASCALE.GCS_V"
* comaScale.sbp -> "NCVA.COMASCALE.SBP"
* comaScale.dbp -> "NCVA.COMASCALE.DBP"
* comaScale.bt -> "NCVA.COMASCALE.BT"
* comaScale.hr -> "NCVA.COMASCALE.HR"
* comaScale.rr -> "NCVA.COMASCALE.RR"
* comaScale.icd10 -> "NCVA.COMASCALE.ICD10"
* comaScale.infarct -> "NCVA.COMASCALE.Infarct"
* comaScale.stkdiagnosisoption1 -> "NCVA.COMASCALE.STKDIAGNOSISOPTION1"
* comaScale.stkdiagnosisoption2 -> "NCVA.COMASCALE.STKDIAGNOSISOPTION2"
* comaScale.tia -> "NCVA.COMASCALE.TIA"
* comaScale.ich -> "NCVA.COMASCALE.ICH"
* comaScale.sah -> "NCVA.COMASCALE.SAH"
* comaScale.stkdiagnosisoption3 -> "NCVA.COMASCALE.STKDIAGNOSISOPTION3"
* comaScale.unnamedCol19 -> "NCVA.COMASCALE.UNNAMED_COL_19"
* nihss -> "NCVA.NIHSS"
* nihss.freqno -> "NCVA.NIHSS.FREQNO"
* nihss.oneA -> "NCVA.NIHSS.ONE_A"
* nihss.oneB -> "NCVA.NIHSS.ONE_B"
* nihss.oneC -> "NCVA.NIHSS.ONE_C"
* nihss.two -> "NCVA.NIHSS.TWO"
* nihss.three -> "NCVA.NIHSS.THREE"
* nihss.four -> "NCVA.NIHSS.FOUR"
* nihss.fiveAl -> "NCVA.NIHSS.FIVE_AL"
* nihss.fiveBr -> "NCVA.NIHSS.FIVE_BR"
* nihss.sixAl -> "NCVA.NIHSS.SIX_AL"
* nihss.sixBr -> "NCVA.NIHSS.SIX_BR"
* nihss.seven -> "NCVA.NIHSS.SEVEN"
* nihss.eight -> "NCVA.NIHSS.EIGHT"
* nihss.nine -> "NCVA.NIHSS.NINE"
* nihss.ten -> "NCVA.NIHSS.TEN"
* nihss.eleven -> "NCVA.NIHSS.ELEVEN"
* nihss.total -> "NCVA.NIHSS.TOTAL"
* nihss.inpdate -> "NCVA.NIHSS.INPDATE"
* nihss.inptime -> "NCVA.NIHSS.INPTIME"
* nihss.arrdate -> "NCVA.NIHSS.ARRDATE"
* nihss.hdisdt -> "NCVA.NIHSS.HDISDT"
* mrs -> "NCVA.mRS"
* mrs.freqno -> "NCVA.mRS.FREQNO"
* mrs.mrsrate -> "NCVA.mRS.MRSRATE"
* mrs.inpdate -> "NCVA.mRS.INPDATE"
* mrs.unnamedCol06 -> "NCVA.mRS.UNNAMED_COL_06"
* mrs.unnamedCol07 -> "NCVA.mRS.UNNAMED_COL_07"
* ich -> "NCVA.ICH"
* ich.ichScore -> "NCVA.ICH.ichScore"
* ich.formdt -> "NCVA.ICH.FORMDT"
* hhs -> "NCVA.HHS"
* hhs.hlsGrade -> "NCVA.HHS.hlsGrade"
* hhs.formdt -> "NCVA.HHS.FORMDT"
* heartDisease -> "NCVA.HEARTDIS"
* heartDisease.thd01 -> "NCVA.HEARTDIS.THD01"
* heartDisease.thd02 -> "NCVA.HEARTDIS.THD02"
* heartDisease.thd03 -> "NCVA.HEARTDIS.THD03"
* heartDisease.thd04 -> "NCVA.HEARTDIS.THD04"
* heartDisease.thd05 -> "NCVA.HEARTDIS.THD05"
* heartDisease.thd06 -> "NCVA.HEARTDIS.THD06"
* heartDisease.thd07 -> "NCVA.HEARTDIS.THD07"
* heartDisease.thd08 -> "NCVA.HEARTDIS.THD08"
* heartDisease.thd09 -> "NCVA.HEARTDIS.THD09"
* treatment -> "NCVA.TREATMENT"
* treatment.tre01 -> "NCVA.TREATMENT.TRE01"
* treatment.tre02 -> "NCVA.TREATMENT.TRE02"
* treatment.tre03 -> "NCVA.TREATMENT.TRE03"
* treatment.tre05 -> "NCVA.TREATMENT.TRE05"
* treatment.tre06 -> "NCVA.TREATMENT.TRE06"
* treatment.tre07 -> "NCVA.TREATMENT.TRE07"
* treatment.tre09 -> "NCVA.TREATMENT.TRE09"
* treatment.tre10 -> "NCVA.TREATMENT.TRE10"
* treatment.tre13 -> "NCVA.TREATMENT.TRE13"
* treatment.tre14 -> "NCVA.TREATMENT.TRE14"
* treatment.tre15 -> "NCVA.TREATMENT.TRE15"
* treatment.tre16 -> "NCVA.TREATMENT.TRE16"
* treatment.tre17 -> "NCVA.TREATMENT.TRE17"
* treatment.tre18 -> "NCVA.TREATMENT.TRE18"
* treatment.tre19 -> "NCVA.TREATMENT.TRE19"
* treatment.tre20 -> "NCVA.TREATMENT.TRE20"
* treatment.tre21 -> "NCVA.TREATMENT.TRE21"
* treatment.tre22 -> "NCVA.TREATMENT.TRE22"
* treatment.tre23 -> "NCVA.TREATMENT.TRE23"
* treatment.tre27 -> "NCVA.TREATMENT.TRE27"
* treatment.tre28 -> "NCVA.TREATMENT.TRE28"
* treatment.tre29 -> "NCVA.TREATMENT.TRE29"
* treatment.tre30 -> "NCVA.TREATMENT.TRE30"
* treatment.tre31 -> "NCVA.TREATMENT.TRE31"
* dischargeDrug -> "NCVA.DISCHG_DRUG"
* dischargeDrug.drg01 -> "NCVA.DISCHG_DRUG.DRG01"
* dischargeDrug.drg02 -> "NCVA.DISCHG_DRUG.DRG02"
* dischargeDrug.drg03 -> "NCVA.DISCHG_DRUG.DRG03"
* dischargeDrug.drg04 -> "NCVA.DISCHG_DRUG.DRG04"
* dischargeDrug.drg05 -> "NCVA.DISCHG_DRUG.DRG05"
* dischargeDrug.drg06 -> "NCVA.DISCHG_DRUG.DRG06"
* dischargeDrug.drg07 -> "NCVA.DISCHG_DRUG.DRG07"
* dischargeDrug.drg08 -> "NCVA.DISCHG_DRUG.DRG08"
* dischargeDrug.sub01 -> "NCVA.DISCHG_DRUG.SUB01"
* dischargeDrug.sub02 -> "NCVA.DISCHG_DRUG.SUB02"
* dischargeDrug.sub03 -> "NCVA.DISCHG_DRUG.SUB03"
* dischargeDrug.sub04 -> "NCVA.DISCHG_DRUG.SUB04"
* dischargeDrug.drg12 -> "NCVA.DISCHG_DRUG.DRG12"
* dischargeDrug.drg13 -> "NCVA.DISCHG_DRUG.DRG13"
* dischargeDrug.drg14 -> "NCVA.DISCHG_DRUG.DRG14"
* dischargeDrug.drg15 -> "NCVA.DISCHG_DRUG.DRG15"
* dischargeDrug.drg16 -> "NCVA.DISCHG_DRUG.DRG16"
* deterioration -> "NCVA.DETERIORATION"
* deterioration.det01 -> "NCVA.DETERIORATION.DET01"
* deterioration.det02 -> "NCVA.DETERIORATION.DET02"
* deterioration.det03 -> "NCVA.DETERIORATION.DET03"
* deterioration.det04 -> "NCVA.DETERIORATION.DET04"
* deterioration.det05 -> "NCVA.DETERIORATION.DET05"
* deterioration.det06 -> "NCVA.DETERIORATION.DET06"
* deterioration.det07 -> "NCVA.DETERIORATION.DET07"
* riskFactor -> "NCVA.DFACTOR"
* riskFactor.ht -> "NCVA.DFACTOR.HT"
* riskFactor.htcurrent -> "NCVA.DFACTOR.HTCURRENT"
* riskFactor.previoustia -> "NCVA.DFACTOR.PREVIOUSTIA"
* riskFactor.cancer -> "NCVA.DFACTOR.CANCER"
* riskFactor.hypercholesterolemia -> "NCVA.DFACTOR.HYPERCHOLESTEROLEMIA"
* riskFactor.smoking -> "NCVA.DFACTOR.SMOKING"
* riskFactor.smokingtiming -> "NCVA.DFACTOR.SMOKINGTIMING"
* riskFactor.smokingquantity -> "NCVA.DFACTOR.SMOKINGQUANTITY"
* riskFactor.smokingyears -> "NCVA.DFACTOR.SMOKINGYEARS"
* riskFactor.heartdisease -> "NCVA.DFACTOR.HEARTDISEASE"
* riskFactor.pad -> "NCVA.DFACTOR.PAD"
* riskFactor.dm -> "NCVA.DFACTOR.DM"
* riskFactor.dmcurrent -> "NCVA.DFACTOR.DMCURRENT"
* riskFactor.alcohol -> "NCVA.DFACTOR.ALCOHOL"
* riskFactor.hypertriglyceridemia -> "NCVA.DFACTOR.HYPERTRIGLYCERIDEMIA"
* riskFactor.polycythemia -> "NCVA.DFACTOR.POLYCYTHEMIA"
* riskFactor.uremia -> "NCVA.DFACTOR.UREMIA"
* riskFactor.previousci -> "NCVA.DFACTOR.PREVIOUSCI"
* riskFactor.previousch -> "NCVA.DFACTOR.PREVIOUSCH"
* familyHistory -> "NCVA.FMHISTORY"
* familyHistory.isHbr -> "NCVA.FMHISTORY.IS_HBR"
* familyHistory.isDm -> "NCVA.FMHISTORY.IS_DM"
* familyHistory.isIhd -> "NCVA.FMHISTORY.IS_IHD"
* familyHistory.isTia -> "NCVA.FMHISTORY.IS_TIA"
* examResult -> "NCVA.EXRESULT"
* examResult.ecgOption -> "NCVA.EXRESULT.ECG_OPTION"
* examResult.hb -> "NCVA.EXRESULT.HB"
* examResult.hct -> "NCVA.EXRESULT.HCT"
* examResult.platelet -> "NCVA.EXRESULT.PLATELET"
* examResult.wbc -> "NCVA.EXRESULT.WBC"
* examResult.ptt -> "NCVA.EXRESULT.PTT"
* examResult.pttControl -> "NCVA.EXRESULT.PTT_CONTROL"
* examResult.ptInr -> "NCVA.EXRESULT.PT_INR"
* examResult.glucoseEr -> "NCVA.EXRESULT.GLUCOSE_ER"
* examResult.bun -> "NCVA.EXRESULT.BUN"
* examResult.creatinine -> "NCVA.EXRESULT.CREATININE"
* examResult.albumin -> "NCVA.EXRESULT.ALBUMIN"
* examResult.crp -> "NCVA.EXRESULT.CRP"
* examResult.hba1c -> "NCVA.EXRESULT.HBA1C"
* examResult.gluAc -> "NCVA.EXRESULT.GLU_AC"
* examResult.ua -> "NCVA.EXRESULT.UA"
* examResult.tCho -> "NCVA.EXRESULT.T_CHO"
* examResult.tg -> "NCVA.EXRESULT.TG"
* examResult.hdl -> "NCVA.EXRESULT.HDL"
* examResult.ldl -> "NCVA.EXRESULT.LDL"
* examResult.got -> "NCVA.EXRESULT.GOT"
* examResult.gpt -> "NCVA.EXRESULT.GPT"
* timesheet -> "NCVA.TIMESHEET"
* timesheet.ctmridate -> "NCVA.TIMESHEET.CTMRIDATE"
* timesheet.ctmritime -> "NCVA.TIMESHEET.CTMRITIME"
* timesheet.isctmrifromoutside -> "NCVA.TIMESHEET.ISCTMRIFROMOUTSIDE"
* timesheet.ivtpadate -> "NCVA.TIMESHEET.IVTPADATE"
* timesheet.ivtpatime -> "NCVA.TIMESHEET.IVTPATIME"
* timesheet.ivtpareason -> "NCVA.TIMESHEET.IVTPAREASON"
* timesheet.ivtpasub01 -> "NCVA.TIMESHEET.IVTPASUB01"
* timesheet.ivtpasub02 -> "NCVA.TIMESHEET.IVTPASUB02"
* timesheet.ivtpasub03 -> "NCVA.TIMESHEET.IVTPASUB03"
* timesheet.ivtpasub04 -> "NCVA.TIMESHEET.IVTPASUB04"
* timesheet.ivtpasub05 -> "NCVA.TIMESHEET.IVTPASUB05"
* timesheet.ivtpasub06 -> "NCVA.TIMESHEET.IVTPASUB06"
* timesheet.ivtpasub07 -> "NCVA.TIMESHEET.IVTPASUB07"
* timesheet.ivtpasub08 -> "NCVA.TIMESHEET.IVTPASUB08"
* timesheet.ivtpasub09 -> "NCVA.TIMESHEET.IVTPASUB09"
* timesheet.ivtpasub10 -> "NCVA.TIMESHEET.IVTPASUB10"
* timesheet.ivtpadoze -> "NCVA.TIMESHEET.IVTPADOZE"
* timesheet.hadmdt -> "NCVA.TIMESHEET.HADMDT"
* timesheet.ctadate -> "NCVA.TIMESHEET.CTADATE"
* timesheet.ctatime -> "NCVA.TIMESHEET.CTATIME"
* timesheet.puncturedt -> "NCVA.TIMESHEET.PUNCTUREDT"
* timesheet.puncturetm -> "NCVA.TIMESHEET.PUNCTURETM"
* timesheet.perfusiondta -> "NCVA.TIMESHEET.PERFUSIONDTA"
* timesheet.perfusiontma -> "NCVA.TIMESHEET.PERFUSIONTMA"

Mapping: StrokeCaseManagementLMToFHIR
Source: StrokeCaseManagementLM
Target: "urn:vgh-stroke:fhir-profiles"
Id: fhir
Title: "FHIR 路徑對應"
Description: "各元素對應的 FHIR Profile 與元素路徑。沒有臨床資源對應的元素，原值保存在 StrokeRegistryResponse 的 raw 題目。"
* -> "StrokeCaseManagementBundle：Bundle" "一個個管事件的完整資料以一個 StrokeCaseManagementBundle 傳送"
* hisnummark -> "StrokePatient：Patient.identifier:medicalRecord.value" "病歷號原樣保留，不作為 Patient.id。type 固定 v2-0203 MR，system 用院方核定的網址（範例 http://www.vghks.gov.tw/patient-id）。每個院所+病歷號建一筆 Patient。"
* cmseqno -> "StrokeRegistryResponse：QuestionnaireResponse.identifier.value" "個管系統回覆的識別碼；identifier.system 用個管流水序號專用網址（範例 http://www.vghks.gov.tw/stroke-case-management-serial）。"
* caseMain.occdate -> "StrokeOnsetTime：Observation.valueDateTime" "code = stroke-observation#stroke-onset-time；與發病時間合併為同一筆 valueDateTime（YYYY-MM-DD 或 YYYY-MM）。時區確認前只填日期（YYYY-MM-DD），時間原值用 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。"
* caseMain.occtime -> "StrokeOnsetTime：Observation.valueDateTime" "code = stroke-observation#stroke-onset-time；與發病日期合併為同一筆 valueDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值用 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。若只有時間無日期，填入 Observation.value[x]:valueDateTime.extension:eventTimeOnly.valueTime。"
* caseMain.arrdate -> "StrokeEncounter：Encounter.period.start" "到院日期只用於經本院急診到院的事件：填急診 Encounter（class EMER）的 period.start，並與到院時間合併。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。無法確認經急診到院時，不建立急診 Encounter，原值只存原始值群組。"
* caseMain.arrtime -> "StrokeEncounter：Encounter.period.start" "到院時間只用於經本院急診到院的事件：與到院日期合併填入 period.start。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。無日期時改填 Encounter.period.start.extension:eventTimeOnly.valueTime。無法確認經急診到院時，原值只存原始值群組。"
* caseMain.hdisdt -> "StrokeEncounter：Encounter.period.end" "住院 Encounter（class IMP）填離院日期；兩來源不一致時須人工核對；只有時間時改填 Encounter.period.end.extension:eventTimeOnly.valueTime。"
* caseMain.psex -> "StrokePatient：Patient.gender" "F→female、M→male；其他值→unknown，原值存入原始值群組；缺值時用 data-absent-reason 擴充。"
* caseMain.hage -> "StrokeAdmissionContext：Observation.valueQuantity" "code = stroke-observation#patient-age；填入 valueQuantity，單位用 UCUM a。空白不建立。"
* caseMain.height -> "StrokeBodyHeight：Observation.valueQuantity.value" "code = http://loinc.org#8302-2；身高數值填 valueQuantity.value，單位用 UCUM cm。值為 0 時在確認意義前不建立，只保留原始值；有實際測量時間才建立。"
* caseMain.weight -> "StrokeBodyWeight：Observation.valueQuantity.value" "code = http://loinc.org#29463-7；體重數值填 valueQuantity.value，單位用 UCUM kg。值為 0 時在確認意義前不建立，只保留原始值；有實際測量時間才建立。"
* caseMain.edulevelcode -> "StrokeAdmissionContext：Observation.valueCodeableConcept" "code = stroke-observation#education-level；代碼填入 StrokeEducationLevelCS；EDU99 保留為原代碼。空白不建立。"
* caseMain.ocpcode -> "StrokeOccupation：Observation.valueCodeableConcept.coding:occupationCategory" "code = http://loinc.org#11341-5；原碼 OCP00–OCP09、OCP99 填 StrokeOccupationCategoryCS，OCP99 為「其他」，空值或無法辨識代碼不建立。每個來源、病人與個管事件（評估時點，以 encounter 區分）各建一筆，只對同一事件的重複資料去重，保留跨事件的職業歷史。"
* caseMain.patfrom -> "StrokeAdmissionContext：Observation.valueCodeableConcept" "code = stroke-observation#admission-source；入院方式原碼 A（住院）、E（急診）、O（門診）直接填入 StrokeAdmissionSourceCS，空白不建立。"
* caseMain.reachwaycode -> "StrokeAdmissionContext：Observation.valueCodeableConcept" "code = stroke-observation#arrival-mode；代碼請對應轉換：EMG 填 1、SELF 填 2、TRAN 填 3；NONE 保留代碼 NONE。空白不建立。"
* caseMain.levoption -> "StrokeEncounter：Encounter.hospitalization.dischargeDisposition" "LEV01→1、LEV02→2、LEV03→3；LEV05（轉 PAC）保留原碼。只用於住院 Encounter。"
* comaScale.gcsM -> "StrokeGCS：Observation.component:motor.valueInteger" "code = http://loinc.org#9268-4；Observation.code = LOINC 9269-2。M 分數填 1–6；缺值處理同 E。來源無 GCS 總分，valueInteger 不填。"
* comaScale.gcsE -> "StrokeGCS：Observation.component:eye.valueInteger" "code = http://loinc.org#9267-6；Observation.code = LOINC 9269-2。E 分數填 1–4；空白、非數值或超出範圍時不填 value，component 改填 dataAbsentReason（只知缺值用 unknown）；到院的 assessmentPhase 填 admission。"
* comaScale.gcsV -> "StrokeGCS：Observation.component:verbal.valueInteger" "code = http://loinc.org#9270-0；Observation.code = LOINC 9269-2。V 分數填 1–5；缺值處理同 E。"
* comaScale.sbp -> "StrokeBloodPressure：Observation.component:SystolicBP.valueQuantity.value" "code = http://loinc.org#8480-6；Observation.code = LOINC 85354-9，單位填 mm[Hg]。只有舒張壓時，本 component 保留 code 並填 dataAbsentReason = unknown；兩者皆缺不建立。"
* comaScale.dbp -> "StrokeBloodPressure：Observation.component:DiastolicBP.valueQuantity.value" "code = http://loinc.org#8462-4；Observation.code = LOINC 85354-9，單位填 mm[Hg]。只有收縮壓時，本 component 保留 code 並填 dataAbsentReason = unknown；兩者皆缺不建立。"
* comaScale.bt -> "StrokeBodyTemperature：Observation.valueQuantity.value" "code = http://loinc.org#8310-5；數值填 valueQuantity.value，單位固定填 UCUM Cel。確認來源單位且有實際測量時間才建立。"
* comaScale.hr -> "StrokeHeartRate：Observation.valueQuantity.value" "code = http://loinc.org#8867-4；數值填 valueQuantity.value，單位填 /min（TW Core 固定）。有實際測量時間才建立。"
* comaScale.rr -> "StrokeRespiratoryRate：Observation.valueQuantity.value" "code = http://loinc.org#9279-1；數值填 valueQuantity.value，單位填 /min（TW Core 固定）。有實際測量時間才建立。"
* comaScale.icd10 -> "StrokeCondition：Condition.code.coding:icd10cm.code" "ICD-10-CM 原碼放 icd10cm Slice（system http://hl7.org/fhir/sid/icd-10-cm），版本確認前先只填 code.text。clinicalStatus、category 由診斷來源取得；兩者齊全才建立 Condition，否則原值存入 StrokeRegistryResponse 原始值備份。"
* comaScale.infarct -> "StrokeClinicalAssessment：Observation.valueString" "code = stroke-observation#stroke-type-infarction；valueString 保留原值填入。"
* comaScale.stkdiagnosisoption1 -> "StrokeClinicalAssessment：Observation.valueCodeableConcept" "code = stroke-observation#toast-classification；分類文字請對應轉碼：Large artery atherosclerosis 轉 1、Cardioembolism 轉 3、Specific etiology 轉 4、Undertermined etiology（來源拼法，Undetermined etiology 亦同）轉 5、Small vessel occlusion 轉 svo；其他文字只存原始值。空白不建立。"
* comaScale.stkdiagnosisoption2 -> "StrokeClinicalAssessment：Observation.valueBoolean" "code = stroke-observation#toast-laa-extracranial；來源為 TOAST 次分類文字欄，請依條件拆分：值為 Extra 時建立本項且 valueBoolean = true。其他值不建立本項：Intra 改建 toast-laa-intracranial；其他病因文字改建 toast-specific-etiology；Incomplete Study、Conflict data、Complete Study 僅存原始值，不建立 Observation。空白不建立。"
* comaScale.stkdiagnosisoption2 -> "StrokeClinicalAssessment：Observation.valueBoolean" "code = stroke-observation#toast-laa-intracranial；來源為 TOAST 次分類文字欄，請依條件拆分：值為 Intra 時建立本項且 valueBoolean = true。其他值不建立本項：Extra 改建 toast-laa-extracranial；其他病因文字改建 toast-specific-etiology；Incomplete Study、Conflict data、Complete Study 僅存原始值，不建立 Observation。空白不建立。"
* comaScale.stkdiagnosisoption2 -> "StrokeClinicalAssessment：Observation.valueString" "code = stroke-observation#toast-specific-etiology；來源為 TOAST 次分類文字欄，請依條件拆分：值為特定病因文字（Cerebral venous thrombosis、Moyamoya Synd、Radiation、Dissection、Migraine、Antiphospholipid Ab Synd、Autoummune disease、Hyperfibrinogenemia、Prot C/Prot S deficiency、Antithrombin III deficiency、Homocystinuria、Hypercoagulable state、Cancer、其他）時建立本項，valueString 原樣保留。Extra、Intra 改建 toast-laa-extracranial 與 toast-laa-intracranial。Incomplete Study、Conflict data、Complete Study 只存原始值，不建立 Observation。空白不建立。"
* comaScale.tia -> "StrokeClinicalAssessment：Observation.valueBoolean" "code = stroke-observation#stroke-type-tia；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* comaScale.ich -> "StrokeClinicalAssessment：Observation.valueBoolean" "code = stroke-observation#stroke-type-ich；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* comaScale.sah -> "StrokeClinicalAssessment：Observation.valueBoolean" "code = stroke-observation#stroke-type-sah；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* comaScale.stkdiagnosisoption3 -> "StrokeClinicalAssessment：Observation.valueString" "code = stroke-observation#stroke-subtype-tia-ich-sah；valueString 保留原值填入。空白不建立。"
* comaScale.unnamedCol19 -> "StrokeRegistryResponse：QuestionnaireResponse.item:unresolvedComaScaleCol19.answer.valueString" "linkId 填 unresolved.NCVA.COMASCALE.UNNAMED_COL_19，保存原始字串。"
* nihss.freqno -> "StrokeNIHSS：Observation.extension:assessmentSequence.valuePositiveInt" "code = http://loinc.org#72089-6；來源評估序號原樣保留。序號 1 另填 assessmentPhase=admission、2 填 discharge，各建一筆。"
* nihss.oneA -> "StrokeNIHSS：Observation.component:levelOfConsciousness.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70184-7。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.oneA -> "StrokeNIHSS：Observation.component:levelOfConsciousness.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70184-7。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.oneB -> "StrokeNIHSS：Observation.component:locQuestions.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70185-4。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.oneB -> "StrokeNIHSS：Observation.component:locQuestions.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70185-4。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.oneC -> "StrokeNIHSS：Observation.component:locCommands.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70186-2。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.oneC -> "StrokeNIHSS：Observation.component:locCommands.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70186-2。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.two -> "StrokeNIHSS：Observation.component:bestGaze.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70187-0。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.two -> "StrokeNIHSS：Observation.component:bestGaze.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70187-0。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.three -> "StrokeNIHSS：Observation.component:visual.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70188-8。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.three -> "StrokeNIHSS：Observation.component:visual.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70188-8。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.four -> "StrokeNIHSS：Observation.component:facialPalsy.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70189-6。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.four -> "StrokeNIHSS：Observation.component:facialPalsy.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70189-6。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.fiveAl -> "StrokeNIHSS：Observation.component:motorArmLeft.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70190-4。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.fiveAl -> "StrokeNIHSS：Observation.component:motorArmLeft.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70190-4。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.fiveBr -> "StrokeNIHSS：Observation.component:motorArmRight.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70967-5。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.fiveBr -> "StrokeNIHSS：Observation.component:motorArmRight.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70967-5。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.sixAl -> "StrokeNIHSS：Observation.component:motorLegLeft.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70191-2。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.sixAl -> "StrokeNIHSS：Observation.component:motorLegLeft.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70191-2。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.sixBr -> "StrokeNIHSS：Observation.component:motorLegRight.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70968-3。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.sixBr -> "StrokeNIHSS：Observation.component:motorLegRight.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70968-3。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.seven -> "StrokeNIHSS：Observation.component:limbAtaxia.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70192-0。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.seven -> "StrokeNIHSS：Observation.component:limbAtaxia.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70192-0。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.eight -> "StrokeNIHSS：Observation.component:sensory.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70193-8。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.eight -> "StrokeNIHSS：Observation.component:sensory.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70193-8。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.nine -> "StrokeNIHSS：Observation.component:bestLanguage.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70194-6。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.nine -> "StrokeNIHSS：Observation.component:bestLanguage.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70194-6。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.ten -> "StrokeNIHSS：Observation.component:dysarthria.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70195-3。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.ten -> "StrokeNIHSS：Observation.component:dysarthria.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70195-3。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.eleven -> "StrokeNIHSS：Observation.component:extinctionInattention.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission；component.code=http://loinc.org#70196-1。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.eleven -> "StrokeNIHSS：Observation.component:extinctionInattention.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge；component.code=http://loinc.org#70196-1。有效整數填 valueInteger，X 等非數值或超出範圍改填 valueString 原樣保留；空白不建 component。"
* nihss.total -> "StrokeNIHSS：Observation.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=admission。有效整數 0–42 填 valueInteger，X、7+X 等非數值改填 valueString；空白不填。"
* nihss.total -> "StrokeNIHSS：Observation.valueInteger" "code = http://loinc.org#72089-6；assessmentPhase=discharge。有效整數 0–42 填 valueInteger，X、7+X 等非數值改填 valueString；空白不填。"
* nihss.inpdate -> "StrokeNIHSS：Observation.effectiveDateTime" "code = http://loinc.org#72089-6；assessmentPhase=admission。日期與同次評估時間合併填入 effectiveDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。若只有年月或只有時間就不填，原值存 StrokeRegistryResponse。"
* nihss.inpdate -> "StrokeNIHSS：Observation.effectiveDateTime" "code = http://loinc.org#72089-6；assessmentPhase=discharge。日期與同次評估時間合併填入 effectiveDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。若只有年月或只有時間就不填，原值存 StrokeRegistryResponse。"
* nihss.inptime -> "StrokeNIHSS：Observation.effectiveDateTime" "code = http://loinc.org#72089-6；assessmentPhase=admission。日期與同次評估時間合併填入 effectiveDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。若只有年月或只有時間就不填，原值存 StrokeRegistryResponse。"
* nihss.inptime -> "StrokeNIHSS：Observation.effectiveDateTime" "code = http://loinc.org#72089-6；assessmentPhase=discharge。日期與同次評估時間合併填入 effectiveDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。若只有年月或只有時間就不填，原值存 StrokeRegistryResponse。"
* nihss.arrdate -> "StrokeEncounter：Encounter.period.start" "住院 Encounter（class IMP）的入院日期，與「住院日期」欄位填同一元素；只有時間時改填 Encounter.period.start.extension:eventTimeOnly.valueTime。"
* nihss.hdisdt -> "StrokeEncounter：Encounter.period.end" "住院 Encounter（class IMP）的離院日期，與另一個「離院日期」欄位填同一元素；兩者不一致時須人工核對。"
* mrs.freqno -> "StrokeMRS：Observation.extension:assessmentSequence.valuePositiveInt" "code = http://loinc.org#75859-9；序號 1–9 原樣保留。序號意義確認前，assessmentPhase=unclassified。"
* mrs.mrsrate -> "StrokeMRS：Observation.valueInteger" "code = http://loinc.org#75859-9；評估次數意義確認前，填 assessmentPhase = unclassified；分數 0–6 填原值。"
* mrs.inpdate -> "StrokeMRS：Observation.effectiveDateTime" "code = http://loinc.org#75859-9；序號意義確認前，assessmentPhase=unclassified。只有年月或只有時間就不填，原值存 StrokeRegistryResponse。"
* mrs.inpdate -> "StrokeMRS：Observation.effectiveDateTime" "code = http://loinc.org#75859-9；填原始各次評估日期，assessmentPhase=unclassified；不足完整日期就不填。"
* mrs.inpdate -> "StrokeMRS：Observation.effectiveDateTime" "code = http://loinc.org#75859-9；評估日期：評估次數意義確認前，填 assessmentPhase = unclassified；不足完整日期時不填，原值存原始值群組。"
* mrs.unnamedCol06 -> "StrokeRegistryResponse：QuestionnaireResponse.item:unresolvedMrsCol06.answer.valueString" "linkId 填 unresolved.NCVA.mRS.UNNAMED_COL_06。answer 為 1..*，每筆 mRS 列一個值，列對應以 raw.ncva.mrs 群組為準。"
* mrs.unnamedCol07 -> "StrokeRegistryResponse：QuestionnaireResponse.item:unresolvedMrsCol07.answer.valueString" "linkId 填 unresolved.NCVA.mRS.UNNAMED_COL_07。answer 為 1..*，每筆 mRS 列一個值，列對應以 raw.ncva.mrs 群組為準。"
* ich.ichScore -> "StrokeClinicalAssessment：Observation.valueString" "code = stroke-observation#ich-score；valueString 保留來源分數原值填入；評估日期填入同筆 effectiveDateTime。"
* ich.formdt -> "StrokeClinicalAssessment：Observation.effectiveDateTime" "code = stroke-observation#ich-score；填入 ich-score 該筆的 effectiveDateTime；格式至少需有 YYYY-MM-DD，若只有年月或只有時間則不填。"
* hhs.hlsGrade -> "StrokeClinicalAssessment：Observation.valueString" "code = stroke-observation#hunt-hess-grade；valueString 保留來源分級原值填入；評估日期填入同筆 effectiveDateTime。"
* hhs.formdt -> "StrokeClinicalAssessment：Observation.effectiveDateTime" "code = stroke-observation#hunt-hess-grade；填 hunt-hess-grade 的 effectiveDateTime；至少要有 YYYY-MM-DD，只有年月或只有時間時不填。"
* heartDisease.thd01 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#atrial-fibrillation-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd02 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#ischemic-heart-disease-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd03 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#valve-replacement-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd04 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#endocarditis-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd05 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#cardiac-myxoma-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd06 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#heart-failure-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd07 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#acute-mi-within-4-weeks / stroke-observation#acute-mi-history；來源限定 4 週內急性心肌梗塞時，code 填 acute-mi-within-4-weeks。0 填 false、1 填 true；空白不建立。"
* heartDisease.thd08 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#rheumatic-heart-disease-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* heartDisease.thd09 -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#patent-foramen-ovale；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* treatment.tre01 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#aggrenox，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre02 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#aspirin，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre03 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#ticlopidine，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre05 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#warfarin，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre06 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#ia-thrombectomy，並加填 SNOMED CT 439541007（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre07 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#urinary-catheter-insertion，並加填 SNOMED CT 446583004（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre09 -> "StrokeRegistryResponse：QuestionnaireResponse.item:signDnr.answer.valueBoolean" "linkId 填 inpatientTreatment.tre09，1→true、0→false。"
* treatment.tre10 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#rehabilitation，並加填 SNOMED CT 2517002（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre13 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#clopidogrel，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre14 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#cilostazol-brand，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre15 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#lmw-heparin，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre16 -> "StrokeMedicationAdministration：MedicationAdministration.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#iv-tpa-unspecified。1→completed、0→not-done；有給藥日期或時間（effective）才建立，否則只存登錄表單；空白不建立。"
* treatment.tre17 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#mechanical-ventilation，並加填 SNOMED CT 40617009（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre18 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#nasogastric-tube-insertion，並加填 SNOMED CT 87750000（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre19 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#dysphagia-screening，並加填 SNOMED CT 431765005（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre20 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#icu-admission；0→false、1→true，只記錄是否入住 ICU；空白不建立。"
* treatment.tre21 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#smoking-cessation-counseling。1→completed、0→not-done；空白不建立。"
* treatment.tre22 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#stroke-education，並加填 SNOMED CT 720849008（code.coding:sct-procedures）。1→completed、0→not-done；空白不建立。"
* treatment.tre23 -> "StrokeProcedure：Procedure.status" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#surgical-treatment。1→completed、0→not-done；空白不建立。"
* treatment.tre27 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#apixaban，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre28 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#dabigatran，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre29 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#edoxaban，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre30 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#rivaroxaban，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* treatment.tre31 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#ticagrelor，extension:recordingContext 填 inpatient。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg01 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#aspirin，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg02 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#aggrenox，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg03 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#ticlopidine，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg04 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#clopidogrel，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg05 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#cilostazol-brand，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg06 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#antihypertensive，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg07 -> "StrokeMedicationStatement：MedicationStatement.status" "來源為 Warfarin 欄時，coding:strokeMedication 用 warfarin。狀態填寫：0→not-taken；1→unknown 且 note.text 填「來源記錄有使用」；空白不建立。"
* dischargeDrug.drg08 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#diabetes-medication，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.sub01 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#oral-hypoglycemic，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.sub02 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#insulin，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.sub03 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#statin，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.sub04 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#non-statin-lipid-lowering，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* dischargeDrug.drg12 -> "StrokeMedicationStatement：MedicationStatement.medicationCodeableConcept.coding:strokeMedication" "四個藥品欄各建一筆：DRG12→apixaban、DRG13→dabigatran、DRG14→edoxaban、DRG15→rivaroxaban。每欄狀態填寫：0→not-taken；1→unknown 且 note.text 填「來源記錄有使用」；空白不建立。"
* dischargeDrug.drg13 -> "StrokeMedicationStatement：MedicationStatement.medicationCodeableConcept.coding:strokeMedication" "四個藥品欄各建一筆：DRG12→apixaban、DRG13→dabigatran、DRG14→edoxaban、DRG15→rivaroxaban。每欄狀態填寫：0→not-taken；1→unknown 且 note.text 填「來源記錄有使用」；空白不建立。"
* dischargeDrug.drg14 -> "StrokeMedicationStatement：MedicationStatement.medicationCodeableConcept.coding:strokeMedication" "四個藥品欄各建一筆：DRG12→apixaban、DRG13→dabigatran、DRG14→edoxaban、DRG15→rivaroxaban。每欄狀態填寫：0→not-taken；1→unknown 且 note.text 填「來源記錄有使用」；空白不建立。"
* dischargeDrug.drg15 -> "StrokeMedicationStatement：MedicationStatement.medicationCodeableConcept.coding:strokeMedication" "四個藥品欄各建一筆：DRG12→apixaban、DRG13→dabigatran、DRG14→edoxaban、DRG15→rivaroxaban。每欄狀態填寫：0→not-taken；1→unknown 且 note.text 填「來源記錄有使用」；空白不建立。"
* dischargeDrug.drg16 -> "StrokeMedicationStatement：MedicationStatement.status" "medicationCodeableConcept.coding:strokeMedication 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-medication#ticagrelor，extension:recordingContext 填 discharge。0→not-taken；1→unknown，note.text 填「來源記錄有使用」；狀態確認後改填 active／completed；空白不建立。"
* deterioration.det01 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#neurologic-deterioration-nihss-2-or-more | stroke-observation#neurologic-deterioration-criteria-unspecified；code 用 neurologic-deterioration-nihss-2-or-more（NIHSS 增加至少 2 分）。0 填 false、1 填 true，空白不建立。"
* deterioration.det02 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#deterioration-cause-herniation；0→false、1→true，空白不建立；其他代碼以原值存入 StrokeRegistryResponse。"
* deterioration.det03 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#deterioration-cause-hemorrhagic-infarct-36h；0→false、1→true，空白不建立；其他代碼以原值存入 StrokeRegistryResponse。"
* deterioration.det04 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#deterioration-cause-hematoma-expansion；0→false、1→true，空白不建立；其他代碼以原值存入 StrokeRegistryResponse。"
* deterioration.det05 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#deterioration-cause-vasospasm；0→false、1→true，空白不建立；其他代碼以原值存入 StrokeRegistryResponse。"
* deterioration.det06 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#deterioration-cause-rebleeding；0→false、1→true，空白不建立；其他代碼以原值存入 StrokeRegistryResponse。"
* deterioration.det07 -> "StrokeComplication：Observation.valueBoolean" "code = stroke-observation#deterioration-cause-medical-problem；0→false、1→true，空白不建立；其他代碼以原值存入 StrokeRegistryResponse。"
* riskFactor.ht -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#hypertension-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.htcurrent -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#hypertension-newly-diagnosed；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.previoustia -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#prior-tia-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.cancer -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#cancer-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.hypercholesterolemia -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#hypercholesterolemia-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.smoking -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#smoking-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.smokingtiming -> "StrokeSmokingStatus：Observation.valueCodeableConcept" "code = http://loinc.org#72166-2；Current→coding:snomedSmokingStatus 77176002；Past→8517006。coding:smokingStatusDetail 保留原碼 Current 或 Past。空白不建立；有實際調查時間才建立。"
* riskFactor.smokingquantity -> "StrokeRiskFactor：Observation.valueQuantity" "code = stroke-observation#cigarettes-per-day；填入 valueQuantity，單位填 {cigarette}/d；等單位核定後才填 system/code。空白不建立。"
* riskFactor.smokingyears -> "StrokeRiskFactor：Observation.valueQuantity" "code = stroke-observation#smoking-duration；填入 valueQuantity，單位填 a；等單位核定後才填 system/code。空白不建立。"
* riskFactor.heartdisease -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#heart-disease-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.pad -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#peripheral-artery-disease-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.dm -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#diabetes-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.dmcurrent -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#diabetes-newly-diagnosed；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.alcohol -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#alcohol-use-history；0 填 false、1 填 true；空白不建立，其他值只存原始值。陰性不建立 Condition。"
* riskFactor.hypertriglyceridemia -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#hypertriglyceridemia-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.polycythemia -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#polycythemia-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.uremia -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#uremia-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.previousci -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#prior-cerebral-infarction-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* riskFactor.previousch -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#prior-cerebral-hemorrhage-history；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* familyHistory.isHbr -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#family-history-hypertension；0 填 false、1 填 true；若為 2（不確定／不知道）則不填值，改填 dataAbsentReason=unknown；空白不建立。陰性不建立 Condition。"
* familyHistory.isDm -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#family-history-diabetes；0 填 false、1 填 true；若為 2（不確定／不知道）則不填值，改填 dataAbsentReason=unknown；空白不建立。陰性不建立 Condition。"
* familyHistory.isIhd -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#family-history-ischemic-heart-disease；0 填 false、1 填 true；若為 2（不確定／不知道）則不填值，改填 dataAbsentReason=unknown；空白不建立。陰性不建立 Condition。"
* familyHistory.isTia -> "StrokeRiskFactor：Observation.valueBoolean" "code = stroke-observation#family-history-stroke-or-tia；0 填 false、1 填 true；若為 2（不確定／不知道）則不填值，改填 dataAbsentReason=unknown；空白不建立。陰性不建立 Condition。"
* examResult.ecgOption -> "StrokeClinicalAssessment：Observation.valueBoolean" "code = stroke-observation#ecg-atrial-fibrillation；0（不是 Af）填 false、1（Af）填 true；空白不建立。"
* examResult.hb -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#hemoglobin；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.hct -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#hematocrit；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.platelet -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#platelet-count；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.wbc -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#wbc-count；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.ptt -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#ptt；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.pttControl -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#ptt-control；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.ptInr -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#pt-inr；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.glucoseEr -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#glucose-at-emergency；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.bun -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#bun；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.creatinine -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#creatinine；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.albumin -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#albumin；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.crp -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#crp；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.hba1c -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#hba1c；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.gluAc -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#fasting-glucose-first；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.ua -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#ua-unspecified；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。確認是尿酸或尿液檢查前，只用 ua-unspecified。"
* examResult.tCho -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#total-cholesterol；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.tg -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#triglyceride；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.hdl -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#hdl-cholesterol；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.ldl -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#ldl-cholesterol；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.got -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#ast；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* examResult.gpt -> "StrokeLaboratory：Observation.valueQuantity" "code = stroke-observation#alt；項目代碼填 Observation.code.coding:strokeObservation。單位確認前只填 value（原值）；若為 NA／NAA／空白但有採檢時間，填 dataAbsentReason=unknown。有實際採檢時間才建立，否則只存 StrokeRegistryResponse。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* timesheet.ctmridate -> "StrokeImagingStudy：ImagingStudy.started" "description 填「首次 CT/MRI」，modality 無法確認 CT 或 MR 時不填。同一次檢查的日期與時間合併填入 started。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。只有時間時填 started.extension:eventTimeOnly.valueTime；都沒有時不填。各檢查各自建立一筆 ImagingStudy。"
* timesheet.ctmritime -> "StrokeImagingStudy：ImagingStudy.started" "description 填「首次 CT/MRI」，modality 無法確認 CT 或 MR 時不填。同一次檢查的日期與時間合併填入 started。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。只有時間時填 started.extension:eventTimeOnly.valueTime；都沒有時不填。各檢查各自建立一筆 ImagingStudy。"
* timesheet.isctmrifromoutside -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#first-ct-mri-from-outside-hospital；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpadate -> "StrokeMedicationAdministration：MedicationAdministration.effectiveDateTime" "EVT 前 IV-tPA 的日期與時間合併填入 effectiveDateTime，medication 填 iv-tpa-unspecified。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。只有時間時填 effectiveDateTime.extension:eventTimeOnly.valueTime；兩者皆無時不建立。"
* timesheet.ivtpatime -> "StrokeMedicationAdministration：MedicationAdministration.effectiveDateTime" "EVT 前 IV-tPA 的日期與時間合併填入 effectiveDateTime，medication 填 iv-tpa-unspecified。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。只有時間時填 effectiveDateTime.extension:eventTimeOnly.valueTime；兩者皆無時不建立。"
* timesheet.ivtpareason -> "StrokeCareProcess：Observation.valueCodeableConcept" "code = stroke-observation#ivtpa-not-given-main-reason；答案填 StrokeIvtpaNotGivenReasonCS（REA01–REA03）並保留原碼，空白不建立。"
* timesheet.ivtpasub01 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-onset-over-3h；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub02 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-mild-or-improving；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub03 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-severe-stroke；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub04 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-age-out-of-range；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub05 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-prior-stroke-with-diabetes；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub06 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-high-blood-pressure；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub07 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-recent-stroke-or-head-trauma；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub08 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-seizure-at-onset；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub09 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-oral-anticoagulant；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpasub10 -> "StrokeCareProcess：Observation.valueBoolean" "code = stroke-observation#ivtpa-not-given-family-refusal；0 填 false、1 填 true；空白不建立，其他代碼原值存入 StrokeRegistryResponse。"
* timesheet.ivtpadoze -> "StrokeMedicationAdministration：MedicationAdministration.dosage.dose.value" "譯碼簿未列劑量單位。單位確認前，原文填 note.text，不填 dosage.dose。"
* timesheet.hadmdt -> "StrokeEncounter：Encounter.period.start" "住院 Encounter（class IMP）填住院日期；只有時間沒有日期時，改填 Encounter.period.start.extension:eventTimeOnly.valueTime。"
* timesheet.ctadate -> "StrokeImagingStudy：ImagingStudy.started" "description 填「EVT 前 CTA」，modality 填 DCM#CT，procedureCode.coding:rapidScanType 可填 CTA。同一次檢查的日期與時間合併填入 started。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。只有時間時填 started.extension:eventTimeOnly.valueTime；都沒有時不填。各檢查各自建立一筆 ImagingStudy。"
* timesheet.ctatime -> "StrokeImagingStudy：ImagingStudy.started" "description 填「EVT 前 CTA」，modality 填 DCM#CT，procedureCode.coding:rapidScanType 可填 CTA。同一次檢查的日期與時間合併填入 started。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認的時區（例如 +08:00）。只有時間時填 started.extension:eventTimeOnly.valueTime；都沒有時不填。各檢查各自建立一筆 ImagingStudy。"
* timesheet.puncturedt -> "StrokeProcedure：Procedure.performedDateTime" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#evt-puncture，以 partOf 參照同次 EVT 主處置（evt）。穿刺日期與時間合併填 performedDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認時區（例如 +08:00）。只有時間時填 performedDateTime.extension:eventTimeOnly.valueTime；日期與時間皆無時不填。"
* timesheet.puncturetm -> "StrokeProcedure：Procedure.performedDateTime" "code.coding:strokeProcedure 填 http://vgh-stroke-ig.fhir.tw/CodeSystem/stroke-procedure#evt-puncture，以 partOf 參照同次 EVT 主處置（evt）。穿刺日期與時間合併填 performedDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與已確認時區（例如 +08:00）。只有時間時填 performedDateTime.extension:eventTimeOnly.valueTime；日期與時間皆無時不填。"
* timesheet.perfusiondta -> "StrokeProcedureResult：Observation.valueDateTime" "code = stroke-observation#reperfusion-time；項目代碼填 Observation.code.coding:strokeObservation。日期與同事件時間合併填入 valueDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間時 valueDateTime 不填值，改填 Observation.valueDateTime.extension:eventTimeOnly.valueTime。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。首次再通、最終再通與再灌流時間只記錄在 StrokeProcedureResult；EVT 主處置的 performed 依來源的處置時間填寫。"
* timesheet.perfusiontma -> "StrokeProcedureResult：Observation.valueDateTime" "code = stroke-observation#reperfusion-time；項目代碼填 Observation.code.coding:strokeObservation。日期與同事件時間合併填入 valueDateTime。時區確認前只填日期（YYYY-MM-DD），時間原值以 StrokeEventTimeOnly 擴充附在該元素上，並存入 StrokeRegistryResponse 的原始值題目；確認後填完整日期時間與時區（例如 +08:00）。只有日期填 YYYY-MM-DD，只有年月填 YYYY-MM；只有時間時 valueDateTime 不填值，改填 Observation.valueDateTime.extension:eventTimeOnly.valueTime。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。首次再通、最終再通與再灌流時間只記錄在 StrokeProcedureResult；EVT 主處置的 performed 依來源的處置時間填寫。"
