Logical: StrokeRapidLM
Id: StrokeRapidLM
Title: "RAPID 影像分析資料邏輯模型"
Description: "RAPID 腦部影像分析結果（NCVA.RAPID）邏輯模型。每次掃描一筆，以病歷號、申請序號、掃描類型與醫院代號識別；數值欄缺值時直接留空。"
* ^status = #draft
* hisnummark 1..1 Identifier "病歷號" "病人在本院的病歷號。"
* rpreqno 1..1 Identifier "申請序號" "影像申請序號，院方說明為醫師開立的醫令碼。語意確認前不寫入 ImagingStudy／ServiceRequest 的 identifier，原值保存在登錄表單回覆，並作為 RAPID 資料包紀錄鍵的一部分。"
* scantype 1..1 code "掃描類型" "影像掃描類型，可填 CTP、CTA、NCCT；來源值有時帶尾端空白。"
* latestseriesdate 0..1 date "最近一次掃描 series 日期" "最近一次掃描 series 的日期，格式為 YYYY-MM-DD；正式介面只有日期。"
* aspectsAffectedside 0..1 code "ASPECTS 影響側" "ASPECTS 評估的影響側：L＝左腦；R＝右腦。"
* aspects 0..1 integer "ASPECTS 分數" "ASPECTS 分數，範圍 0 至 10。"
* ctaAffectedside 0..1 code "CTA 影響側" "電腦斷層血管攝影的影響側：L＝左腦；R＝右腦。"
* cbfVolume 0..1 Quantity "CBF<30% 體積" "腦血流量小於 30% 的體積，單位為 mL。填 0 至 3 位整數，僅 CTP 影像有此值。"
* tmaxVolume 0..1 Quantity "Tmax>6 秒體積" "Tmax 大於 6 秒的體積，單位為 mL。填 0 至 3 位整數，僅 CTP 影像有此值。"
* mismatchVolume 0..1 Quantity "不一致體積" "不一致體積，單位為 mL。譯碼簿公式：Tmax 小於 6 秒體積減去 CBF 小於 30% 體積；數值採來源原值，填 0 至 3 位整數，僅 CTP 影像有此值。"
* mismatchRatio 0..1 decimal "不一致比率" "不一致比率。譯碼簿公式：Tmax 小於 6 秒體積除以 CBF 小於 30% 體積。格式為 XX.X，僅 CTP 影像有此值；9999 表示無法計算，視同缺值，真實的 0 要保留。"
* hypoperfusionIntensityRatio 0..1 decimal "低灌注強度比值" "低灌注強度比值，為 Tmax 大於 10 秒體積除以 Tmax 大於 6 秒體積。數值介於 0 至 0.X，僅 CTP 影像有此值。"
* hid 1..1 Identifier "醫院代號" "院所代號，例如 1A0＝高雄榮總。"
* zrapid 0..1 dateTime "日期時戳" "資料時戳，格式為 YYYY-MM-DD hh:mm:ss。"
* mtqualified 0..1 string "MTQUALIFIED" "JSON 樣本有此欄位，但譯碼簿未定義，樣本皆為空值。"
* mtqualified16hDefuse3 0..1 string "MTQUALIFIED_16H_DEFUSE3" "JSON 樣本有此欄位，但譯碼簿未定義，樣本皆為空值。"
* mtqualified6hExtendia 0..1 string "MTQUALIFIED_6H_EXTENDIA" "JSON 樣本有此欄位，但譯碼簿未定義，樣本皆為空值。"
* mtqualified6hSwiftprime 0..1 string "MTQUALIFIED_6H_SWIFTPRIME" "JSON 樣本有此欄位，但譯碼簿未定義，樣本皆為空值。"

Mapping: StrokeRapidLMToRapid
Source: StrokeRapidLM
Target: "urn:vgh-stroke:source:rapid"
Description: "對照 RAPID 譯碼簿（NCVA.RAPID）的原始欄位。"
Id: rapid-source
Title: "RAPID 原始欄位對照"
* -> "NCVA.RAPID"
* hisnummark -> "NCVA.RAPID.HISNUMMARK"
* rpreqno -> "NCVA.RAPID.RPREQNO"
* scantype -> "NCVA.RAPID.SCANTYPE"
* latestseriesdate -> "NCVA.RAPID.LATESTSERIESDATE"
* aspectsAffectedside -> "NCVA.RAPID.ASPECTS_AFFECTEDSIDE"
* aspects -> "NCVA.RAPID.ASPECTS"
* ctaAffectedside -> "NCVA.RAPID.CTA_AFFECTEDSIDE"
* cbfVolume -> "NCVA.RAPID.CBF_VOLUME"
* tmaxVolume -> "NCVA.RAPID.TMAX_VOLUME"
* mismatchVolume -> "NCVA.RAPID.MISMATCH_VOLUME"
* mismatchRatio -> "NCVA.RAPID.MISMATCH_RATIO"
* hypoperfusionIntensityRatio -> "NCVA.RAPID.HYPOPERFUSION_INTENSITY_RATIO"
* hid -> "NCVA.RAPID.HID"
* zrapid -> "NCVA.RAPID.ZRAPID"
* mtqualified -> "NCVA.RAPID.MTQUALIFIED"
* mtqualified16hDefuse3 -> "NCVA.RAPID.MTQUALIFIED_16H_DEFUSE3"
* mtqualified6hExtendia -> "NCVA.RAPID.MTQUALIFIED_6H_EXTENDIA"
* mtqualified6hSwiftprime -> "NCVA.RAPID.MTQUALIFIED_6H_SWIFTPRIME"

Mapping: StrokeRapidLMToFHIR
Source: StrokeRapidLM
Target: "urn:vgh-stroke:fhir-profiles"
Id: fhir
Title: "FHIR 路徑對應"
Description: "各元素對應的 FHIR Profile 與元素路徑。沒有臨床資源對應的元素，原值保存在 StrokeRegistryResponse 的 raw 題目。"
* -> "StrokeRapidBundle：Bundle" "一次 RAPID 掃描的完整資料以一個 StrokeRapidBundle 傳送"
* hisnummark -> "StrokePatient：Patient.identifier:medicalRecord.value" "病歷號原樣保留，不作為 Patient.id。type 固定 v2-0203 MR，system 用院方核定的網址（範例 http://www.vghks.gov.tw/patient-id）。每個院所+病歷號建一筆 Patient。"
* rpreqno -> "StrokeRegistryResponse：QuestionnaireResponse.item:rapidRequestNo.answer.valueString" "linkId 填 rapid.rpreqno，原樣保存。確認語意前不寫入 ImagingStudy／ServiceRequest identifier。"
* scantype -> "StrokeImagingStudy：ImagingStudy.procedureCode.coding:rapidScanType" "StrokeRapidScanTypeCS 原碼填 CTP／CTA／NCCT（去除尾端空白）；modality 另填 DCM#CT。申請序號（RPREQNO）不是 DICOM UID，不建立 series。"
* latestseriesdate -> "StrokeImagingResult：Observation.effectiveDateTime" "確認結果取自該最近掃描序列時，才作為該筆影像判讀結果的 effectiveDateTime（只填 YYYY-MM-DD）；未確認配對時原日期存入 StrokeRegistryResponse。"
* aspectsAffectedside -> "StrokeImagingResult：Observation.valueCodeableConcept" "code = stroke-observation#aspects-affected-side；項目代碼填 Observation.code.coding:strokeObservation。代碼系統填 http://vgh-stroke-ig.fhir.tw/CodeSystem/affected-side（L 左腦、R 右腦），text 填左腦／右腦。可獨立建一筆 Observation，或在已配對的 ASPECTS／CTA 結果改用 bodySite.text，兩者擇一。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* aspects -> "StrokeImagingResult：Observation.valueInteger" "code = stroke-observation#aspects-score；項目代碼填 Observation.code.coding:strokeObservation。ASPECTS 填 0–10 原值。EVT 與 RAPID 來源在配對核定前各自建立。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* ctaAffectedside -> "StrokeImagingResult：Observation.valueCodeableConcept" "code = stroke-observation#cta-affected-side；項目代碼填 Observation.code.coding:strokeObservation。代碼系統填 http://vgh-stroke-ig.fhir.tw/CodeSystem/affected-side（L 左腦、R 右腦），text 填左腦／右腦。可獨立建一筆 Observation，或在已配對的 ASPECTS／CTA 結果改用 bodySite.text，兩者擇一。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* cbfVolume -> "StrokeImagingResult：Observation.valueQuantity" "code = stroke-observation#perfusion-core-volume；項目代碼填 Observation.code.coding:strokeObservation。單位填 UCUM mL，填入原值。EVT 與 RAPID 在配對核定前各自建立。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* tmaxVolume -> "StrokeImagingResult：Observation.valueQuantity" "code = stroke-observation#tmax-over-6s-volume；項目代碼填 Observation.code.coding:strokeObservation。單位填 UCUM mL，填入 Tmax > 6 秒體積。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* mismatchVolume -> "StrokeImagingResult：Observation.valueQuantity" "code = stroke-observation#perfusion-mismatch-volume；項目代碼填 Observation.code.coding:strokeObservation。單位填 UCUM mL，填入原值。EVT 與 RAPID 在配對核定前各自建立。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* mismatchRatio -> "StrokeImagingResult：Observation.valueQuantity" "code = stroke-observation#perfusion-mismatch-ratio；比值原值（廠商公式算出）填入 valueQuantity，單位填 UCUM 1；只有 CTP 影像才有值。若為 9999 表示無法計算，不填 valueQuantity，改填 dataAbsentReason = unknown，且 dataAbsentReason.text 填「來源 9999：無法計算」；空白同樣填 unknown。真實 0 保留。"
* hypoperfusionIntensityRatio -> "StrokeImagingResult：Observation.valueQuantity" "code = stroke-observation#hypoperfusion-intensity-ratio；項目代碼填 Observation.code.coding:strokeObservation。單位填 UCUM 1（無單位比值）。院方核定 LOINC 後，在同一 code 另加 coding（依父層 code 綁定）。"
* hid -> "StrokeOrganization：Organization.identifier.value" "院所代號（例 1A0）原樣填入 identifier.value。"
* zrapid -> "StrokeProvenance：Provenance.occurredDateTime" "來源資料時戳：語意確認前不填 occurredDateTime，只保留原值；語意已確認、時區未確認時，只填日期（YYYY-MM-DD），時間以 StrokeEventTimeOnly 擴充附在該元素上，原值同時保存在原始值題目；語意與時區都確認後，填帶已確認時區的完整日期時間。"
* mtqualified -> "StrokeRegistryResponse：QuestionnaireResponse.item:rawRapid.item(linkId = raw.rapid.mtqualified).answer.valueString" "尚無臨床資源對應，只保存原值"
* mtqualified16hDefuse3 -> "StrokeRegistryResponse：QuestionnaireResponse.item:rawRapid.item(linkId = raw.rapid.mtqualified16hDefuse3).answer.valueString" "尚無臨床資源對應，只保存原值"
* mtqualified6hExtendia -> "StrokeRegistryResponse：QuestionnaireResponse.item:rawRapid.item(linkId = raw.rapid.mtqualified6hExtendia).answer.valueString" "尚無臨床資源對應，只保存原值"
* mtqualified6hSwiftprime -> "StrokeRegistryResponse：QuestionnaireResponse.item:rawRapid.item(linkId = raw.rapid.mtqualified6hSwiftprime).answer.valueString" "尚無臨床資源對應，只保存原值"
